EndPoint
dsccommunity/SqlServerDsc pull request #1617
Opened 2020-09-18 11:12 UTC by Fiander

#### Adds ServiceBroker to EndPoint #498

#### Task list

- [ ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [X ] Resource documentation updated in the resource's README.md.
- [X ] Resource parameter descriptions updated in schema.mof.
- [ X] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [X ] Examples updated.
- [X ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ X] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2020-09-24 17:57 UTC, johlju commented
Great work! Will review as soon as I have time. 🙂

2020-09-24 18:52 UTC, Fiander commented
No problem, gives me time fighting the unit tests....

2020-09-30 07:14 UTC, johlju requested changes
Really impressive work on this change! Thank you for the hard work on this! :smile: 

> Reviewed 10 of 12 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-:-MISqy9n0EZOh6nQ54IC:btgxa5v)* status: all files reviewed, 34 unresolved discussions (waiting on @Fiander)

___
*[CHANGELOG.md, line 7 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISjO9_7ZbF1b25zAz3:-MISjO9_7ZbF1b25zAz4:b-4fbfup) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/CHANGELOG.md#L7)):*
> ```
> - SqlServerDsc
> ```

Please add blank row before this row.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 237 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISjgcJA7Sopex8HuuE:-MISjgcK9WEjQh-fCoBu:brudaf2) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L237)):*
> ```
> if (($EndpointType -eq 'DatabaseMirroring')  -or ($EndpointType -eq 'ServiceBroker'))
> ```

We could simplify this with `if ($EndpointType -in @('DatabaseMirroring','ServiceBroker'))`?
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 249 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISjTFyAWB45u2cycH-:-MISjTFyAWB45u2cycH0:bcaswyr) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L249)):*
> ```
> switch ($EndpointType)
> ```

Please add blank row before this row.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 259 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISjUrEAH585RQygaXb:-MISjUrEAH585RQygaXc:b40wni3) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L259)):*
> ```
> 'ServiceBroker'
> ```

Please add blank row before this row.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 267 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISjanw-UNPmSKpPqfg:-MISjanw-UNPmSKpPqfh:b2ccnji) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L267)):*
> ```
> <#
> ```

Please add blank row before this row.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 328 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISkdzB-XYWxesh-avh:-MISkdzB-XYWxesh-avi:btmb8ca) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L328)):*
> ```
> #These are for ServiceBroker and DatabaseMirroring
> ```

I suggest we add an `if ($EndpointType -in @('DatabaseMirroring','ServiceBroker'))` instead of this comment so this is already prepared for a future endpoint that does not support this property.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 375 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISk5TxCz1_Acmphilq:-MISk5TxCz1_Acmphilr:b40wni3) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L375)):*
> ```
> 'ServiceBroker'
> ```

Please add blank row before this row.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 568 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISlQYB-aiJyuV8A6d7:-MISlQYB-aiJyuV8A6d8:b-qduvul) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L568)):*
> ```
> if ($getTargetResourceResult.IsMessageForwardingEnabled -ne $IsMessageForwardingEnabled)
> ```

We should only do this evaluation if the endpoint type is 'ServiceBroker' even if the user wrongly set the property for another endpoint type?
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 576 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISlOY_3Rk8x5PIW7qD:-MISlOY_3Rk8x5PIW7qE:b82sha9) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L576)):*
> ```
> if ($getTargetResourceResult.MessageForwardingSize -ne $MessageForwardingSize)
> ```

We should only do this evaluation if the endpoint type is 'ServiceBroker' even if the user wrongly set the property for another endpoint type?
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.schema.mof, line 13 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISleYc62-NF3_Yd6y8:-MISleYc62-NF3_Yd6y9:b-xtwjp8) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.schema.mof#L13)):*
> ```
> Uint32
> ```

Minor. UInt32 (upper 'I').
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 111 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISm69-0p3bEdX4YPX9:-MISm69-0p3bEdX4YPXA:b-k5nfac) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L111)):*
> ```
> #                    return New-Object -TypeName Object |
> ```

Think this commented row remove should be removed? (guessing left-over debug code)
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 278 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISn2jJ37a0o4g_cOFu:-MISn2jJ37a0o4g_cOFv:b-gmsveh) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L278)):*
> ```
> $testParameters = $defaultSsbrParameters
> ```

We should change it it to (using clone) so properties are not removed in the original hashtable if we remove them from the "copy".

```
$testParameters = $defaultSsbrParameters.Clone()
```
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 282 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISp5dS5Q8mhv1TsZP-:-MISp5dT6i2Cw1YwthB7:b51v0l0) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L282)):*
> ```
> $testParameters = $defaultSsbrParameters
> ```

This can be remove since we set it before the Context-block.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 288 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISp9hv8uA4ydKdAUd_:-MISp9hv8uA4ydKdAUda:b51v0l0) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L288)):*
> ```
> $testParameters = $defaultSsbrParameters
> ```

This can be remove since we set it before the Context-block.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 301 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISpAZdBq2o9KxBfsEM:-MISpAZdBq2o9KxBfsEN:b51v0l0) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L301)):*
> ```
> $testParameters = $defaultSsbrParameters
> ```

This can be remove since we set it before the Context-block.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 311 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISnRqJ6NgKHsGpE9QZ:-MISnRqJ6NgKHsGpE9Q_:blhu6cz) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L311)):*
> ```
> $testParameters = $defaultSsbrParameters
> ```

This can be remove since we set it before the previous Context-block.
___
*[tests [...]

2020-09-30 08:15 UTC, Fiander commented
Just pushed a new version. Hope i got all requests. While editing the rownumbers kept changing. 
Note to self.... start at the bottom of a file next time.

>tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 282 at r3 (raw file):
>$testParameters = $defaultSsbrParameters
>This can be remove since we set it before the Context-block.

This one i did not remove. Because of the beforeeach block where `$testParameters = $defaultParameters` stands.
Did add comment about that one at all places.

2020-09-30 09:51 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617)* status: 8 of 12 files reviewed, 33 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 237 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISjgcJA7Sopex8HuuE:-MITM2Vt6anDHhe08pcf:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L237)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if (($EndpointType -eq 'DatabaseMirroring')  -or ($EndpointType -eq 'ServiceBroker'))
> ```

We could simplify this with `if ($EndpointType -in @('DatabaseMirroring','ServiceBroker'))`?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 249 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISjTFyAWB45u2cycH-:-MITM3bkDLknJpFOMTU2:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L249)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> switch ($EndpointType)
> ```

Please add blank row before this row.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 259 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISjUrEAH585RQygaXb:-MITM47g9YXfJh-lb-sP:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L259)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'ServiceBroker'
> ```

Please add blank row before this row.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 267 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISjanw-UNPmSKpPqfg:-MITM5vb0i2yD_FYvNew:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L267)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> <#
> ```

Please add blank row before this row.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 328 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISkdzB-XYWxesh-avh:-MITM90I4FNUOOgom_Jo:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L328)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #These are for ServiceBroker and DatabaseMirroring
> ```

I suggest we add an `if ($EndpointType -in @('DatabaseMirroring','ServiceBroker'))` instead of this comment so this is already prepared for a future endpoint that does not support this property.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 375 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISk5TxCz1_Acmphilq:-MITMAHd3ftgfdn9e8Ok:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L375)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'ServiceBroker'
> ```

Please add blank row before this row.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, line 568 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISlQYB-aiJyuV8A6d7:-MITMD3Q1RdfZ8BoNwFz:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1#L568)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($getTargetResourceResult.IsMessageForwardingEnabled -ne $IsMessageForwardingEnabled)
> ```

We should only do this evaluation if the endpoint type is 'ServiceBroker' even if the user wrongly set the property for another endpoint type?
</blockquote></details>

Done.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 111 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISm69-0p3bEdX4YPX9:-MITMJEh4Dh-ynvuSX4d:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L111)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #                    return New-Object -TypeName Object |
> ```

Think this commented row remove should be removed? (guessing left-over debug code)
</blockquote></details>

Done.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 278 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISn2jJ37a0o4g_cOFu:-MITPIS60bcvcjonrnOj:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L278)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $testParameters = $defaultSsbrParameters
> ```

We should change it it to (using clone) so properties are not removed in the original hashtable if we remove them from the "copy".

```
$testParameters = $defaultSsbrParameters.Clone()
```
</blockquote></details>

Done.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 282 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISp5dS5Q8mhv1TsZP-:-MITPJuc7SgCwnuAlDKP:b-88jfg9) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L282)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $testParameters = $defaultSsbrParameters
> ```

This can be remove since we set it before the Context-block.
</blockquote></details>

no, in the before each block there is code like this:
$testParameters = $defaultParameters
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 288 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISp9hv8uA4ydKdAUd_:-MITPdNs2fYGsg4NkNUI:bpawr6n) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L288)):*
> no, in the before each block there is code like this:
> $testParameters = $defaultParameters
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 301 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISpAZdBq2o9KxBfsEM:-MITPfO_8ukFv84vw_Jp:b-88jfg9) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L301)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $testParameters = $defaultSsbrParameters
> ```

This can be remove since we set it before the Context-block.
</blockquote></details>

no, in the before each block there is code like this:
$testParameters = $defaultParameters
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 311 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISnRqJ6NgKHsGpE9QZ:-MITPgBwBG_pgDTXW9T7:b-88jfg9) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L311)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $testParameters = $defaultSsbrParamete [...]

2020-10-01 17:28 UTC, johlju commented
I will try to review it again tomorrow. Was too busy today. 🙂

2020-10-02 08:22 UTC, johlju requested changes
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617)* status: all files reviewed, 2 unresolved discussions (waiting on @Fiander)

___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 915 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISqYHX07MybdMSSTp2:-MIcNUd790gha5UyPfmI:b-hgbt7t) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L915)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

nope, no reason... deleted it.
</blockquote></details>

I think we need to add it back and remove the comments, because they are part of the that particular unit test. It is testing that all expect one property is different.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 923 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISqkQE2CzKGa4oBpxB:-MIcOUjUDj0mufcU0J_9:bl78p5g) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L923)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we need to add it back and remove the comments, because they are part of the that particular unit test. They are not commented out in the original code.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 949 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISqnUs7HuZyWnBg6Dh:-MIcOW075Azyz1TMSLDu:bl78p5g) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L949)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we need to add it back and remove the comments, because they are part of the that particular unit test. They are not commented out in the original code.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 982 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISqodY-3QlusumxWTe:-MIcOXVV65tXf3ldjhBi:bl78p5g) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L982)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we need to add it back and remove the comments, because they are part of the that particular unit test. They are not commented out in the original code.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 1017 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISqq0D0A3Y9CUvNsuu:-MIcOYXF8oOp6lg8gQQz:bl78p5g) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L1017)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we need to add it back and remove the comments, because they are part of the that particular unit test. They are not commented out in the original code.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 1047 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISqrB01gK66Zh3Ek-M:-MIcOZXQEG4MIADLsc2P:bl78p5g) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L1047)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we need to add it back and remove the comments, because they are part of the that particular unit test. They are not commented out in the original code.
___
*[tests/Unit/DSC_SqlEndpoint.Tests.ps1, line 1061 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-MISqsFk7g5ikSdrncPS:-MIcO_MI7KXboI5rj9zf:bl78p5g) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9ba90060ea2def2910b88d3295a07f8225140dca/tests/Unit/DSC_SqlEndpoint.Tests.ps1#L1061)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we need to add it back and remove the comments, because they are part of the that particular unit test. They are not commented out in the original code.


<!-- Sent from Reviewable.io -->

2020-10-02 08:26 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Ignore previous comments. Looks good to me when I went through it again. 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-:-MIcPkgl8IZOFN4E_-Ym:bzgj0z3)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-02 08:28 UTC, merged

2020-10-02 08:29 UTC, johlju commented
@Fiander awesome work on this one! Thank you! 🙇 😃

2020-10-02 08:38 UTC, Fiander commented
> <img alt=":lgtm:" width="61" height="20" src="https://camo.githubusercontent.com/41b3ec3419116e3b3f84507ad965646ce4ce1f0c/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67">
> 
> Ignore previous comments. Looks good to me when I went through it again.
> 
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1617#-:-MIcPkgl8IZOFN4E_-Ym:bzgj0z3)_ status: :shipit: complete! all files reviewed, all discussions resolved

when reading those tests, those rows seemed unnecessary to me, and the tests function without them.