SQLRole resource overhaul for tests. fix for #550
dsccommunity/SqlServerDsc pull request #1623
Opened 2020-10-06 10:12 UTC by Fiander

Major overhaul of SQLRole, added tests, and fix for issue #550

#### Pull Request (PR) description
some remodeling of SqlRole.
lots of extra tests,
fix for #550 

#### This Pull Request (PR) fixes the following issues
Fixes #550 

#### Task list

- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [X] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2020-10-07 13:24 UTC, johlju requested changes
Thank you for this. This is gonna take a while to review for me. It also feels like a breaking change with the change for Get-TargetResource if users are depending on how it worked prior to this suggested change. But I can stand behind the change that it should only report 'Present' or 'Absent' if all mandatory parameter is in the current state, in this case if the role exist.

I did a quick glance, so this is just a first batch of comments. :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-:-MJ28H0UEfrc3mnyH268:b-16gf8r)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @Fiander)

___
*[CHANGELOG.md, line 8 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ293zP0zB-9yv5C0Ua:-MJ293zP0zB-9yv5C0Ub:b-dahkja) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/CHANGELOG.md#L8)):*
> ```
> -SqlRole
> ```

Please add a space after the dash `- SqlRole`.
___
*[CHANGELOG.md, line 10 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ29AtGCINfIWkfI0bj:-MJ29AtGCINfIWkfI0bk:b-ws2uk4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/CHANGELOG.md#L10)):*
> ```
> - Major overhaul of resource, added lots of tests.
>   - Added sanitize function for issue #550
> ```

Please make these entries more descriptive of what this PR changes so it is clear to other users how it works now (what changed). These entries are used for the release notes in the automatic release pipeline. Also reference the issue like previous entries for the specific change log entry the fixes that issue.
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 22 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ2ArC9Al9u1Y44NuAo:-MJ2ArC9Al9u1Y44NuAp:bvkc5ye) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L22)):*
> ```
> #returns $null if role does not exist. Else an array of all role members. This Array can be empty.
> ```

This comment seems out of place. Is it meant to be in a `.NOTES` section for design information to other contributors? 
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 80 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ2BhvlDpS-C10BPhCl:-MJ2BhvlDpS-C10BPhCm:bzcgniw) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L80)):*
> ```
> members
> ```

`Members` (upper-case 'M')
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 81 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ2BnC7ABdurv9AkxhE:-MJ2BnC808yDuSjCwxo0:bvvs75q) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L81)):*
> ```
> membersToInclude
> ```

`MembersToInclude` (upper-case 'M')
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 82 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ2Bq3jCpgdJoz6oqrK:-MJ2Bq3jCpgdJoz6oqrL:bus4ry6) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L82)):*
> ```
> membersToExclude
> ```

`MembersToExclude` (upper-case 'M')
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 620 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ2CDkjA4k-M-4ryNDq:-MJ2CDkjA4k-M-4ryNDr:beym4dm) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L620)):*
> ```
> Sanitize-InputObjects
> ```

I rather see this using approved verbs (`Get-Verb`). 
Suggest renaming this to what it does `<verb>-MemberParameters` (something better than InputObjects which could be anything) :slightly_smiling_face: 
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 647 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ2Cg-V00Pf9bAyeF1m:-MJ2Cg-V00Pf9bAyeF1n:begt0ov) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L647)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> if ($MembersToInclude -or $MembersToExclude)
>         {
>             $errorMessage = $script:localizedData.MembersToIncludeAndExcludeParamMustBeNull
>             New-InvalidOperationException -Message $errorMessage
>         }
> ```
</details>


Suggest removing this and instead use the helper function out in the *-ResourceTarget function:
https://github.com/dsccommunity/DscResource.Common#assert-boundparameter

The module is available and imported at the top of this module script file.
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 652 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ2DmjVCzVWcaAZRcRI:-MJ2DmjVCzVWcaAZRcRJ:b2s15dq) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L652)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
> if ($ServerRoleName -eq 'sysadmin')
>         {
>             if ($Members -notcontains 'SA')
>             {
>                 $Members += 'SA'
>             }
>         }
>     }
>     else
>     {
>         if ($ServerRoleName -eq 'sysadmin')
>         {
>             if ($MembersToExclude -contains 'SA')
>             {
>                 $MembersToExclude = $MembersToExclude -ne 'SA'
>             }
>         }
> ```
</details>


Is it possible to remove some of the duplicate code here? 


<!-- Sent from Reviewable.io -->

2020-10-07 17:04 UTC, Fiander commented
Hi Johan, will do all those things.
I just did not see a simple way to integrate the skip SA part with the functions as they were.

For now just ignore the review I'm really fighting the integration tests. something is off on my test machine and no mof files are generated anymore. Of no single resource. not related to this resource. but i want to do this right.

I do have one request... could you please take a look at the unit test row 973 (It 'Should return false when ErrorAction is set to SilentlyContinue' )
I just don't believe this test works as expected. the success of this test seems just plain luck.
As i see it, the exception goes, and result will never get a value or even exist. 
then, because it does not exist, it evaluates to $false what makes the test a success. 
I would vote to remove this test, but it is not my code so i want your advice. 

Last thing: would Get-CorrectedMemberParameters be a good name for renaming Sanitize-InputObjects?

2020-10-15 11:43 UTC, johlju commented
I will get back to this as soon as I can. The day job is keeping me away. :)

2020-10-15 12:11 UTC, Fiander commented
no problem, I just found the reason why the integration tests kept failing. will post a new build tonight.

2020-10-31 15:26 UTC, johlju requested changes
Sorry for not reviewing this sooner, but the regular work has been a lot lately and taking all the bandwidth.

> Reviewed 5 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-:-MKz9OiN5-nnG9lk2muc:bsx2ux8)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @Fiander)

___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 152 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKz8FVa8fk4VINKvlY3:-MKz8FVa8fk4VINKvlY4:bfpe1h7) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/235c064ea1ca5b7023f9e96d64642a4b06ae853a/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L152)):*
> ```
>         MembersToInclude = $MembersToInclude
>         MembersToExclude = $MembersToExclude
> ```

Instead of returning `$null` I would rather that we keep this so it returns the actual values that was provided in the configuration. When you run Get-DscConfiguration or similar it is possible to compare the actual members with the desired members in thouse two properties. Although I can see it will not return the desired members if only the `Members` property was used... :thinking:  But keeping these avoids a breaking change. What are your thoughts?
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 620 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzAuay6S-cRKlmjBit:-MKzAuay6S-cRKlmjBiu:bxqy35j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L620)):*
> ```
>             #this is never reached. Commented out; This should be removed togeter with row 979 till 1017 in DSC_SqlRole.Tests.ps1, but not my decision
>             #return $false
> ```

Yes we can remove it, and the test. Must be a left over that was missed in a previous change.
___
*[source/DSCResources/DSC_SqlRole/README.md, line 8 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzBha27CZrlJkkpCJl:-MKzBha27CZrlJkkpCJm:bnkgp2m) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/source/DSCResources/DSC_SqlRole/README.md#L8)):*
> ```
> When the target role is sysadmin, SA wil not be removed from this role.
> ```

Maybe this is a bit more descriptive? "When the target role is sysadmin the DSC resource will prevent the user 'sa' from being removed. This is done to keep the DSC resource from throwing an error since SQL Server does not allow this user to be removed."
___
*[tests/Integration/DSC_SqlRole.Integration.Tests.ps1, line 103 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzDzke8-V6sF8E_FFk:-MKzDzkfCz741OdIzdz7:b-vtxgk) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Integration/DSC_SqlRole.Integration.Tests.ps1#L103)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>             $configurationParameters = @{
>                 OutputPath                 = $TestDrive
>                 # The variable $ConfigurationData was dot-sourced above.
>                 ConfigurationData          = $ConfigurationData
>             }
>
>             & $configurationName @configurationParameters
>
>             $startDscConfigurationParameters = @{
>                 Path         = $TestDrive
>                 ComputerName = 'localhost'
>                 Wait         = $true
>                 Verbose      = $true
>                 Force        = $true
>                 ErrorAction  = 'Stop'
>             }
> ```
</details>


This change will add a technical debt when we move to Pester 5. In Pester 5 code should either be inside a it-block or inside a before*-block. Also by changing this the test will look different than all other integration tests. What was the reason this block moved outside the it-block? 
___
*[tests/Integration/DSC_SqlRole.Integration.Tests.ps1, line 153 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzCwAeDPxxPG65usuw:-MKzCwAeDPxxPG65usux:b-iq2967) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Integration/DSC_SqlRole.Integration.Tests.ps1#L153)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>             $configurationParameters = @{
>                 OutputPath                 = $TestDrive
>                 # The variable $ConfigurationData was dot-sourced above.
>                 ConfigurationData          = $ConfigurationData
>             }
>
>             & $configurationName @configurationParameters
>
>             $startDscConfigurationParameters = @{
>                 Path         = $TestDrive
>                 ComputerName = 'localhost'
>                 Wait         = $true
>                 Verbose      = $true
>                 Force        = $true
>                 ErrorAction  = 'Stop'
>             }
> ```
</details>


same as previous comment.
___
*[tests/Integration/DSC_SqlRole.Integration.Tests.ps1, line 206 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzE64t5reO7CED4WXX:-MKzE64t5reO7CED4WXY:bf46os1) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Integration/DSC_SqlRole.Integration.Tests.ps1#L206)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>             $configurationParameters = @{
>                 OutputPath                 = $TestDrive
>                 # The variable $ConfigurationData was dot-sourced above.
>                 ConfigurationData          = $ConfigurationData
>             }
>
>             & $configurationName @configurationParameters
>
>             $startDscConfigurationParameters = @{
>                 Path         = $TestDrive
>                 ComputerName = 'localhost'
>                 Wait         = $true
>                 Verbose      = $true
>                 Force        = $true
>                 ErrorAction  = 'Stop'
>             }
> ```
</details>


Same as previous comment.
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 251 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzEJjIAwaZF7zclvZF:-MKzEJjIAwaZF7zclvZG:bgkhttd) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Unit/DSC_SqlRole.Tests.ps1#L251)):*
> ```
> $result = Get-TargetResource @testParameters
> ```

What was the reason this block moved outside the it-block?  This code should be inside the It-block so that any unexpected error that is thrown is correctly handled by the It-block.

I unit tests it is okay to duplicate code, because it is more important that the unit tests is easily readable. In this case it is okay that `Get-TargetResource` is called for each It-block.

See comment about Pester 5 as well that I mentioned in the integration tests.

Throughout the unit test.
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 267 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzF_1W1eLG2ipQs4sH:-MKzF_1W1eLG2ipQs4sI:b-vibo7g) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Unit/DSC_SqlRole.Tests.ps1#L267)):*
> ```
>                 It 'Should be executed once' {
>                     Assert-MockCalled -CommandName Connect-SQL -Exactly -Times 1 -Scope Context
>                 }
> ```

We should call `Get-TargetResource @testParameters` in this it-block as well so that `Scope` can be  `It`.

Throughout the code.


<!-- Sent from Reviewable.io -->

2020-10-31 19:59 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 152 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKz8FVa8fk4VINKvlY3:-ML-6J6M7BEjDgtkDYvE:b-pdzgxj) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/235c064ea1ca5b7023f9e96d64642a4b06ae853a/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L152)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         MembersToInclude = $MembersToInclude
>         MembersToExclude = $MembersToExclude
> ```

Instead of returning `$null` I would rather that we keep this so it returns the actual values that was provided in the configuration. When you run Get-DscConfiguration or similar it is possible to compare the actual members with the desired members in thouse two properties. Although I can see it will not return the desired members if only the `Members` property was used... :thinking:  But keeping these avoids a breaking change. What are your thoughts?
</blockquote></details>

Because the return will always be the actual members in the role, and not the desired members in a role, id do not see the point in doing the same for $MembersToInclude and exclude. When using this, you wil always have to use other code for the original value of $Members. The way I made it, makes the function much more consistent. you get "present" if the role exists, and when it exists, you get the current members. The way it was: if a role does not exists, you still get $membersToInclude And $membersToExclude. To me that seems strange behavior. 
___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 620 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzAuay6S-cRKlmjBit:-ML-9AWUDoqdvoRTfkBN:b-ynwl21) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L620)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>             #this is never reached. Commented out; This should be removed togeter with row 979 till 1017 in DSC_SqlRole.Tests.ps1, but not my decision
>             #return $false
> ```

Yes we can remove it, and the test. Must be a left over that was missed in a previous change.
</blockquote></details>

I removed it.
___
*[source/DSCResources/DSC_SqlRole/README.md, line 8 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzBha27CZrlJkkpCJl:-ML-9daw3LP_5AiMOMbZ:b-od938k) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/source/DSCResources/DSC_SqlRole/README.md#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> When the target role is sysadmin, SA wil not be removed from this role.
> ```

Maybe this is a bit more descriptive? "When the target role is sysadmin the DSC resource will prevent the user 'sa' from being removed. This is done to keep the DSC resource from throwing an error since SQL Server does not allow this user to be removed."
</blockquote></details>

I like your style :-) it is done
___
*[tests/Integration/DSC_SqlRole.Integration.Tests.ps1, line 103 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzDzke8-V6sF8E_FFk:-ML-9pryBAqvDiYvH1TO:bri5crn) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Integration/DSC_SqlRole.Integration.Tests.ps1#L103)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>             $configurationParameters = @{
>                 OutputPath                 = $TestDrive
>                 # The variable $ConfigurationData was dot-sourced above.
>                 ConfigurationData          = $ConfigurationData
>             }
>
>             & $configurationName @configurationParameters
>
>             $startDscConfigurationParameters = @{
>                 Path         = $TestDrive
>                 ComputerName = 'localhost'
>                 Wait         = $true
>                 Verbose      = $true
>                 Force        = $true
>                 ErrorAction  = 'Stop'
>             }
> ```

This change will add a technical debt when we move to Pester 5. In Pester 5 code should either be inside a it-block or inside a before*-block. Also by changing this the test will look different than all other integration tests. What was the reason this block moved outside the it-block? 
</blockquote></details>

to be honest.....
I just forgot to encapsulate it in a BeforeAll...
I see that code as setup code.
https://github.com/pester/Pester#put-setup-in-beforeall
___
*[tests/Integration/DSC_SqlRole.Integration.Tests.ps1, line 153 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzCwAeDPxxPG65usuw:-ML-AMYA7nm_a6W6OVyy:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Integration/DSC_SqlRole.Integration.Tests.ps1#L153)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>             $configurationParameters = @{
>                 OutputPath                 = $TestDrive
>                 # The variable $ConfigurationData was dot-sourced above.
>                 ConfigurationData          = $ConfigurationData
>             }
>
>             & $configurationName @configurationParameters
>
>             $startDscConfigurationParameters = @{
>                 Path         = $TestDrive
>                 ComputerName = 'localhost'
>                 Wait         = $true
>                 Verbose      = $true
>                 Force        = $true
>                 ErrorAction  = 'Stop'
>             }
> ```

same as previous comment.
</blockquote></details>

Done.
___
*[tests/Integration/DSC_SqlRole.Integration.Tests.ps1, line 206 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzE64t5reO7CED4WXX:-ML-ANE84aah4eRq4j5A:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Integration/DSC_SqlRole.Integration.Tests.ps1#L206)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>             $configurationParameters = @{
>                 OutputPath                 = $TestDrive
>                 # The variable $ConfigurationData was dot-sourced above.
>                 ConfigurationData          = $ConfigurationData
>             }
>
>             & $configurationName @configurationParameters
>
>             $startDscConfigurationParameters = @{
>                 Path         = $TestDrive
>                 ComputerName = 'localhost'
>                 Wait         = $true
>                 Verbose      = $true
>                 Force        = $true
>                 ErrorAction  = 'Stop'
>             }
> ```

Same as previous comment.
</blockquote></details>

Done.
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 251 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzEJjIAwaZF7zclvZF:-ML-ARDf4XYOu9FdW3gs:bvactlo) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Unit/DSC_SqlRole.Tests.ps1#L251)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $result = Get-TargetResource @testParameters
> ```

What was the reason this block moved outside the it-block?  This code should be inside the It-block so that any unexpected error that is thrown is correctly handled by the It-block.

I unit tests it is okay to duplicate code, because it is more important that the unit tests is easily readable. In this case it is okay that `Get-TargetResource` is c [...]

2020-11-01 12:01 UTC, johlju requested changes
Did you push a change, I see comments that things have been resolved but seems there is no commit. Maybe you waiting for answers on your comments, before pushing if so ignore this. :slightly_smiling_face: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-:-ML2YpGrCsF2QdlVBN80:by2huuo)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 152 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKz8FVa8fk4VINKvlY3:-ML2WyFoENeeY1RuVCnO:b-2yyqt4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/235c064ea1ca5b7023f9e96d64642a4b06ae853a/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L152)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Because the return will always be the actual members in the role, and not the desired members in a role, id do not see the point in doing the same for $MembersToInclude and exclude. When using this, you wil always have to use other code for the original value of $Members. The way I made it, makes the function much more consistent. you get "present" if the role exists, and when it exists, you get the current members. The way it was: if a role does not exists, you still get $membersToInclude And $membersToExclude. To me that seems strange behavior. 
</blockquote></details>

Thanks for your view on it. I agree with your reasoning. I wonder if we should add a `.NOTES` section in the comment-based help for `Get-TargetResource` and add your reasoning above. So that another contributor does not add them back (and a reminder for maintainers if one would ever). :thinking: 
___
*[tests/Integration/DSC_SqlRole.Integration.Tests.ps1, line 103 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzDzke8-V6sF8E_FFk:-ML2YnHr7s09Cqhf3-eW:b8yx6ro) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Integration/DSC_SqlRole.Integration.Tests.ps1#L103)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

to be honest.....
I just forgot to encapsulate it in a BeforeAll...
I see that code as setup code.
https://github.com/pester/Pester#put-setup-in-beforeall

</blockquote></details>

This line `& $configurationName @configurationParameters` is actually the "Should _compile_" of the It-block and is a test to verify the schema against a configuration. So I think that part is not setup code in this case. I agree the other stuff can go in a BeforeAll-block.
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 251 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzEJjIAwaZF7zclvZF:-ML2_RJR7IGvCSoHWkZr:buxityv) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Unit/DSC_SqlRole.Tests.ps1#L251)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

to be honest.....
I just forgot to encapsulate it in a BeforeAll...
I see that part of the code as setup code.
https://github.com/pester/Pester#put-setup-in-beforeall
</blockquote></details>

That section explains the new behavior of Pester 5 where the main setup code for the test file must be in a Describe-block, in this test file that would be lines 1-42 that needs to be in a BeforeAll-block at the top of the file. That is not possible with Pester 4.

With that said I would be okay to have the `$result = Get-TargetResource @testParameters` in a BeforeEach-block so it is run prior each It-block. Though I'm not sure how Pester handles errors thrown in the BeforeEach/BeforeAll-block. But maybe you can just add a `throw` in the code and see how Pester handles it? If Pester catches the error correctly (outputs a correct error to the contributor) then I'm okay with it :smile: 

Thoughts?
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 258 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-ML2fLNN0BIL3p4dR99S:-ML2fDhDBB0cOSKzD8dI:b-3x0fmp) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Unit/DSC_SqlRole.Tests.ps1#L258)):*
> ```
> -Be $null
> ```

Can be `-BeNullOrEmpty` instead?
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 267 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzF_1W1eLG2ipQs4sH:-ML2dWeC3Cymyl2M65lz:bhl7o6t) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Unit/DSC_SqlRole.Tests.ps1#L267)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

I did it this way to get more consistent code

we wil have to change this anyway for pester v5, but as of now i can not find how it should be.

from:
https://pester.dev/docs/commands/Assert-MockCalled
THIS COMMAND IS OBSOLETE AND WILL BE REMOVED SOMEWHERE DURING v5 LIFETIME, USE Should -Invoke INSTEAD.



</blockquote></details>

`Assert-MockCalled` basically just have to be renamed to `Should -Invoke` for Pester 5. Otherwise the behavior is the same as far as I know (no breaking changes in the parameters).

Let se how this plays out depending on the previous comment. Resolving this comment for now.


<!-- Sent from Reviewable.io -->

2020-11-01 12:27 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 652 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MJ2DmjVCzVWcaAZRcRI:-ML2j1j42-rUA-kO0VcR:b-pe4o1m) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c16cd25aa1aee6001c14df0f606dfef06cdd4183/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L652)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($ServerRoleName -eq 'sysadmin')
>         {
>             if ($Members -notcontains 'SA')
>             {
>                 $Members += 'SA'
>             }
>         }
>     }
>     else
>     {
>         if ($ServerRoleName -eq 'sysadmin')
>         {
>             if ($MembersToExclude -contains 'SA')
>             {
>                 $MembersToExclude = $MembersToExclude -ne 'SA'
>             }
>         }
> ```

Is it possible to remove some of the duplicate code here? 
</blockquote></details>

euh... what duplicate code?
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 251 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzEJjIAwaZF7zclvZF:-ML2jfng8C0pWys4aw_0:b-1oehkw) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Unit/DSC_SqlRole.Tests.ps1#L251)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

That section explains the new behavior of Pester 5 where the main setup code for the test file must be in a Describe-block, in this test file that would be lines 1-42 that needs to be in a BeforeAll-block at the top of the file. That is not possible with Pester 4.

With that said I would be okay to have the `$result = Get-TargetResource @testParameters` in a BeforeEach-block so it is run prior each It-block. Though I'm not sure how Pester handles errors thrown in the BeforeEach/BeforeAll-block. But maybe you can just add a `throw` in the code and see how Pester handles it? If Pester catches the error correctly (outputs a correct error to the contributor) then I'm okay with it :smile: 

Thoughts?
</blockquote></details>

in the parts where I test for exceptions, that part is in an execution block within an IT block. not all Contexts need to be checked 
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 258 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-ML2fLNN0BIL3p4dR99S:-ML2kjdXEcQILs1QA516:b-5kd9p4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Unit/DSC_SqlRole.Tests.ps1#L258)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> -Be $null
> ```

Can be `-BeNullOrEmpty` instead?
</blockquote></details>

Did i really mis two? fixed


<!-- Sent from Reviewable.io -->

2020-11-01 12:28 UTC, Fiander reviewed
yes, i did yesterday and now again for the -Be $null

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-:-ML2lhMF6P1dtcrlBVo5:b-fonz6y)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @Fiander and @johlju)



<!-- Sent from Reviewable.io -->

2020-11-01 12:44 UTC, Fiander reviewed
i think i saved it in my wrong repo. now should be good>?

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-:-ML2mYdt5rr1Jz8Q1GAb:bkv6doj)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @Fiander and @johlju)



<!-- Sent from Reviewable.io -->

2020-11-02 10:55 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623)* status: 1 of 7 files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 152 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKz8FVa8fk4VINKvlY3:-ML7TybBDlhbxAxRVxF8:b61ywbn) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/235c064ea1ca5b7023f9e96d64642a4b06ae853a/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L152)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Thanks for your view on it. I agree with your reasoning. I wonder if we should add a `.NOTES` section in the comment-based help for `Get-TargetResource` and add your reasoning above. So that another contributor does not add them back (and a reminder for maintainers if one would ever). :thinking: 
</blockquote></details>

wouldnt this reasoning be for all resources? Most of them already follow it, but SqlScript for example does not. 
Ive added a .Notes section 
___
*[tests/Integration/DSC_SqlRole.Integration.Tests.ps1, line 103 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzDzke8-V6sF8E_FFk:-ML7XcSD6S3ta-Ikz-NV:bf7xd9r) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Integration/DSC_SqlRole.Integration.Tests.ps1#L103)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This line `& $configurationName @configurationParameters` is actually the "Should _compile_" of the It-block and is a test to verify the schema against a configuration. So I think that part is not setup code in this case. I agree the other stuff can go in a BeforeAll-block.
</blockquote></details>

After i've reed it for the fourth time I finally got what you mean. changed it.
___
*[tests/Unit/DSC_SqlRole.Tests.ps1, line 267 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKzF_1W1eLG2ipQs4sH:-ML7Tn2sEJbgdutW9NPn:b2nhksp) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/dc92c33ec41c7dfd9a3c84144ce554fceb9ab43a/tests/Unit/DSC_SqlRole.Tests.ps1#L267)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

`Assert-MockCalled` basically just have to be renamed to `Should -Invoke` for Pester 5. Otherwise the behavior is the same as far as I know (no breaking changes in the parameters).

Let se how this plays out depending on the previous comment. Resolving this comment for now.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2020-11-05 11:40 UTC, Fiander commented
pfiew... build failed on SqlLogin ( illegal registry thingy ) not on my code.

2020-11-21 10:15 UTC, johlju reviewed
> Reviewed 1 of 5 files at r6, 1 of 3 files at r8, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, line 152 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1623#-MKz8FVa8fk4VINKvlY3:-MMeEyXo69W900_JX4jU:b-olnpoc) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/235c064ea1ca5b7023f9e96d64642a4b06ae853a/source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1#L152)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

wouldnt this reasoning be for all resources? Most of them already follow it, but SqlScript for example does not. 
Ive added a .Notes section 
</blockquote></details>

Yes the reasoning should be for all resources. Though, it can be hard for me as a maintainer to remember to enforce this when PR's are far apart. :slightly_smiling_face:  Thanks for adding the notes section, this will help in future I think.


<!-- Sent from Reviewable.io -->

2020-11-21 10:15 UTC, johlju commented
Closing this and will continue the review in the other PR.

2020-11-21 10:15 UTC, closed without merging