SqlTraceFlag: New resource
dsccommunity/SqlServerDsc pull request #1640
Opened 2020-11-26 17:56 UTC by Fiander

#### Pull Request (PR) description
New Resource SqlTraceFlag.

#### This Pull Request (PR) fixes the following issues

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [x] Localization strings updated.
- [x] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2020-11-27 07:52 UTC, Fiander commented
Small question.
for the big build i had to change in the schema.mof:
    [Write...] Uint32[] TraceFlags;
into
    [Write...] Uint32 TraceFlags[];

Why did it build correctly at home?

2020-11-27 07:59 UTC, johlju commented
Did you run the HQRM test at home? One test it does is to parse the schema mof's. 

```
.\build.ps1 -Tasks hqrmtest
```

It is a separate test because it takes a while to run and does not work cross-platform.

2020-11-27 08:22 UTC, Fiander commented
That is a test i can not run. ALL resource get this message:
Multiple versions of the module 'SqlServerDsc' were found. You can run 'Get-Module -ListAvailable -FullyQualifiedName SqlServerDsc' to see available versions on the system
, and then use the fully qualified name '@{ModuleName="SqlServerDsc"; RequiredVersion="Version"}'.

so i think i need to remove the normal module, or move all develop work ( of halve of it ) into a sepperate VM. 

Will look into that. Thank you for the suggestion about that test.

2020-11-27 08:35 UTC, johlju commented
Yes, that might be a problem. I don't have any modules I develop in any PSModulePath because of that.

2020-11-27 15:11 UTC, johlju requested changes
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 2 of 10 files reviewed, 12 unresolved discussions (waiting on @Fiander)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9FZUI87TaGKBAnrpW:-MN9FZUI87TaGKBAnrpX:b99qokd) (no related file):*
I sent in a PR https://github.com/Fiander/SqlServerDsc/pull/1 for style fixes instead of comment on all of them. :slightly_smiling_face: 

---
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 68 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN979Ht0IDjGtsUgSpn:-MN979Ht0IDjGtsUgSpo:bsbxdco) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L68)):*
> ```
> return @{
> ```

This should return all properties in the schema.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 164 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN97gAh26nZMZK3SgS5:-MN97gAh26nZMZK3SgS6:b-9fswqe) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L164)):*
> ```
> $TraceFlags
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlags')` when checking if the parameter was set as part of the configuration and should be enforced? We should be able to pass `@()` to remove all trace flags.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 173 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN98Tit1cZredvFpt6u:-MN98Tit1cZredvFpt6v:buatzbr) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L173)):*
> ```
> $TraceFlagsToInclude
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlagsToInclude')` when checking if the parameter was set as part of the configuration and should be enforced?
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 184 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN98WOD7FAgpf8wC0dp:-MN98WOD7FAgpf8wC0dq:b-4l2vmx) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L184)):*
> ```
> $TraceFlagsToExclude
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlagsToExclude')` when checking if the parameter was set as part of the configuration and should be enforced?
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 353 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9AAf99RS5NLtQ_clL:-MN9AAf99RS5NLtQ_clM:b-7df1u3) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L353)):*
> ```
> if ($TraceFlags)
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlags')` when checking if the parameter was set as part of the configuration and should be enforced?
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 355 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9AJ4T3jTKys6mBPxr:-MN9AJ4T3jTKys6mBPxs:bxoj9pg) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L355)):*
> ```
> Compare-Object -ReferenceObject $getTargetResourceResult.ActualTraceFlags -DifferenceObject $TraceFlags
> ```

Can we move this out of the evaluation and set it to a variable that is used in evaluation instead, to make the code a bit more readable.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 367 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9ADG58kMBdX_iWcXD:-MN9ADG6C5eCIeOKD5jF:b-cd68mx) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L367)):*
> ```
> if ($TraceFlagsToInclude)
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlagsToInclude')` when checking if the parameter was set as part of the configuration and should be enforced?
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 383 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9AFyC98PP5Zf9q2pT:-MN9AFyC98PP5Zf9q2pU:b-4l2vmx) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L383)):*
> ```
> $TraceFlagsToExclude
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlagsToExclude')` when checking if the parameter was set as part of the configuration and should be enforced?
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 410 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9BwV57oUglqZk5G-i:-MN9BwV57oUglqZk5G-j:b-omsjl4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L410)):*
> ```
> Export-ModuleMember -Function *-TargetResource
> ```

We could actually remove this as it is not necessary. Old inheritance. 
The resource SqlProtocol and SqlProtocolTcpIp does not have this. Haven't gotten around to remove it from all other resources.
If you want to keep it, move it to the end of the file. :slightly_smiling_face: 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 416 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9BYeW9RGyRXu2Ua9P:-MN9BYeW9RGyRXu2Ua9Q:bsw0oar) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L416)):*
> ```
> Get-SqlServiceName
> ```

Non-blocking (Informational): This is similar to this, but not quite, seems this should be made into a common function in the future. https://github.com/dsccommunity/SqlServerDsc/blob/a235aa317f6c93106a5d073e06327ed003b921d6/source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.psm1#L514  
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 420 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9Alt9ComtQP1gcMQ0:-MN9Alt9ComtQP1gcMQ1:b-ui9ofa) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L420)):*
> ```
> Position = 1
> ```

We can remove this as we always should use named parameters.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 422 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9AjDs2uaI--CAoVJA:-MN9AjDs2uaI--CAoVJB:b50wx7o) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L422)):*
> ```
> $InstanceName
> ```

Can we add this to the comment-based help.


<!-- Sent from Reviewable.io -->

2020-11-27 15:17 UTC, johlju requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 3 of 10 files reviewed, 13 unresolved discussions (waiting on @Fiander)

___
*[tests/Unit/Stubs/SMO.cs, line 975 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9Gl5LETCL9J8v8Qbb:-MN9Gl5LETCL9J8v8Qbc:b1ozvns) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/tests/Unit/Stubs/SMO.cs#L975)):*
> ```
> .ManagedServiceType
> ```

Change to `.ManagedComputer`


<!-- Sent from Reviewable.io -->

2020-11-27 15:50 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 1 of 10 files reviewed, 13 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 68 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN979Ht0IDjGtsUgSpn:-MN9Hn6I403rx_a636HZ:bz3w4g1) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L68)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> return @{
> ```

This should return all properties in the schema.
</blockquote></details>

Done, But seems to me like a wast of resources. ( not your fault!)
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 164 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN97gAh26nZMZK3SgS5:-MN9Izgy9KSK_KJnN_gf:bcdy14w) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L164)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $TraceFlags
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlags')` when checking if the parameter was set as part of the configuration and should be enforced? We should be able to pass `@()` to remove all trace flags.
</blockquote></details>

Done, but isnt removing done by setting the resource to Absent?
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 173 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN98Tit1cZredvFpt6u:-MN9JKnO933m-5RYDn_Q:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L173)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $TraceFlagsToInclude
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlagsToInclude')` when checking if the parameter was set as part of the configuration and should be enforced?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 184 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN98WOD7FAgpf8wC0dp:-MN9JLZaDOI2XwYToTZf:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L184)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $TraceFlagsToExclude
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlagsToExclude')` when checking if the parameter was set as part of the configuration and should be enforced?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 353 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9AAf99RS5NLtQ_clL:-MN9JlnlESRFraIvJrZm:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L353)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($TraceFlags)
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlags')` when checking if the parameter was set as part of the configuration and should be enforced?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 355 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9AJ4T3jTKys6mBPxr:-MN9M1HJ9p5bzfWzAEbJ:bs7wumx) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L355)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Compare-Object -ReferenceObject $getTargetResourceResult.ActualTraceFlags -DifferenceObject $TraceFlags
> ```

Can we move this out of the evaluation and set it to a variable that is used in evaluation instead, to make the code a bit more readable.
</blockquote></details>

Done. 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 367 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9ADG58kMBdX_iWcXD:-MN9M5C-Eku2G09TpYE5:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L367)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($TraceFlagsToInclude)
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlagsToInclude')` when checking if the parameter was set as part of the configuration and should be enforced?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 383 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9AFyC98PP5Zf9q2pT:-MN9M6169GJ1eMKMvzHj:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L383)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $TraceFlagsToExclude
> ```

Can we use `$PSBoundParameters.ContainsKey('TraceFlagsToExclude')` when checking if the parameter was set as part of the configuration and should be enforced?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 410 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9BwV57oUglqZk5G-i:-MN9M9iG-ADm58hjI_3H:b-ypbmdy) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L410)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Export-ModuleMember -Function *-TargetResource
> ```

We could actually remove this as it is not necessary. Old inheritance. 
The resource SqlProtocol and SqlProtocolTcpIp does not have this. Haven't gotten around to remove it from all other resources.
If you want to keep it, move it to the end of the file. :slightly_smiling_face: 
</blockquote></details>

Done. removed it.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 416 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9BYeW9RGyRXu2Ua9P:-MN9MGrK2UzKD2-no7zm:bsanhjy) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L416)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Get-SqlServiceName
> ```

Non-blocking (Informational): This is similar to this, but not quite, seems this should be made into a common function in the future. https://github.com/dsccommunity/SqlServerDsc/blob/a235aa317f6c93106a5d073e06327ed003b921d6/source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.psm1#L514  
</blockquote></details>

i agree.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 420 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9Alt9ComtQP1gcMQ0:-MN9MJeS4bwZZkUk1qaY:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L420)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Position = 1
> ```

We can remove this as we always should use named parameters.
</blockquote></details>

Done.
___
*[source/DSCReso [...]

2020-11-27 15:52 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 1 of 10 files reviewed, 13 unresolved discussions (waiting on @Fiander and @johlju)

___
*[tests/Unit/Stubs/SMO.cs, line 975 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN9Gl5LETCL9J8v8Qbb:-MN9Ovx69MqvLtWEIS-Y:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/tests/Unit/Stubs/SMO.cs#L975)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Oops.... stupid one..... Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-27 17:48 UTC, johlju commented
If you can look at the PR https://github.com/Fiander/SqlServerDsc/pull/1 in your fork and merge it. 🙂

2020-11-27 18:09 UTC, Fiander commented
thank you, i didnot see that one

2020-11-27 19:26 UTC, johlju requested changes
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 164 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN97gAh26nZMZK3SgS5:-MNA9Ky4C-Llz46PWFY-:bl516t) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L164)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Done, but isnt removing done by setting the resource to Absent?
</blockquote></details>

Actually, in this resource there is no point of having the Ensure property since it does no create or remove an object. It just changes a setting, so setting the `TraceFlags` to `@()` should be the right way to enforce that there should be no trace flags. 


<!-- Sent from Reviewable.io -->

2020-11-27 20:28 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 164 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN97gAh26nZMZK3SgS5:-MNAM7l92IFx4t7l0plB:b-t1pstw) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L164)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Actually, in this resource there is no point of having the Ensure property since it does no create or remove an object. It just changes a setting, so setting the `TraceFlags` to `@()` should be the right way to enforce that there should be no trace flags. 
</blockquote></details>

oke. But then we should also remove the ensure parameter.


<!-- Sent from Reviewable.io -->

2020-11-27 20:52 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 164 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN97gAh26nZMZK3SgS5:-MNATUKrBXzZ-v2qiFOO:bnp5dgp) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L164)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

oke. But then we should also remove the ensure parameter.
</blockquote></details>

Yes, sorry I meant that. The ensure property in the scheme and the parameter in the code. :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2020-11-29 07:52 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 1 of 10 files reviewed, 16 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 36 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHuXj_9ulGAm4lDzp5:-MNHuXj_9ulGAm4lDzp6:b-3z8gyo) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L36)):*
> ```
> $Name
> ```

This should be `$InstaneName` and make sure it is written out in the localized string, so the user can see what instance it getting from.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 45 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHy3a83u0gfVLVDdg-:-MNHy3a83u0gfVLVDdg0:b-71xysh) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L45)):*
> ```
> $wmiService
> ```

Maybe we could call this `$databaseEngineService` instead?
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 59 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHtXZt7kHSIJxqyzef:-MNHtXZt7kHSIJxqyzeg:b-31ebir) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L59)):*
> ```
> New-InvalidOperationException -Message $errorMessage
> ```

We should not throw here in Get-TargetResource. It is better we write this message as a verbose message and return an empty array for TraceFlags, This is so that it is possible to run Get-DscConfiguration or Test-TargetResource when no SQL Server has yet been installed.

This should probably be moved, see comment in Set.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 65 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHuApPEBIKqM6FqHmw:-MNHuApPEBIKqM6FqHmx:b-kkf2mm) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L65)):*
> ```
> New-InvalidOperationException -Message $errorMessage
> ```

Same as previous comment.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 68 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHvne6-ieJQReKPz7_:-MNHvne6-ieJQReKPz7a:b-mmss24) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L68)):*
> ```
> return @{
> ```

This is missing the property `RestartInstance`.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 71 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHveCU5ZN4OQbZS4YY:-MNHveCU5ZN4OQbZS4YZ:b-h5h8e2) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L71)):*
> ```
> ActualTraceFlags    = $actualTraceFlags
> ```

This should be removed and `$actualTraceFlags` should be set to `TraceFlags`.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 129 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHvygVEqssEx0yHWvE:-MNHvygVEqssEx0yHWvF:b-fio0oe) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L129)):*
> ```
> $RestartInstance
> ```

Missing this one in comment-based help.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 133 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHumYL7WLvby1bS1_c:-MNHumYL7WLvby1bS1_d:b-jqgk0j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L133)):*
> ```
> $Name
> ```

This should be `$InstaneName` and make sure it is written out in the localized string, so the user can see what instance it setting values to.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 133 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHunzL6sqi45RGeVIG:-MNHunzL6sqi45RGeVIH:b-ph9m9k) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L133)):*
> ```
> $RetryCount, ($RetryIntervalSec * $RetryCount)
> ```

These should be removed?
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 203 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHwlvq1kKwOnAi59pA:-MNHwlvq1kKwOnAi59pB:bvuofvt) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L203)):*
> ```
> if ($sqlManagement)
> ```

We should throw if this evaluation is false.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 205 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHxjWXD-7R7WKZ6XVL:-MNHxjWXD-7R7WKZ6XVM:b-71xysh) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L205)):*
> ```
> $wmiService
> ```

Maybe we could call this `$databaseEngineService` instead?
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 208 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHx8226bRl3pgWzZpr:-MNHx8226bRl3pgWzZps:bcfryyo) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L208)):*
> ```
> if ($wmiService)
> ```

We should throw if this evaluation is false.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 241 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHyYAX9gGE6LgUxFcW:-MNHyYAX9gGE6LgUxFcX:b-a4mk5q) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L241)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
>                     # Get the current status of the sql agent. After restart of the instance, the status of the agent should be the same.
>                     $agentServiceStatus = (
>                         $sqlManagement.Services |
>                             Where-Object -FilterScript { $PSItem.Name -eq $serviceNames.SQLAgentName }
>                     ).ServiceState
>                     $wmiService.Stop()
>                     Start-Sleep -Seconds 10
>                     $wmiService.Start()
>                     if ($agentServiceStatus -ne 'Stopped')
>                     {
>                         (
>                             $sqlManagement.Services |
>                                 Where-Object -FilterScript { $PSItem.Name -eq $serviceNames.SQLAgentName }
>                         ).Start()
>                     }
> ```
</details>


Can we use `Restart-SqlService´ instead?
https://github.com/dsccommunity/SqlServerDsc/blob/ce786852a984ea364e1213d936f647bc5ebe4a30/source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1#L966
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 316 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHw6Ni5X_7bdj8BJoI:-MNHw6Ni5X_7bdj8BJoJ:b-fio0oe) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L316)):*
> ```
> $RestartInstance
> ```

Missing this one in comment-based help.
 [...]

2020-11-29 08:57 UTC, johlju requested changes
> Reviewed 1 of 10 files at r1, 1 of 2 files at r2, 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 8 of 10 files reviewed, 25 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 348 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNI8J-J8tQcC3QaKCMN:-MNI8J-J8tQcC3QaKCMO:b-9klcht) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L348)):*
> ```
> ActualTraceFlags
> ```

This should be changed to `TraceFlags`. See comment in Get-function. Throughout the Test-function. 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 355 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNI8zCPB5b5mdvMd3kZ:-MNI8zCPB5b5mdvMd3k_:b535gdt) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L355)):*
> ```
> #C
> ```

Add a space after the #
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 357 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNI92dx-SdWYAoksSb7:-MNI92dx-SdWYAoksSb8:b-1yn93p) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L357)):*
> ```
> if ( $null
> ```

We can remove the extra space after the parenthesis. 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof, line 6 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNI9Hee-j-SLbCzNQDb:-MNI9Hee-j-SLbCzNQDc:bs1ja5u) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof#L6)):*
> ```
> ...startup options should have"
> ```

Can we add the following to the string so that it is clear "This parameter will replace all the current trace flags with the specified trace flags."

Please add to comment-based help for the parameter as well.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof, line 7 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNI8jjO0MuqlfCuB8r6:-MNI8ird90_5aF8IIMoi:b-c7rmow) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof#L7)):*
> ```
> An array of trace flags that startup options should have
> ```

Add full stop (`.`) to this description strings. Throughout.
___
*[source/DSCResources/DSC_SqlTraceFlag/README.md, line 3 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNIA5nSEbJzbVVxPQYT:-MNIA5nT4vbO8F1YKPwi:b-gpi24g) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/README.md#L3)):*
> ```
> ...will set TraceFlags on...
> ```

Maybe "...will remove or set one or more trace flags on...
___
*[source/DSCResources/DSC_SqlTraceFlag/README.md, line 12 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNIARE60hR-FiXgYhpw:-MNIARE60hR-FiXgYhpx:b-bmf52j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/README.md#L12)):*
> ```
> Target machine
> ```

Do you mean the account that the resource is run as.not the machine?
___
*[source/Examples/Resources/SqlTraceFlag/2-SetTraceFlagsIncludeExclude.ps1, line 3 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNIB28R0k63me3ZQLkr:-MNIB28R0k63me3ZQLks:bhx6gh1) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/Examples/Resources/SqlTraceFlag/2-SetTraceFlagsIncludeExclude.ps1#L3)):*
> ```
>         This example shows how to set TraceFlags where all existing
>         TraceFlags are overwriten by these
> ```

This description should be rephrased for this example. (copied from previous example)
___
*[source/Examples/Resources/SqlTraceFlag/3-RemoveTraceFlags.ps1, line 3 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNIBJ5S32KvAOAYGfMp:-MNIBJ5S32KvAOAYGfMq:bhx6gh1) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/Examples/Resources/SqlTraceFlag/3-RemoveTraceFlags.ps1#L3)):*
> ```
>         This example shows how to set TraceFlags where all existing
>         TraceFlags are overwriten by these
> ```

This description should be rephrased for this example. (copied from previous example)
___
*[tests/Unit/DSC_SqlTraceFlag.Tests.ps1, line 113 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNIBwz08PxyCfttl2Vm:-MNIBwz08PxyCfttl2Vn:b-qtw0e4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/tests/Unit/DSC_SqlTraceFlag.Tests.ps1#L113)):*
> ```
> #region Function mocks
> ```

Can we please move parameter code and mocked code to the actual describe-/context-block where they are needed. If that means duplicating code then that we should do that. It is much easier for new contributors if describe-/context -blocks are self-sustaining when they try to follow the test-code.

_I'm trying to slowly rewrite the unit test code in this way. Because the test code in existing test is now often to "intelligent" making it difficulty to read/understand for new contributors._


<!-- Sent from Reviewable.io -->

2020-11-29 09:26 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 8 of 10 files reviewed, 25 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 164 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MN97gAh26nZMZK3SgS5:-MNIG6NkCMm7iVprhW99:b-g8d71f) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/c5346a2872b729243553e540a259b80bf3687487/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L164)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Yes, sorry I meant that. The ensure property in the scheme and the parameter in the code. :slightly_smiling_face: 
</blockquote></details>

Done, and also all the testing
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 36 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHuXj_9ulGAm4lDzp5:-MNIAQZ1CwwtDMCrHAXw:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L36)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $Name
> ```

This should be `$InstaneName` and make sure it is written out in the localized string, so the user can see what instance it getting from.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 45 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHy3a83u0gfVLVDdg-:-MNIAShiCuk51S-K-rLy:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L45)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $wmiService
> ```

Maybe we could call this `$databaseEngineService` instead?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 59 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHtXZt7kHSIJxqyzef:-MNIB4YTCfXih3denNlL:b-grc040) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L59)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> New-InvalidOperationException -Message $errorMessage
> ```

We should not throw here in Get-TargetResource. It is better we write this message as a verbose message and return an empty array for TraceFlags, This is so that it is possible to run Get-DscConfiguration or Test-TargetResource when no SQL Server has yet been installed.

This should probably be moved, see comment in Set.
</blockquote></details>

Most resources throw exeptions. they all need "DependsOn" settings. 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 68 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHvne6-ieJQReKPz7_:-MNIBNF3Bo0LRvv9ftrU:b-aft74y) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L68)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> return @{
> ```

This is missing the property `RestartInstance`.
</blockquote></details>

Oops, Done
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 71 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHveCU5ZN4OQbZS4YY:-MNIBRqr7n9B4dFSXEqv:bp090cr) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L71)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ActualTraceFlags    = $actualTraceFlags
> ```

This should be removed and `$actualTraceFlags` should be set to `TraceFlags`.
</blockquote></details>

That would make the rest of the code really confusing. I have added it as a Read in the resource schema, misusing a parameter for something like this is confusing.
 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 129 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHvygVEqssEx0yHWvE:-MNIG-byDdrxa5RHeX-V:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L129)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $RestartInstance
> ```

Missing this one in comment-based help.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 133 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHumYL7WLvby1bS1_c:-MNIG0aA9PQL9_aIQ7Xz:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L133)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $Name
> ```

This should be `$InstaneName` and make sure it is written out in the localized string, so the user can see what instance it setting values to.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 133 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHunzL6sqi45RGeVIG:-MNIG14vEuLavrVkrdav:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L133)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $RetryCount, ($RetryIntervalSec * $RetryCount)
> ```

These should be removed?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 203 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHwlvq1kKwOnAi59pA:-MNIGHJq1sC4DJx0_nXw:b-x3k3do) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L203)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($sqlManagement)
> ```

We should throw if this evaluation is false.
</blockquote></details>

That is done in Get-TargetResource. Doing it here leads to unreachable ( untestable ) code.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 205 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHxjWXD-7R7WKZ6XVL:-MNIGYP1BFM5Wi1z3tVV:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L205)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $wmiService
> ```

Maybe we could call this `$databaseEngineService` instead?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 208 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHx8226bRl3pgWzZpr:-MNIGc32-3SzG0V_5aQP:b-vmq53u) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L208)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($wmiService)
> ```

We should throw if this evaluation is false.
</blockquote></details>

That is done in Get-TargetResource. Doing it here leads to unreachable ( untestable ) code.
___
*[source/DSCResourc [...]

2020-11-29 09:27 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 3 of 10 files reviewed, 25 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/README.md, line 3 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNIA5nSEbJzbVVxPQYT:-MNIJx_r5B9xbWyxTJuL:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/README.md#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ...will set TraceFlags on...
> ```

Maybe "...will remove or set one or more trace flags on...
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlTraceFlag/README.md, line 12 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNIARE60hR-FiXgYhpw:-MNIJxHC5UxiTiBRvMl0:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/README.md#L12)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Yes i did.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-29 11:29 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 3 of 10 files reviewed, 22 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 59 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHtXZt7kHSIJxqyzef:-MNIgwUA5D3v6aNSdZHk:b-9ml336) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L59)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Most resources throw exeptions. they all need "DependsOn" settings. 
</blockquote></details>

Let's leave it as-is, and let it throw here.

I think we had this discussion in the Community Slack channel, then we said Get should not throw. But I can see both points. Using DependsOn might be the case when running them in a compiled configuration, but running Get with `Invoke-DscResource` would throw an error instead of returning the actual state. The actual state would be in this case an empty array when the SQL Server is not installed an outputting a verbose message saying the state could no be evaluated. But if this should return the actual state, if it can't due to missing instance, it should throw. So let it throw here.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 71 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHveCU5ZN4OQbZS4YY:-MNIfZHY5OAmg70d3GpY:bs0ipby) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L71)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

That would make the rest of the code really confusing. I have added it as a Read in the resource schema, misusing a parameter for something like this is confusing.
 
</blockquote></details>

I can't see tis getting confusing. Get should return the current state in TraceFlags. Just like SqlRole returning the actual members in the Members property, :thinking:  I think we should only use read-only properties when there are more metadata around the actual state that needs to be "explained", for example what state the the SQL Service is in. 


<!-- Sent from Reviewable.io -->

2020-11-29 12:26 UTC, Fiander commented
> I can't see tis getting confusing. Get should return the current state in TraceFlags. Just like SqlRole returning the actual members in the Members property, 🤔 I think we should only use read-only properties when there are more metadata around the actual state that needs to be "explained", for example what state the the SQL Service is in.

One of the arguments in SqlRole you used was: 
>Instead of returning $null I would rather that we keep this so it returns the actual values that was provided in the configuration. When you run Get-DscConfiguration or similar it is possible to compare the actual members with the desired members in those two properties. Although I can see it will not return the desired members if only the Members property was used... 🤔 But keeping these avoids a breaking change. What are your thoughts?

by using a readonly property for the actual values, you could get exactly that: the possibility to compare the actual members with the desired members inline in a single pipeline. So actually i should add the real traceflag, in- and excludeTraceflags in get-target resource as real parameters.

And it is SqlRole that i found very confusing to read just because $Members can be the Parameter or the actual value.
i wish i knew about readonly parameters back then. Than i would not have removed the parameters Members, MembersToInclude and MembersToExclude, and just added an readonly MembersInRole. That would have made the code much more readable.
`Compare-Object -ReferenceObject $result.Members -DifferenceObject $Members`
vs
`Compare-Object -ReferenceObject $result.MembersInRole -DifferenceObject $Members`
the last one for me is just more readable. 
bye doing so, we could maybe remove the Breaking change on SqlRole?

2020-11-29 12:32 UTC, Fiander commented
> tests/Unit/DSC_SqlTraceFlag.Tests.ps1, line 113 at r4 (raw file):
>
>#region Function mocks
>Can we please move parameter code and mocked code to the actual describe-/context-block where they are needed. If that >means duplicating code then that we should do that. It is much easier for new contributors if describe-/context -blocks are self->sustaining when they try to follow the test-code.

>I'm trying to slowly rewrite the unit test code in this way. Because the test code in existing test is now often to "intelligent" >making it difficulty to read/understand for new contributors.

just to make sure: do you meen copy/move row 111..179 to the BeforeAll in the describe of the Get-Set-Test sections?

2020-11-30 06:54 UTC, johlju commented
I appreciate the discussion. 🙂 

In regards to read-only properties. I think it is important to differentiate what is a parameter for in-data and what is outputted from the resource. I think it is very well known that the current state it reported back in the properties described in the schema, that is why I went along with adding `$null` for the `*Exclude` and `*Include` properties since they does not have a current state, they just have in-data. 
In all resources thorughout the DSC Resource Kit the current state is always returned in the schema properties. Read-only properties is only added to get more metadata as sid before. If we would have and `ActualTraceFlags` property then we moving towards a new pattern where every property in the schema should also have a Read-Only `Actual*` property and that is not the well-known pattern and would differentiate from all other resource modules. 
Since it is well-known that the current state is returned in the schema properties it would not be intuitive to suddenly have `Actual*` properties.

> Just to make sure: do you mean copy/move row 111..179 to the BeforeAll in the describe of the Get-Set-Test sections?
> p.s. When are we going to pester 5? Assert-MockCalled >> Should -Invoke

Move only the code that is necessary for each individual Describe/Context-block. I'm looking for "self-sustaining tests" so a contributor does not need to look through entire test code file to understand a test and to add a simple change. Do the necessary mocking as close to the actual It-block(s) as possible. 🙂 

We can't move to Pester 5 until all the Pester tests has been rewritten to support Pester 5 and the pipeline support is as well (make sure Pester 5 i started so it genereates the code coverage file). Also so far Pester 5 does not support output code coverage (missed lines) which is a great tool to see that you covered all code paths - not blocking though.
I have a PR https://github.com/dsccommunity/SqlServerDsc/pull/1550 open that changed the test code for SqlServerDsc.Common, but it broke in a new release of Pester 5 (5.1?) so now the tests does no run correctly in that PR and I haven't had time to fix it. But that is just one test, fixing all tests is a massive job, but happy for any PR's moving in that direction. 🙂

2020-11-30 08:37 UTC, Fiander commented
> I appreciate the discussion. 🙂
> 
> In regards to read-only properties. I think it is important to differentiate what is a parameter for in-data and what is outputted from the resource. I think it is very well known that the current state it reported back in the properties described in the schema, that is why I went along with adding `$null` for the `*Exclude` and `*Include` properties since they does not have a current state, they just have in-data.
> In all resources thorughout the DSC Resource Kit the current state is always returned in the schema properties. Read-only properties is only added to get more metadata as sid before. If we would have and `ActualTraceFlags` property then we moving towards a new pattern where every property in the schema should also have a Read-Only `Actual*` property and that is not the well-known pattern and would differentiate from all other resource modules.
> Since it is well-known that the current state is returned in the schema properties it would not be intuitive to suddenly have `Actual*` properties.
>
oke, will comply, but to me this seems like an error in the pattern.

> > Just to make sure: do you mean copy/move row 111..179 to the BeforeAll in the describe of the Get-Set-Test sections?
> > p.s. When are we going to pester 5? Assert-MockCalled >> Should -Invoke
> 
> Move only the code that is necessary for each individual Describe/Context-block. I'm looking for "self-sustaining tests" so a contributor does not need to look through entire test code file to understand a test and to add a simple change. Do the necessary mocking as close to the actual It-block(s) as possible. 🙂
> 
coping code makes it more error prune. But i get what you want. Clean Tests. 
Would moving the mock code to a different file be an idea? that is what is suggested in the pester-quickstart [https://pester.dev/docs/quick-start](url) 
`BeforeAll { 
    . $PSScriptRoot/Get-Planet.ps1
}

Describe 'Get-Planet' {
    It 'Given no parameters, it lists all 8 planets' {
        $allPlanets = Get-Planet
        $allPlanets.Count | Should -Be 8
    }
}`
That way, you clean up all the test files, and one can have the mock file open next to the test file, 
a compleet test would then have two files. resource.test.ps1 and resource.mock.ps1
just a idea.

As for moving the code... where should i stop. Just move the Mocking code? or also the variables. for selfsustained, the variables are also needed. but that would really explode the code.

> We can't move to Pester 5 until all the Pester tests has been rewritten to support Pester 5 and the pipeline support is as well (make sure Pester 5 i started so it generates the code coverage file). Also so far Pester 5 does not support output code coverage (missed lines) which is a great tool to see that you covered all code paths - not blocking though.
> I have a PR #1550 open that changed the test code for SqlServerDsc.Common, but it broke in a new release of Pester 5 (5.1?) so now the tests does no run correctly in that PR and I haven't had time to fix it. But that is just one test, fixing all tests is a massive job, but happy for any PR's moving in that direction. 🙂

i was just wondering.

2020-12-03 06:24 UTC, PlagueHO commented
I understand the reasoning here, but we should probably base the pattern around what the PowerShell team have done with the `Group` resource in `PSDesiredStateConfiguration` and `PSDscResources` - as these are the "in-box" resources (and replacement for the "in-box" resources). They are the most used resources across DSC, so that pattern is most understood/expected.

It appears that this resource is implementing the same pattern, where the actual value is returned in the `Members` property and the `MembersToInclude` and `MembersToExclude` are returned as $null.

Not saying that is the perfect pattern by any means :grin: just that it is probably most understood because of it's wide use.

2020-12-04 18:00 UTC, johlju commented
> Would moving the mock code to a different file be an idea? 

I rather not because I think that would make it harder for newcomers to understand that dependent code is in another file.
Our goal should be having tests that are easily to read and easy to follow. We should avoid having contributors that are new to Pester to need to jump up and down in the file, that includes not needing coding in two files.

For integration tests I think the configuration is in another file to look more like a real configuration file, and it is meant that the config file could get input from a third file (real world properties). But I want these to be simple as well so making these into one file too would make them much easier to read as well, but we don't have to go there now with the integ tests. 🙂

2020-12-04 18:08 UTC, johlju requested changes
> Reviewed 3 of 6 files at r5, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @Fiander and @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 320 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHv80C1l2TeRu7ulbu:-MNivYHOCwNk78frIxan:b-j1k2kv) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L320)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you missed this one? :slightly_smiling_face: 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 45 at r6](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNiucEXBQCWx01iYcrO:-MNiucEY6HtbIAczQA2G:b-xhbvhx) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/ca656552e2f6bf860b3477d4d5ab9edbbf457f31/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L45)):*
> ```
> e  = $
> ```

We can remove the extra space before the equal sign.
___
*[tests/Unit/Stubs/New File.ps1, line 0 at r6](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNiw8kC0lrLJEb5-NNQ:-MNiw8kC0lrLJEb5-NNR:bgzqpbq) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/ce786852a984ea364e1213d936f647bc5ebe4a30/tests/Unit/Stubs/New File.ps1#L0)):*
Seems we got an extra empty file here.


<!-- Sent from Reviewable.io -->

2020-12-04 18:10 UTC, johlju commented
It was a bit busy at the day job this week, but resolved all the comments that were done. Awesome work on this, soon done! 😃

2020-12-04 19:04 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 320 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNHv80C1l2TeRu7ulbu:-MNiyvCq2dVeRkcCAqNh:bii7t4m) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L320)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think you missed this one? :slightly_smiling_face: 
</blockquote></details>

yes i did...... 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 45 at r6](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNiucEXBQCWx01iYcrO:-MNiybtU2p4FUtGhY1eQ:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/ca656552e2f6bf860b3477d4d5ab9edbbf457f31/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L45)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> e  = $
> ```

We can remove the extra space before the equal sign.
</blockquote></details>

Done.
___
*[tests/Unit/DSC_SqlTraceFlag.Tests.ps1, line 113 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNIBwz08PxyCfttl2Vm:-MNj4kFZ-ME18q6hy01B:b-7rl0jd) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/tests/Unit/DSC_SqlTraceFlag.Tests.ps1#L113)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

Will do, but that wil not be now. i have a familimeeting to attend to. Back in a few hours.
</blockquote></details>

done.
___
*[tests/Unit/Stubs/New File.ps1, line  at r6](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNiw8kC0lrLJEb5-NNQ:-MNj4fNM0BSjcDao1G3V:b-6tucmt) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/ce786852a984ea364e1213d936f647bc5ebe4a30/tests/Unit/Stubs/New File.ps1#L)):*
> Get-function.
Where did that one come from? removed it


<!-- Sent from Reviewable.io -->

2020-12-04 19:17 UTC, Fiander commented
> It was a bit busy at the day job this week, but resolved all the comments that were done. Awesome work on this, soon done! 😃

No problem, i finally have my branches in working order :-)

when do you want to go to version 15?
because i am also working on a fix for #1492
https://github.com/Fiander/SqlServerDsc/tree/SqlAgDatabase.

now finishing up on the tests i hope. I think i fixed all i did not good in 1640, so that one should be easieer for you to review

sry about this one, but i want to improve, and that means make mistakes/misinterpretations.

2020-12-05 10:02 UTC, johlju commented
> when do you want to go to version 15?

We in the community decide. I usually try to get as many breaking changes into a breaking change release as possible, but I haven't gotten the time to help out creating PR's at the moment. So if there are no more breaking changes in the works then we could release anytime. 🙂 

> sry about this one, but i want to improve, and that means make mistakes/misinterpretations.

No need for sorry! The community, and especially I, really appreciate the time you put in to these PRs! 🙇‍♂️ The discussions we have is natural and a good thing, and I appreciate to get new perspectives from you! 🙂 
You do quality work! Do not feel like you have make any mistakes - it is natural that there are discussions/comments during the review process. 😃 

I review the last bits now.

2020-12-05 10:31 UTC, johlju requested changes
> Reviewed 1 of 6 files at r5, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: all files reviewed, 3 unresolved discussions (waiting on @Fiander)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 244 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmOrcw-IXP1B37YWRa:-MNmOrcw-IXP1B37YWRb:bjnubpn) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L244)):*
> ```
> $RestartTimeout = 10
> ```

Could you make an issue for this so we can fix this in another PR. I think we should make this as parameter in the future because 10 seconds can be slow on some machines. A parameter similar to this:
 https://github.com/dsccommunity/SqlServerDsc/blob/ce786852a984ea364e1213d936f647bc5ebe4a30/source/DSCResources/DSC_SqlConfiguration/DSC_SqlConfiguration.schema.mof#L9
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 354 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmQ6ED9OlRPdekxHuy:-MNmQ6EE7mbJ1VwgRUUz:bix3u2) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L354)):*
> ```
> $ServerRoleName
> ```

This one should be removed I think, because the localized string has no placeholder for any variables.

But we could also change the localized string to output the actual and desired trace flags, maybe `The trace flags does not match. Expected '{0}', but was '{1}'.`. Then join the array to a string to pass to the localized string, e.g`$TraceFlags -join ','`

I let you decide. :slightly_smiling_face: 
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof, line 9 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmPUrFD9-n4XdC-x_g:-MNmPUrFD9-n4XdC-x_h:bj6p8of) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof#L9)):*
> ```
> RestartInstance
> ```

In other resources we have named this `RestartService`, is it worth renaming to that here to? I good with either way. I let you decide.
___
*[tests/Unit/DSC_SqlTraceFlag.Tests.ps1, line 824 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmRdf88LJO-J9LCUTY:-MNmRdf88LJO-J9LCUTZ:b-46hhbz) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/tests/Unit/DSC_SqlTraceFlag.Tests.ps1#L824)):*
> ```PowerShell
> {
>     Invoke-TestCleanup
> }
> ```

Can we make a empty line at the end in this file. I usually set the code editor to make this automatically on save (like VS Code).
Reviewable is indicating if there are no new line at the end of a file. :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2020-12-05 11:16 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 348 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNI8J-J8tQcC3QaKCMN:-MNmbGJt1JQincr9m14j:bp2436f) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/8cd697027d3619f8f8ee0ba77dd8a2b19af62f81/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L348)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ActualTraceFlags
> ```

This should be changed to `TraceFlags`. See comment in Get-function. Throughout the Test-function. 
</blockquote></details>

hmm, did these yesterday, but they were undone? done them again.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 244 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmOrcw-IXP1B37YWRa:-MNmYv9iEnIrMXPhmbXa:bcyqtqv) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L244)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $RestartTimeout = 10
> ```

Could you make an issue for this so we can fix this in another PR. I think we should make this as parameter in the future because 10 seconds can be slow on some machines. A parameter similar to this:
 https://github.com/dsccommunity/SqlServerDsc/blob/ce786852a984ea364e1213d936f647bc5ebe4a30/source/DSCResources/DSC_SqlConfiguration/DSC_SqlConfiguration.schema.mof#L9

</blockquote></details>

In that case, i would rather do that now. 
Adding this in the scheme, is not much work, and would save a breaking change in the future.
the default can then be 120 seconds or so.

changes in code would be moving that one line up as parameter ( in all functions, and examples )
tests can be speeded up by setting this one to 1 i think
when you say "YES", i will change it now, otherwise i will change the 10 seconds to 120.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 354 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmQ6ED9OlRPdekxHuy:-MNmZvVM4LVtX7RPjCTU:bswsu5u) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L354)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $ServerRoleName
> ```

This one should be removed I think, because the localized string has no placeholder for any variables.

But we could also change the localized string to output the actual and desired trace flags, maybe `The trace flags does not match. Expected '{0}', but was '{1}'.`. Then join the array to a string to pass to the localized string, e.g`$TraceFlags -join ','`

I let you decide. :slightly_smiling_face: 
</blockquote></details>

the long one it is. 
When using dsc-resources i like it when they tell me what went wrong, including the values.
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof, line 9 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmPUrFD9-n4XdC-x_g:-MNma2sO-KOFB9G6Mz6_:bndxspo) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> RestartInstance
> ```

In other resources we have named this `RestartService`, is it worth renaming to that here to? I good with either way. I let you decide.
</blockquote></details>

no problem. : my logic >> i want the instance to restart, so restartInstance. but changed it to match all others.
___
*[tests/Unit/DSC_SqlTraceFlag.Tests.ps1, line 824 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmRdf88LJO-J9LCUTY:-MNmaRGk6GTXhL-h3Kih:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/tests/Unit/DSC_SqlTraceFlag.Tests.ps1#L824)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we make a empty line at the end in this file. I usually set the code editor to make this automatically on save (like VS Code).
Reviewable is indicating if there are no new line at the end of a file. :slightly_smiling_face: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-05 11:18 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 354 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmQ6ED9OlRPdekxHuy:-MNmbljvBXX4ZAWsIFSq:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L354)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

the long one it is. 
When using dsc-resources i like it when they tell me what went wrong, including the values.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-05 11:39 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 244 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmOrcw-IXP1B37YWRa:-MNmgcRV3JHFeubDKZBQ:bb4a8aj) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L244)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

In that case, i would rather do that now. 
Adding this in the scheme, is not much work, and would save a breaking change in the future.
the default can then be 120 seconds or so.

changes in code would be moving that one line up as parameter ( in all functions, and examples )
tests can be speeded up by setting this one to 1 i think
when you say "YES", i will change it now, otherwise i will change the 10 seconds to 120.
</blockquote></details>

Yes, you are welcome to add it now. I thought I'd spare you yet another change. :wink:  But let's add it now if you are up to it.


<!-- Sent from Reviewable.io -->

2020-12-05 11:46 UTC, johlju approved these changes
This looks good to me now. Waiting for you to add the RestartTimeout parameter since it sounded you were up to it. :slightly_smiling_face: 

> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-:-MNmO7wg6UiUj4GXAB8q:b3jftxw)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-05 11:48 UTC, johlju commented
@Fiander HQRM test failed on the examples. Parameter `RestartInstance` need to be renamed there as well. 🙂

2020-12-05 17:46 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @Fiander and @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNo-h92DhkmDZYSxl06:-MNo-h92DhkmDZYSxl07:bhmekor) (no related file):*
Can you update the list of resources here as well?

https://github.com/dsccommunity/SqlServerDsc/blob/ce786852a984ea364e1213d936f647bc5ebe4a30/source/SqlServerDsc.psd1#L38

---
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 68 at r9](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNo-XgS7QpUxL-HCEjB:-MNo-XgS7QpUxL-HCEjC:b3tuzb7) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/bd76c226e18a220572c4915ce86237a073f66c57/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L68)):*
> ```
> return @{
> ```

Now we need the RestartTimeout here to. :wink: 


<!-- Sent from Reviewable.io -->

2020-12-05 18:59 UTC, Fiander reviewed
And i missed one in a unit test.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-:-MNmwyXJ0pdKP07JIZ6i:b-ou3vq8)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNo-h92DhkmDZYSxl06:-MNoGSCSDDb-ZlFgdpW-:bu0fupc) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can you update the list of resources here as well?

https://github.com/dsccommunity/SqlServerDsc/blob/ce786852a984ea364e1213d936f647bc5ebe4a30/source/SqlServerDsc.psd1#L38
</blockquote></details>

yes i can, and i did

---
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 244 at r7](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNmOrcw-IXP1B37YWRa:-MNmxH0L6CS0u6Z4Y0S6:b-r9aok2) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/36eb33caeaa99bfc015f8ca2c425bfdd555b3138/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L244)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Yes, you are welcome to add it now. I thought I'd spare you yet another change. :wink:  But let's add it now if you are up to it.
</blockquote></details>

already done. waiting for hqrm to succeed
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 68 at r9](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNo-XgS7QpUxL-HCEjB:-MNoGWEy3goe1CO9GLcQ:ba5xrq3) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/bd76c226e18a220572c4915ce86237a073f66c57/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L68)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> return @{
> ```

Now we need the RestartTimeout here to. :wink: 
</blockquote></details>

damm it... 


<!-- Sent from Reviewable.io -->

2020-12-05 19:00 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNo-h92DhkmDZYSxl06:-MNoGb2o8dxRjs5uRWO9:b-896fix) (no related file):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

yes i can, and i did
</blockquote></details>

Done.

---
___
*[source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, line 68 at r9](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-MNo-XgS7QpUxL-HCEjB:-MNoGaFfEFoeL7pSHabq:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/bd76c226e18a220572c4915ce86237a073f66c57/source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1#L68)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

damm it... 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-05 20:42 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1640#-:-MNod32gDs0FxIZg7gvw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-05 20:43 UTC, johlju commented
Waiting for the tests to pass and then we can merge this. 😃

2020-12-06 08:29 UTC, merged

2020-12-06 08:31 UTC, johlju commented
@Fiander awesome work on this! 😄  I can release a new full version of SqlServerDsc later today.