SqlAGDatabase Fix for issue #1492
dsccommunity/SqlServerDsc pull request #1642
Opened 2020-12-04 23:05 UTC by Fiander

#### Pull Request (PR) description
Added support for automatic seeding as per issue #1492. 
Added tests for this addition. 

#### This Pull Request (PR) fixes the following issues

Fixes #1492
#### Task list

- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [X] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [X] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2020-12-05 21:02 UTC, johlju requested changes
Started review on this one, but need to continue another day, just did a quick read-through for now.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-:-MNohJRr4yhSxnr0fy4u:b-ki6ifx)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @Fiander)

___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 442 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MNoegulBMsjpnBUEbF1:-MNoegum-sFGtpP3cQC9:b-xhgkzi) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/68c488fe61921088122b1550d20eae14c1c58ab5/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L442)):*
> ```
> $primaryServerObject.Databases[$databaseToAddToAvailabilityGroup].LastBackupDate.ToFileTimeUtc()  | Out-Null
> ```

Is it possible to use evaluate `$primaryServerObject.Databases[$databaseToAddToAvailabilityGroup].LastBackupDate` using if-statement instead of having try-catch-statement for this logic. Personally it feels wrong to throw an error to verify a false state. Just checking if there isn't a better way- :slightly_smiling_face: 
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 477 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MNog-L6BROGyj1E2XCJ:-MNog-L6BROGyj1E2XCK:b-kg9j3t) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/68c488fe61921088122b1550d20eae14c1c58ab5/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L477)):*
> ```PowerShell
>                     catch
>                     {
>                         # Log the failure
> ```

If the backup is needed and fails we should try to run `Add-SqlAvailabilityDatabase` on it further down? Feels like this need to be moved together with the other code?
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 498 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MNofg086GYwY-nDjPmI:-MNofg086GYwY-nDjPmJ:b-kg9j3t) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/68c488fe61921088122b1550d20eae14c1c58ab5/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L498)):*
> ```PowerShell
>                     catch
>                     {
>                         # Log the failure
> ```

If the backup is needed and fails we should try to run `Add-SqlAvailabilityDatabase` on it further down? Feels like this need to be moved together with the other code?


<!-- Sent from Reviewable.io -->

2020-12-05 21:05 UTC, johlju commented
In the comment above I meant to say "If the backup is needed and fails _should we_ try to run Add-SqlAvailabilityDatabase on it further down?". AG databases are not my strong suit so need your expertise here. 🙂

2020-12-05 22:58 UTC, Fiander reviewed
no problem :-)
about your comment of row 477. I did not change that code except for adding 4 spaces in front to align it with the added if ( $backupNeeded) statement. i don't know how the original code works when a backup fails, but in the unit tests there is in row 1247 a test for failed backups.  so i think that should be handled correctly.

Databases that can not be added to an availability group are reported by the resource ( row 642 - 651 )

When the seedingMode = 'Manual', then a backup is made, that is restored on all replica servers with norecovery.
then when that is done, the secondary's are added to the availability group, and the changes since the last log backup are transported trough the HADR port. When that synchronization is done ( the remote LSN matches the local LSN), the database is in sync and ready.

When the seedingMode = 'Automatic', then you can add a database to an availibility group, and trough the HADR port the complete database is synchronized. But that is only possible when the LSNs of the database make sense. and therefor at least one full backup is needed. the BAK file is not needed, just a full backup. The first full backup of a database set the database_lsn to zero, and from there the synchronization takes place.

this is also the reason i added two variables: backupneeded, and restoreneeded. with automatic seeding i never need a restore, but sometimes a backup. that backup may even be to "disk = nul".

                

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-:-MNp-2xI0H9uZRvn6Fzn:bipzgk9)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 442 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MNoegulBMsjpnBUEbF1:-MNp1Oyw8FI5Np6DanJJ:b-52parw) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/68c488fe61921088122b1550d20eae14c1c58ab5/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L442)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $primaryServerObject.Databases[$databaseToAddToAvailabilityGroup].LastBackupDate.ToFileTimeUtc()  | Out-Null
> ```

Is it possible to use evaluate `$primaryServerObject.Databases[$databaseToAddToAvailabilityGroup].LastBackupDate` using if-statement instead of having try-catch-statement for this logic. Personally it feels wrong to throw an error to verify a false state. Just checking if there isn't a better way- :slightly_smiling_face: 
</blockquote></details>

Done. i didn't like that code either.  now i found a way that is simpler.
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 477 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MNog-L6BROGyj1E2XCJ:-MNp1jZNAJNYbHwUQaU0:bh5dej3) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/68c488fe61921088122b1550d20eae14c1c58ab5/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L477)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

If the backup is needed and fails we should try to run `Add-SqlAvailabilityDatabase` on it further down? Feels like this need to be moved together with the other code?
</blockquote></details>

i dont know. all i did is put an if ( $backupNeeded) around that code. 
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 498 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MNofg086GYwY-nDjPmI:-MNp1zWiBLEJQxvIC9sW:bk8t51t) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/68c488fe61921088122b1550d20eae14c1c58ab5/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L498)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

If the backup is needed and fails we should try to run `Add-SqlAvailabilityDatabase` on it further down? Feels like this need to be moved together with the other code?
</blockquote></details>

 i dont know. all i did is put an if ( $backupNeeded) around that code. 


<!-- Sent from Reviewable.io -->

2020-12-12 11:03 UTC, johlju commented
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 477 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MNog-L6BROGyj1E2XCJ:-MOLbQCH9fjcvkC7zH0M:bfcgf14) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/68c488fe61921088122b1550d20eae14c1c58ab5/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L477)):*
<details><summary><i>Previously, Fiander wrote…</i></summary><blockquote>

i dont know. all i did is put an if ( $backupNeeded) around that code. 
</blockquote></details>

Ah, I missed that it was inly whitespace diff, I thought this was all new code. My mistake,


<!-- Sent from Reviewable.io -->

2020-12-12 11:26 UTC, johlju requested changes
Awesome work! :smiley: Thanks for the explanation above. Just tiny changes needed.

> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-:-MOLgiTYEBBRd24PggY9:bjm907a)* status: all files reviewed, 12 unresolved discussions (waiting on @Fiander)

___
*[CHANGELOG.md, line 10 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLfrqPEcWBk3UihyGl:-MOLfrqPEcWBk3UihyGm:b-th57x6) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L10)):*
> ```
> Resource
> ```

Tiny typo. lower-case 'r' in "resource"
___
*[CHANGELOG.md, line 10 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLg2eUC7Fw_05LjhY8:-MOLg2eUC7Fw_05LjhY9:b-hzqwkq) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L10)):*
> ```
> ste-TargetResource
> ```

Tiny typo. 'Set' in "Set-TargetResource"
___
*[CHANGELOG.md, line 11 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLgBg2-8tCoHCqH0Xm:-MOLgBg2-8tCoHCqH0Xn:b4nimup) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L11)):*
> ```
> availibility
> ```

Tiny typo. "availability"
___
*[CHANGELOG.md, line 11 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLgK7m1Q2RdUUOEV4u:-MOLgK7m1Q2RdUUOEV4v:b-ob00vr) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L11)):*
> ```
> wil
> ```

Tiny typo. "will"
___
*[CHANGELOG.md, line 12 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLf7yRA_HCXHRdIeA4:-MOLf7yRA_HCXHRdIeA5:b-480ex3) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L12)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> - AGDatabase
>   - Fix for issue ([issue #1492](https://github.com/dsccommunity/SqlServerDsc/issues/1492))
>     added AutomaticSeeding for this Resource. In ste-TargetResource added logic that looks
>     at all replicas of an availibility group. When automatic seedig is found, it wil use that.
>   - Lots of extra tests to check AutomaticSeeding.
>   - Backuppath is still needed just in case a database never has been backuped before.
> ```
</details>


Need to rebase (resolve conflicts) when you have time, and the move this back under unreleased section since it was a release done after this PR. Normale git does see that automatically and move it to the wrong place (well fotr git it is the correct place :slightly_smiling_face: ). 
___
*[CHANGELOG.md, line 13 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLgUz84-j2P7dSRSDM:-MOLgUz84-j2P7dSRSDN:b-cl6nvl) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L13)):*
> ```
> Backuppath
> ```

I think we should have a space between: 'backup path'?
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 237 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLdlxD0cI1hE2ji3VC:-MOLdlxD0cI1hE2ji3VD:bceg1jp) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L237)):*
> ```
> Removed
> ```

Nitpick: lower-case 'r' here.
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 425 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLc5oxCdv4KkM-ATlC:-MOLc5oxCdv4KkM-ATlD:b-mzwyru) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L425)):*
> ```
> #Determine...
> ```

We should add space after `#` (`# Determine...`
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 425 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLcXCRDyJBKgYjSeem:-MOLcXCRDyJBKgYjSeen:bw61d4a) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L425)):*
> ```
> an backup is not needed
> ```

should say "backup and restore is not needed"?
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 428 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLcI9C3dZ7YOEo61E5:-MOLcI9C3dZ7YOEo61E6:b-ii1vw2) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L428)):*
> ```
> foreach ( $availabilityGroupReplica in $secondaryReplicas )
> ```

Nitpick: Can we add a blank row before this row to get some air in the code?
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 439 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLcxWR8qc6PsVPQihs:-MOLcxWR8qc6PsVPQiht:b-toqfyi) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L439)):*
> ```
>                 # Because an availibility group can only be made when the database has at least one backup,
>                 # if there is no backup, create one. This backup is not needed for restore, only the initial setup
>                 # of the LSN in the database is needed
> ```

Multi line comments should use `<# #>` and indent the comment, like:
```powershell
<#
    Because an availability group can only be made when the database has at least one backup,
    if there is no backup, create one. This backup is not needed for restore, only the initial setup
    of the LSN in the database is needed.
#>
```

There was a tiny typo that I changed too in `availability`
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 607 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLeAnqDrWRROQzhCIb:-MOLeAnqDrWRROQzhCIc:bieygh9) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L607)):*
> ```
> #Wanneer er een backup gemaakt is, moet die hier verwijderd worden.
> ```

Can we get this one in english please :wink:  


<!-- Sent from Reviewable.io -->

2020-12-12 20:41 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642)* status: 0 of 5 files reviewed, 12 unresolved discussions (waiting on @johlju)

___
*[CHANGELOG.md, line 10 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLfrqPEcWBk3UihyGl:-MONf2qF9Y4YCdsjPZmq:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Resource
> ```

Tiny typo. lower-case 'r' in "resource"
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 10 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLg2eUC7Fw_05LjhY8:-MONf3XB0w5uxOB0RD2f:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ste-TargetResource
> ```

Tiny typo. 'Set' in "Set-TargetResource"
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 11 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLgBg2-8tCoHCqH0Xm:-MONf3xn6Qxxri5bdFT6:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> availibility
> ```

Tiny typo. "availability"
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 11 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLgK7m1Q2RdUUOEV4u:-MONf4V4DU78a3RV6tUd:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> wil
> ```

Tiny typo. "will"
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 12 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLf7yRA_HCXHRdIeA4:-MONf5Sl0Z1a-SB5DWIs:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L12)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> - AGDatabase
>   - Fix for issue ([issue #1492](https://github.com/dsccommunity/SqlServerDsc/issues/1492))
>     added AutomaticSeeding for this Resource. In ste-TargetResource added logic that looks
>     at all replicas of an availibility group. When automatic seedig is found, it wil use that.
>   - Lots of extra tests to check AutomaticSeeding.
>   - Backuppath is still needed just in case a database never has been backuped before.
> ```

Need to rebase (resolve conflicts) when you have time, and the move this back under unreleased section since it was a release done after this PR. Normale git does see that automatically and move it to the wrong place (well fotr git it is the correct place :slightly_smiling_face: ). 
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 13 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLgUz84-j2P7dSRSDM:-MONf6555T_20Z7X98z9:bdz45zo) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/CHANGELOG.md#L13)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Backuppath
> ```

I think we should have a space between: 'backup path'?
</blockquote></details>

No. but i have changed it to $BackupPath to make clear we stil need that variable despite automaticSeeding.
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 237 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLdlxD0cI1hE2ji3VC:-MONfPs76LQq2yKjzWIF:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L237)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Removed
> ```

Nitpick: lower-case 'r' here.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 425 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLc5oxCdv4KkM-ATlC:-MONfZ8e04Dmp2O4-bBO:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L425)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #Determine...
> ```

We should add space after `#` (`# Determine...`
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 425 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLcXCRDyJBKgYjSeem:-MONfZm75RQgqHQ9DTJS:bfymgzr) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L425)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> an backup is not needed
> ```

should say "backup and restore is not needed"?
</blockquote></details>

Restore not needed, backup..... maybe...
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 428 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLcI9C3dZ7YOEo61E5:-MONffv67yXzOhHezIZO:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L428)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> foreach ( $availabilityGroupReplica in $secondaryReplicas )
> ```

Nitpick: Can we add a blank row before this row to get some air in the code?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 439 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLcxWR8qc6PsVPQihs:-MONfhDJ7rqbix5Sx85y:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L439)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                 # Because an availibility group can only be made when the database has at least one backup,
>                 # if there is no backup, create one. This backup is not needed for restore, only the initial setup
>                 # of the LSN in the database is needed
> ```

Multi line comments should use `<# #>` and indent the comment, like:
```powershell
<#
    Because an availability group can only be made when the database has at least one backup,
    if there is no backup, create one. This backup is not needed for restore, only the initial setup
    of the LSN in the database is needed.
#>
```

There was a tiny typo that I changed too in `availability`
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 607 at r3](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOLeAnqDrWRROQzhCIb:-MONfou25x7epoPUrISz:bqdrft0) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/9808962de9103f9f7512abe28870265771c037ea/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L607)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #Wanneer er een backup gemaakt is, moet die hier verwijderd worden.
> ```

Can we get this one in english please :wink:  
</blockquote></details>

oops... part of the pseudoCode ive started with... forgot to create real comment.


<!-- Sent from Reviewable.io -->

2020-12-13 07:49 UTC, johlju requested changes
> Reviewed 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642)* status: all files reviewed, 3 unresolved discussions (waiting on @Fiander)

___
*[CHANGELOG.md, line 10 at r9](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOQ2BfhBDy_YL8awJm7:-MOQ2BfhBDy_YL8awJm8:b-i860yx) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3accf967a01f0db18393710b0cc3fc9bb9b6258a/CHANGELOG.md#L10)):*
> ```
> AGDatabase
> ```

Should be SqlAGDatabase
___
*[CHANGELOG.md, line 12 at r9](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOQ26_i6QiW4J85_unH:-MOQ26_i6QiW4J85_unI:b6xi2eu) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3accf967a01f0db18393710b0cc3fc9bb9b6258a/CHANGELOG.md#L12)):*
> ```
> set
> ```

Upper-case 'S' in 'Set'.
___
*[CHANGELOG.md, line 15 at r9](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOQ2uyN6UBJqs7rOlcM:-MOQ2uyN6UBJqs7rOlcN:b-otfv6p) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3accf967a01f0db18393710b0cc3fc9bb9b6258a/CHANGELOG.md#L15)):*
> ```
> $BackupPath
> ```

Maybe: ```The parameter `BackupPath` is still...```
That would make it more clear fo users what is meant?


<!-- Sent from Reviewable.io -->

2020-12-13 11:54 UTC, Fiander reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[CHANGELOG.md, line 10 at r9](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOQ2BfhBDy_YL8awJm7:-MOQx-3g7FxyuxympWf9:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3accf967a01f0db18393710b0cc3fc9bb9b6258a/CHANGELOG.md#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> AGDatabase
> ```

Should be SqlAGDatabase
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 12 at r9](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOQ26_i6QiW4J85_unH:-MOQx-NH3f4DEABxhOpr:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3accf967a01f0db18393710b0cc3fc9bb9b6258a/CHANGELOG.md#L12)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> set
> ```

Upper-case 'S' in 'Set'.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 15 at r9](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-MOQ2uyN6UBJqs7rOlcM:-MOQx-o174d5yAFl7rsv:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3accf967a01f0db18393710b0cc3fc9bb9b6258a/CHANGELOG.md#L15)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $BackupPath
> ```

Maybe: ```The parameter `BackupPath` is still...```
That would make it more clear fo users what is meant?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-13 12:11 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642#-:-MOR-c9A3FfEi0ibgLUa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-13 12:51 UTC, johlju approved these changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1642)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-13 16:24 UTC, merged