SqlLogin: Added and amended integration tests for logins of 'SqlLogin' type (Fixes #361)
dsccommunity/SqlServerDsc pull request #1652
Opened 2020-12-14 15:57 UTC by SphenicPaul

#### Pull Request (PR) description
Updated a number of the `SqlLogin` resource, integration tests:
* Create a new, `SqlLogin` that doesn't use the same name as the SQL administration account used in the integration tests
* Ensure a new, `SqlLogin` resource of `SqlLogin` type (rather than type `Windows`) can be used to connect into the database (once created by the DSC resource)
* Ensure the default database connected to (as part of the above) is the same as specified in the resource's `DefaultDatabase` property/parameter (this didn't appear to be covered by any integration tests)
* Add assertions/tests (again, to add additional test coverage) around the `SqlLogin` specific parameters (that don't apply to `Windows` types):
  * `LoginMustChangePassword` 
  * `LoginPasswordExpirationEnabled`
  * `LoginPasswordPolicyEnforced`
* Added configuration to test the update of a `SqlLogin` type (including assertions of all of the above), and also including password change (to resolve #361)

#### This Pull Request (PR) fixes the following issues

- Fixes #361

#### Task list
- [ ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2020-12-23 14:46 UTC, johlju commented
I will get on this tomorrow. 🙂

2020-12-24 09:51 UTC, johlju requested changes
> Reviewed 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @SphenicPaul)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ99YUECmCgfDJ6lP1:-MPJ99YUECmCgfDJ6lP2:b-os6v5e) (no related file):*
Please update the following section if there are more objects (logins) left by he integration tests.

---
___
*[CHANGELOG.md, line 22 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ3Q802aWxCJIXORdr:-MPJ3Q802aWxCJIXORds:bh6igmi) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/CHANGELOG.md#L22)):*
> ```
> SqlLogin
> ```

Wouldn't mind if the text in the PR description made it's way into the changelog too. I think all the changes to integration tests and referencing the issues they close would be good information to end users.
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 458 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ5WpLC-je0wCze5fv:-MPJ5WpLC-je0wCze5fw:bw5oc23) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L458)):*
> ```
> if ($null -eq $loginInfo)
> ```

This must be a bug in `Get-TargetResource` and we should fix it there. The function `Get-TargetResource` should always return a hashtable with the same properties as the schema, it is not allowed to return `$null`. Values for the properties returned should be at minimum the values of the mandatory parameters if the login does not exist.

Is the root cause bug in `Get-TargetResource` that the `Connect-SQL` are not wrapped in a `try`/`catch`-block? 
___
*[source/DSCResources/DSC_SqlLogin/README.md, line 13 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ4P1SBvj6SQkRoZXN:-MPJ4P1SBvj6SQkRoZXO:b-ihx1x4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/source/DSCResources/DSC_SqlLogin/README.md#L13)):*
> ```
> (only valid when the `LoginType` is `'SqlLogin'`)
> ```

This part could be misread as the parameter `LoginMustChangePassword` is only valid to use for SQL logins. I think you mean that the requirement is only valid on SQL logins? Can we rephrase?
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 292 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ810Q0BX4_HDLYMSy:-MPJ810Q0BX4_HDLYMSz:bql88p8) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L292)):*
> ```
> ...and password to correct...
> ```

I'm not following you here with "correct". Can we rephrase this part? 
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 381 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ8XA1BPRlkET3MSGG:-MPJ8XA1BPRlkET3MSGH:bum4pgj) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L381)):*
> ```
> ...password to correct...
> ```

I'm not following you here with "correct". Can we rephrase this part? 


<!-- Sent from Reviewable.io -->

2020-12-24 09:52 UTC, johlju commented
@SphenicPaul Awesome work on this one! Thank you for updating the integration tests! Just a few comments, most minor.

2020-12-24 09:54 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @SphenicPaul)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ99YUECmCgfDJ6lP1:-MPJ9oad854UbdTmo1fw:b-k75j8v) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please update the following section if there are more objects (logins) left by he integration tests.
</blockquote></details>

Forgot to paste the link. :slightly_smiling_face: 

Please update the following section if there are more objects (logins) left by he integration tests:
https://github.com/dsccommunity/SqlServerDsc/blob/master/tests/Integration/README.md#sqllogin

---


<!-- Sent from Reviewable.io -->

2020-12-24 10:45 UTC, johlju commented
@SphenicPaul I very much appreciate your help with commenting and cleaning up old issues. 🙇 🙂

2020-12-24 12:07 UTC, SphenicPaul commented
No worries. I was initially looking through old issues defined as “bug” and started on a “SqlLogin” fix. I also tried to find related ones that might be “quick wins” that I could fix in the same PR (without making the PR too large). 

A few looked pretty related and/or stale so might as well try and get the issue counts and bug counts down by getting some of these fixed/closed. 🙂

I’ll try and look at this PR again next week (thanks for reviewing) - The points make sense but I need to take more of a look at potential bug you mention.

2021-01-07 13:06 UTC, SphenicPaul commented
Note: Will still be looking at this... possibly at the weekend.

2021-01-09 16:23 UTC, johlju commented
@SphenicPaul sounds great, looking forward to merging this. 🙂

2021-01-10 09:37 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @SphenicPaul)

___
*[CHANGELOG.md, line 22 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQfdip7DX4MSr1bjbg9:-MQfdip7DX4MSr1bjbgA:bq8o3of) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/CHANGELOG.md#L22)):*
> ```Markdown
>   - Lots of extra tests to check AutomaticSeeding.
>   - The parameter `BackupPath` is still needed just in case a database never has been backuped before.
> - SqlLogin
> ```

I just published a new release so when resolving conflicts make sure the entries is moved up to the Unreleased section again. :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2021-01-10 14:58 UTC, SphenicPaul reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @johlju and @SphenicPaul)

___
*[CHANGELOG.md, line 22 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ3Q802aWxCJIXORdr:-MQgiRJfDIG3A3mwc9-Z:b-npqpai) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/CHANGELOG.md#L22)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> SqlLogin
> ```

Wouldn't mind if the text in the PR description made it's way into the changelog too. I think all the changes to integration tests and referencing the issues they close would be good information to end users.
</blockquote></details>

I've added more information (taken from the PR description) into the CHANGELOG around the `SqlLogin` resource.
___
*[CHANGELOG.md, line 22 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQfdip7DX4MSr1bjbg9:-MQgihZ68s7O0ugYigMS:b3h68k1) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/CHANGELOG.md#L22)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I just published a new release so when resolving conflicts make sure the entries is moved up to the Unreleased section again. :slightly_smiling_face: 
</blockquote></details>

I was having some problems updating my branch from updates in the `master` (now `main`) branch but think this is resolved now.

I've removed the #792 issue/fix for now pending investigation.
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 458 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ5WpLC-je0wCze5fv:-MQgQUkL8zruxPoMO0gM:bcrd37h) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L458)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($null -eq $loginInfo)
> ```

This must be a bug in `Get-TargetResource` and we should fix it there. The function `Get-TargetResource` should always return a hashtable with the same properties as the schema, it is not allowed to return `$null`. Values for the properties returned should be at minimum the values of the mandatory parameters if the login does not exist.

Is the root cause bug in `Get-TargetResource` that the `Connect-SQL` are not wrapped in a `try`/`catch`-block? 
</blockquote></details>

I'll try and dig into this further while the integration tests are running on other changes following these comments.
___
*[source/DSCResources/DSC_SqlLogin/README.md, line 13 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ4P1SBvj6SQkRoZXN:-MQgOF0n5S_oj_9kqhCg:bdldjx5) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/source/DSCResources/DSC_SqlLogin/README.md#L13)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> (only valid when the `LoginType` is `'SqlLogin'`)
> ```

This part could be misread as the parameter `LoginMustChangePassword` is only valid to use for SQL logins. I think you mean that the requirement is only valid on SQL logins? Can we rephrase?
</blockquote></details>

I've split the single bullet point into a couple to try and make this clearer. Could you have a look if this now reads any better/clearer than before?
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 292 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ810Q0BX4_HDLYMSy:-MQgMpUbBOVqgsfN2F-z:b-1wxdb4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L292)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ...and password to correct...
> ```

I'm not following you here with "correct". Can we rephrase this part? 
</blockquote></details>

OK. So with this test, I'd missed a few words from the name of the test. The idea is that the test ensures that if the login is used to connect to the database (when no database is specified in the connection string) the login connects into the same default database as specified by the login when created (ensuring the default database property has been applied OK).
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 381 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ8XA1BPRlkET3MSGG:-MQgNWaT4Ro7LjH152f2:bjgguks) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L381)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ...password to correct...
> ```

I'm not following you here with "correct". Can we rephrase this part? 
</blockquote></details>

Similar to the other test/comment, I'd missed a few words from the name of the test. This test is verifying the same as the as the other and is using the same login as the other however, this is being run after the login (including it's password) has been changed/updated.

I've also just updated the passwords back to be consistent with the documentation and added an additional test to update/set the `DscUser4` login back to the state before it was changed. The additional test doesn't cover much additional functionality (other than an additional change back to a previous set of values) but ensures that login only has a different/changed password for a minimal amount of time (and therefore there's less of an issue with knowing which password to use at what point in the integration tests).


<!-- Sent from Reviewable.io -->

2021-01-10 15:12 UTC, SphenicPaul reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ99YUECmCgfDJ6lP1:-MQgqEEbBris6N64vQ5L:b-896fix) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Forgot to paste the link. :slightly_smiling_face: 

Please update the following section if there are more objects (logins) left by he integration tests:
https://github.com/dsccommunity/SqlServerDsc/blob/master/tests/Integration/README.md#sqllogin

</blockquote></details>

Done.

---
___
*[CHANGELOG.md, line 22 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQfdip7DX4MSr1bjbg9:-MQgqXVS8ELIwRkaefpD:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/CHANGELOG.md#L22)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

I was having some problems updating my branch from updates in the `master` (now `main`) branch but think this is resolved now.

I've removed the #792 issue/fix for now pending investigation.
</blockquote></details>

Done.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 381 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ8XA1BPRlkET3MSGG:-MQgq0sz6m0Ap2LDRtvQ:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L381)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

Similar to the other test/comment, I'd missed a few words from the name of the test. This test is verifying the same as the as the other and is using the same login as the other however, this is being run after the login (including it's password) has been changed/updated.

I've also just updated the passwords back to be consistent with the documentation and added an additional test to update/set the `DscUser4` login back to the state before it was changed. The additional test doesn't cover much additional functionality (other than an additional change back to a previous set of values) but ensures that login only has a different/changed password for a minimal amount of time (and therefore there's less of an issue with knowing which password to use at what point in the integration tests).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-10 16:02 UTC, SphenicPaul reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 458 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ5WpLC-je0wCze5fv:-MQgyXKk2DEyOwhVJ4RQ:bt7475k) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L458)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

I'll try and dig into this further while the integration tests are running on other changes following these comments.
</blockquote></details>

After having a further look at #792, I'd be of the opinion that this issue should be closed. 

We have integration tests (some added as part of this PR) that add SQL Logins, then update those SQL Logins (that now exist) and delete them (and assert these actions work as expected). None of those seem to demonstrate/highlight the issue raised (therefore, I'd be happy to confirm it wasn't one) ..... unless you've suggestions to counter that? - Your comments from the issue at the time seemed to highlight the area that needed fixing, but guess those may have been incorrect? especially given `Get-TargetResource` would return always return hashtable/value?.... Not sure if you can add any more information/context to the original comments (though it was 2017).

I'd agree with your comments that `Get-TargetResource` should always return a value and the `Connect-SQL` usage is no different to other resources so I'd probably look to leave that as it is on the assumption it is working as expected (and seems to have tests to evidence that).

I've removed the check/condition I added in this `SqlLogin` resource to check for the $null, `Get-TargetResource` output (and I've also removed the related unit test) so it's back as it originally was.


<!-- Sent from Reviewable.io -->

2021-01-10 16:03 UTC, SphenicPaul reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 458 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ5WpLC-je0wCze5fv:-MQh1KbFEe08yfIpTeme:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L458)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

After having a further look at #792, I'd be of the opinion that this issue should be closed. 

We have integration tests (some added as part of this PR) that add SQL Logins, then update those SQL Logins (that now exist) and delete them (and assert these actions work as expected). None of those seem to demonstrate/highlight the issue raised (therefore, I'd be happy to confirm it wasn't one) ..... unless you've suggestions to counter that? - Your comments from the issue at the time seemed to highlight the area that needed fixing, but guess those may have been incorrect? especially given `Get-TargetResource` would return always return hashtable/value?.... Not sure if you can add any more information/context to the original comments (though it was 2017).

I'd agree with your comments that `Get-TargetResource` should always return a value and the `Connect-SQL` usage is no different to other resources so I'd probably look to leave that as it is on the assumption it is working as expected (and seems to have tests to evidence that).

I've removed the check/condition I added in this `SqlLogin` resource to check for the $null, `Get-TargetResource` output (and I've also removed the related unit test) so it's back as it originally was.


</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-10 16:10 UTC, SphenicPaul commented
@johlju - I'm hoping I've addressed/resolved your points/requests - Let me know if there are any further items.

I'll keep an eye out (and resolve) any failing tests (running at present) but I'm not expecting to have to make any further changes for this off the back of your requested changes (unless you have any subsequent ones for the changelog).

If there are, and they are quick to make, I'll look to make these later tonight or early this week to try and close of this PR.

Shout if you've any questions/comments etc.

2021-01-11 08:06 UTC, SphenicPaul commented
@johlju - Are you able to trigger the failed jobs in this Azure pipeline run (I don’t have the permissions). It looks like they both timed out but not exactly sure why.

2021-01-11 12:44 UTC, johlju commented
Yep, I will look at it.

2021-01-11 12:45 UTC, johlju commented
Look like Azure Pipelines lost connection with the build worker "This job was abandoned. We have detected that logs from the agent may have not finished uploading. We have included our in-memory record of all log lines uploaded before we lost contact with the agent"

2021-01-11 12:51 UTC, SphenicPaul commented
Thanks. I can see that's running again.

If the same happens (i.e. a timout/failure) again, I'll take another look incase it's something wrong with any changes I've made to the integration tests.

2021-01-11 12:56 UTC, johlju commented
I have never seen that happen before, so guessing it was a temporary problem with Azure Pipelines, not the change to the tests. 🙂

2021-01-11 13:43 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-:-MQlfrmq9JN_VijoKFKb:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @SphenicPaul)

___
*[CHANGELOG.md, line 8 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQldYJH2u7QZxGLuSFQ:-MQldYJH2u7QZxGLuSFR:bb0nldt) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/CHANGELOG.md#L8)):*
> ```
> ## [15.0.1] - 2021-01-09
> ```

This section header should be removed, guessing it was wrongly duplicated from below. :slightly_smiling_face: 
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 458 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ5WpLC-je0wCze5fv:-MQleSiD7Ts48ZYAWf3v:b5xythl) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L458)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Closed the issue as per your suggestion.
___
*[source/DSCResources/DSC_SqlLogin/README.md, line 13 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ4P1SBvj6SQkRoZXN:-MQleyE40TwtvH0DXCyD:b9bkkp1) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/source/DSCResources/DSC_SqlLogin/README.md#L13)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

I've split the single bullet point into a couple to try and make this clearer. Could you have a look if this now reads any better/clearer than before?
</blockquote></details>

Looks great!
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 292 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ810Q0BX4_HDLYMSy:-MQlfRCq8nX-DQ_qDi2N:b-vs1prh) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L292)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

OK. So with this test, I'd missed a few words from the name of the test. The idea is that the test ensures that if the login is used to connect to the database (when no database is specified in the connection string) the login connects into the same default database as specified by the login when created (ensuring the default database property has been applied OK).
</blockquote></details>

Looks good!
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 381 at r2](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MPJ8XA1BPRlkET3MSGG:-MQlf_4yEkqPkT7zQPeO:bpal0mp) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/0db46c02f39fff8c9fbabbfb75b1098ee794a9ff/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L381)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great! Looks good!


<!-- Sent from Reviewable.io -->

2021-01-11 13:43 UTC, johlju commented
@SphenicPaul just a tiny comment in the CHANGELOG.md. Looks good to me after that!

2021-01-11 13:49 UTC, johlju commented
Seems it failed on the new integration test:
```
    Context When using configuration DSC_SqlLogin_AddLoginDscUser4_Config (to update back to original password)
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = 
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = 
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer WIN-ENKPUBRUPEL with user sid 
S-1-5-21-2303587632-266063863-609898013-500.
VERBOSE: [WIN-ENKPUBRUPEL]: LCM:  [ Start  Set      ]
VERBOSE: [WIN-ENKPUBRUPEL]: LCM:  [ Start  Resource ]  [[SqlLogin]Integration_Test]
VERBOSE: [WIN-ENKPUBRUPEL]: LCM:  [ Start  Test     ]  [[SqlLogin]Integration_Test]
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Determines if the login 'DscUser4' 
at the instance 'WIN-ENKPUBRUPEL\DSCSQLTEST' has the correct state.
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Getting the login 'DscUser4' from 
the instance 'WIN-ENKPUBRUPEL\DSCSQLTEST'.
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Preferred module SqlServer found. 
(SQLCOMMON0023)
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Importing PowerShell module 
'SqlServer' with version '21.1.18230' from path 'C:\Program 
Files\WindowsPowerShell\Modules\SqlServer\21.1.18230\SqlServer.psm1'. (SQLCOMMON0025)
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Connecting as current user 
'WIN-ENKPUBRUPEL\SqlAdmin' using integrated security. (SQLCOMMON0054)
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Connected to SQL instance 
'WIN-ENKPUBRUPEL\DSCSQLTEST'. (SQLCOMMON0018)
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] The login 'DscUser4' is Present at 
the instance 'WIN-ENKPUBRUPEL\DSCSQLTEST'.
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] The login 'DscUser4' has the 
password expiration disabled, but expected it to be enabled.
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] The login 'DscUser4' has the 
password policy enforced disabled, but expected it to be enabled.
VERBOSE: [WIN-ENKPUBRUPEL]: LCM:  [ End    Test     ]  [[SqlLogin]Integration_Test]  in 7.7380 seconds.
VERBOSE: [WIN-ENKPUBRUPEL]: LCM:  [ Start  Set      ]  [[SqlLogin]Integration_Test]
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Found PowerShell module SqlServer 
already imported in the session. (SQLCOMMON0026)
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Connecting as current user 
'WIN-ENKPUBRUPEL\SqlAdmin' using integrated security. (SQLCOMMON0054)
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Connected to SQL instance 
'WIN-ENKPUBRUPEL\DSCSQLTEST'. (SQLCOMMON0018)
VERBOSE: [WIN-ENKPUBRUPEL]:                            [[SqlLogin]Integration_Test] Setting password expiration enabled
 to 'True' for the login 'DscUser4' on the instance 'WIN-ENKPUBRUPEL\DSCSQLTEST'.
VERBOSE: [WIN-ENKPUBRUPEL]: LCM:  [ End    Set      ]  [[SqlLogin]Integration_Test]  in 0.4700 seconds.
      [-] Should re-compile and re-apply the MOF without throwing 9.17s
        Expected no exception to be thrown, but an exception "PowerShell DSC resource DSC_SqlLogin  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: Altering the login 'DscUser4' failed. ---> System.Management.Automation.MethodInvocationException: Exception calling "Alter" with "0" argument(s): "Alter failed for Login 'DscUser4'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Alter failed for Login 'DscUser4'.  ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> System.Data.SqlClient.SqlException: The CHECK_EXPIRATION option cannot be used when CHECK_POLICY is OFF.
           at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
           --- End of inner exception stack trace ---
           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
           at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType, Boolean retry)
           at Microsoft.SqlServer.Management.Smo.SqlSmoObject.AlterImplFinish(StringCollection alterQuery, ScriptingPreferences sp)
           at Microsoft.SqlServer.Management.Smo.SqlSmoObject.AlterImplWorker()
           at Microsoft.SqlServer.Management.Smo.SqlSmoObject.AlterImpl()
           --- End of inner exception stack trace ---
           at Microsoft.SqlServer.Management.Smo.SqlSmoObject.AlterImpl()
           at CallSite.Target(Closure , CallSite , Login )
           --- End of inner exception stack trace ---
           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
           --- End of inner exception stack trace --- " was thrown from D:\a\1\s\tests\Integration\DSC_SqlLogin.Integration.Tests.ps1:428 char:21
            + ...               Start-DscConfiguration @startDscConfigurationParameters
            +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
        429:                 } | Should -Not -Throw
        at <ScriptBlock>, D:\a\1\s\tests\Integration\DSC_SqlLogin.Integration.Tests.ps1: line 410
```

2021-01-11 13:55 UTC, johlju commented
It seems the integration tests hangs after that test. Never seen that happen before. 😄 Is it missing error handling somewhere? The tests should have continued even if it has thrown. 🤔

2021-01-11 14:06 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: all files reviewed, 9 unresolved discussions (waiting on @SphenicPaul)

___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 284 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQljG7L6AAiVBqaO60u:-MQljG7L6AAiVBqaO60v:ba1zh6p) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L284)):*
> ```
> $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
> ```

Let's move this into the scriptblock below together with `Open()`. If the type does not exist it will throw also, then we are missing something to run the test.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 303 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQljWGk1kYpeoZuXe2e:-MQljWGk1kYpeoZuXe2f:b80u8yv) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L303)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>                 $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
>                 $sqlCommand = New-Object System.Data.SqlClient.SqlCommand('SELECT DB_NAME() as CurrentDatabaseName', $sqlConnection)
>                 $sqlConnection.Open()
>                 $sqlDataAdapter = New-Object System.Data.SqlClient.SqlDataAdapter $sqlCommand
>                 $sqlDataSet = New-Object System.Data.DataSet
>                 $sqlDataAdapter.Fill($sqlDataSet) | Out-Null
>                 $sqlConnection.Close()
> ```
</details>


We should have this in `{ ... } | Should -Not -Thow`. Use `$script:` scope to pass out variables outside the scriptblock.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 373 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQljtqWA-zSJ1z3osFL:-MQljtqWA-zSJ1z3osFM:bvvz96k) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L373)):*
> ```
> $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
> ```

Let's move this into the scriptblock below together with `Open()`.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 393 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQljxpM2dD4P735gWnx:-MQljxpM2dD4P735gWny:b-1jv4u) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L393)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>                 $sqlConnectionString = 'Data Source={0}\{1};User ID={2};Password={3};Connect Timeout=5;' -f $serverName, $instanceName, $userName, $password # Note: Not providing a database name
>                 $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
>                 $sqlCommand = New-Object System.Data.SqlClient.SqlCommand('SELECT DB_NAME() as CurrentDatabaseName', $sqlConnection)
>                 $sqlConnection.Open()
>                 $sqlDataAdapter = New-Object System.Data.SqlClient.SqlDataAdapter $sqlCommand
>                 $sqlDataSet = New-Object System.Data.DataSet
>                 $sqlDataAdapter.Fill($sqlDataSet) | Out-Null
>                 $sqlConnection.Close()
> ```
</details>


We should have this in `{ ... } | Should -Not -Thow`. Use `$script:` scope to pass out variables outside the scriptblock.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 404 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQlk1J6-X4vYfdaPEKv:-MQlk1J6-X4vYfdaPEKw:b2jv1zq) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L404)):*
> ```
>         # Note that this configuration has already been run within these Integration tests but is
>         # executed once more to reset the password back to the original one provided.
> ```

We should use comment-block when the comment is more than 1 row.

```powershell
<#
    Note that this configuration has already been run within these Integration tests but is
    executed once more to reset the password back to the original one provided.
#>
```
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 450 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQlkVC63YkDkckxAfyf:-MQlkK9n-MY0KeUHdAzd:bvvz96k) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L450)):*
> ```
> $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
> ```

Let's move this into the scriptblock below together with `Open()`.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 567 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQlkfBW8yjE-wsDtGdA:-MQlkfBW8yjE-wsDtGdB:bt251ep) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L567)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>             # Close any existing connections into the database before it is dropped
>             $serverName = $ConfigurationData.AllNodes.ServerName
>             $instanceName = $ConfigurationData.AllNodes.InstanceName
>             $userName = $ConfigurationData.AllNodes.DscUser4Name
>             $password = $ConfigurationData.AllNodes.DscUser4Pass1 # Using original password
>             $defaultDbName = $ConfigurationData.AllNodes.DefaultDbName
>             $sqlConnectionString = 'Data Source={0}\{1};User ID={2};Password={3};Connect Timeout=5;Database=master;' -f $serverName, $instanceName, $userName, $password
>             $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
>             $sqlStatement = "ALTER DATABASE [{0}] SET OFFLINE WITH ROLLBACK IMMEDIATE" -f $defaultDbName
>             $sqlCommand = New-Object System.Data.SqlClient.SqlCommand($sqlStatement, $sqlConnection)
>             $sqlConnection.Open()
>             $sqlCommand.ExecuteNonQuery()
>             $sqlConnection.Close()
> ```
</details>


We should have this code in an It-block. We should also have this in `{ ... } | Should -Not -Thow`. Use `$script:` scope to pass out variables outside the scriptblock.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 576 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQllA8N1GUPFt6S1O8w:-MQllA8N1GUPFt6S1O8x:b8x2f39) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L576)):*
> ```
> "ALTER DATABASE [{0}] SET OFFLINE WITH ROLLBACK IMMEDIATE"
> ```

We can using single quotes around this string (`'`).


<!-- Sent from Reviewable.io -->

2021-01-11 14:09 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: all files reviewed, 9 unresolved discussions (waiting on @SphenicPaul)

___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 567 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQlkfBW8yjE-wsDtGdA:-MQllNkk6ckSHOc93juR:b-k3fhgo) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L567)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>             # Close any existing connections into the database before it is dropped
>             $serverName = $ConfigurationData.AllNodes.ServerName
>             $instanceName = $ConfigurationData.AllNodes.InstanceName
>             $userName = $ConfigurationData.AllNodes.DscUser4Name
>             $password = $ConfigurationData.AllNodes.DscUser4Pass1 # Using original password
>             $defaultDbName = $ConfigurationData.AllNodes.DefaultDbName
>             $sqlConnectionString = 'Data Source={0}\{1};User ID={2};Password={3};Connect Timeout=5;Database=master;' -f $serverName, $instanceName, $userName, $password
>             $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
>             $sqlStatement = "ALTER DATABASE [{0}] SET OFFLINE WITH ROLLBACK IMMEDIATE" -f $defaultDbName
>             $sqlCommand = New-Object System.Data.SqlClient.SqlCommand($sqlStatement, $sqlConnection)
>             $sqlConnection.Open()
>             $sqlCommand.ExecuteNonQuery()
>             $sqlConnection.Close()
> ```

We should have this code in an It-block. We should also have this in `{ ... } | Should -Not -Thow`. Use `$script:` scope to pass out variables outside the scriptblock.
</blockquote></details>

Maybe we should also move this code to its own Context-block 'When preparing the database for removal' (or someting).


<!-- Sent from Reviewable.io -->

2021-01-11 14:10 UTC, johlju commented
A little more comments since the tests seems to hang. Guessing it is the code under the last review comment that messes things upp. If it fails outside of an It-block maybe Pester hangs.

2021-01-11 17:17 UTC, SphenicPaul reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: all files reviewed, 9 unresolved discussions (waiting on @johlju)

___
*[CHANGELOG.md, line 8 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQldYJH2u7QZxGLuSFQ:-MQmIT7e8gmuzmq5fKKe:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/CHANGELOG.md#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ## [15.0.1] - 2021-01-09
> ```

This section header should be removed, guessing it was wrongly duplicated from below. :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 284 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQljG7L6AAiVBqaO60u:-MQmJ7riETxM0w3GVmD6:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L284)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
> ```

Let's move this into the scriptblock below together with `Open()`. If the type does not exist it will throw also, then we are missing something to run the test.
</blockquote></details>

Done.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 303 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQljWGk1kYpeoZuXe2e:-MQmMOtuE_ySYKYVeGG6:brd70x0) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L303)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                 $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
>                 $sqlCommand = New-Object System.Data.SqlClient.SqlCommand('SELECT DB_NAME() as CurrentDatabaseName', $sqlConnection)
>                 $sqlConnection.Open()
>                 $sqlDataAdapter = New-Object System.Data.SqlClient.SqlDataAdapter $sqlCommand
>                 $sqlDataSet = New-Object System.Data.DataSet
>                 $sqlDataAdapter.Fill($sqlDataSet) | Out-Null
>                 $sqlConnection.Close()
> ```

We should have this in `{ ... } | Should -Not -Thow`. Use `$script:` scope to pass out variables outside the scriptblock.
</blockquote></details>

OK. I've added `$script:CurrentDatabaseName = $null` before and after the assertions (to remove risks around value impacting other current and future tests), and also added the lines you specified into a new scriptblock, whilst asserting there is no exception thrown.

Second assertion now ensures the `$script:CurrentDatabaseName` value assigned within the scriptblock is as expected.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 373 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQljtqWA-zSJ1z3osFL:-MQmJASL68QTRDJHmuDJ:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L373)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
> ```

Let's move this into the scriptblock below together with `Open()`.
</blockquote></details>

Done.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 393 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQljxpM2dD4P735gWnx:-MQmN86wBW6R7aDRDT3w:b-3oekv0) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L393)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                 $sqlConnectionString = 'Data Source={0}\{1};User ID={2};Password={3};Connect Timeout=5;' -f $serverName, $instanceName, $userName, $password # Note: Not providing a database name
>                 $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
>                 $sqlCommand = New-Object System.Data.SqlClient.SqlCommand('SELECT DB_NAME() as CurrentDatabaseName', $sqlConnection)
>                 $sqlConnection.Open()
>                 $sqlDataAdapter = New-Object System.Data.SqlClient.SqlDataAdapter $sqlCommand
>                 $sqlDataSet = New-Object System.Data.DataSet
>                 $sqlDataAdapter.Fill($sqlDataSet) | Out-Null
>                 $sqlConnection.Close()
> ```

We should have this in `{ ... } | Should -Not -Thow`. Use `$script:` scope to pass out variables outside the scriptblock.
</blockquote></details>

As per other comment (re: line 303)...

I've added `$script:CurrentDatabaseName = $null` before and after the assertions (to remove risks around value impacting other current and future tests), and also added the lines you specified into a new scriptblock, whilst asserting there is no exception thrown.

Second assertion now ensures the `$script:CurrentDatabaseName` value assigned within the scriptblock is as expected.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 404 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQlk1J6-X4vYfdaPEKv:-MQmNbbF4haaNB5Vu9YB:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L404)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         # Note that this configuration has already been run within these Integration tests but is
>         # executed once more to reset the password back to the original one provided.
> ```

We should use comment-block when the comment is more than 1 row.

```powershell
<#
    Note that this configuration has already been run within these Integration tests but is
    executed once more to reset the password back to the original one provided.
#>
```
</blockquote></details>

Done.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 450 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQlkVC63YkDkckxAfyf:-MQmJD7w5AbAIHC9jC0j:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L450)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString
> ```

Let's move this into the scriptblock below together with `Open()`.
</blockquote></details>

Done.
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 567 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQlkfBW8yjE-wsDtGdA:-MQmQtDiBj8-44-s2upt:b-sefyn3) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L567)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe we should also move this code to its own Context-block 'When preparing the database for removal' (or someting).
</blockquote></details>

OK. I've moved this functionality into the 'When preparing database, dependencies cleanup' context and separated this out from the original test/context. 

The new functionality is in it's own 'It' block within a `| Should -Not -Throw` assertion (with the exception of the variable assignments in the 'Context', not the 'It', as I wanted to use the `$defaultDbName` variable value in the 'It` name/description).
___
*[tests/Integration/DSC_SqlLogin. [...]

2021-01-11 18:13 UTC, SphenicPaul commented
@johlju - I've now made these revisions. 

Additionally the exception (i.e. `The CHECK_EXPIRATION option cannot be used when CHECK_POLICY is OFF.`) is thrown when the second update is performed on the `DscUser4` login. The integration tests (across a few configurations) do this to the login...

(1) Add the login (in `DSC_SqlLogin_AddLoginDscUser4_Config`)...

```PowerShell

        SqlLogin 'Integration_Test'
        {
            Ensure                         = 'Present'
            Name                           = $Node.DscUser4Name
            LoginType                      = $Node.DscUser4Type
            LoginMustChangePassword        = $false
            LoginPasswordExpirationEnabled = $true
            LoginPasswordPolicyEnforced    = $true

            <...snip...>

        }


```

...then (2) updates the login (i.e. the first update, in `DSC_SqlLogin_UpdateLoginDscUser4_Config`)...

```PowerShell

        SqlLogin 'Integration_Test'
        {
            Ensure                         = 'Present'
            Name                           = $Node.DscUser4Name
            LoginType                      = $Node.DscUser4Type
            LoginMustChangePassword        = $false  # Left the same as this cannot be updated
            LoginPasswordExpirationEnabled = $false
            LoginPasswordPolicyEnforced    = $false

            <...snip...>

        }

```

... then (3) updates the login again (i.e. the second update) by using the configuration used in the original "Add" configuration (in `DSC_SqlLogin_AddLoginDscUser4_Config`)...

```PowerShell

        SqlLogin 'Integration_Test'
        {
            Ensure                         = 'Present'
            Name                           = $Node.DscUser4Name
            LoginType                      = $Node.DscUser4Type
            LoginMustChangePassword        = $false
            LoginPasswordExpirationEnabled = $true
            LoginPasswordPolicyEnforced    = $true

            <...snip...>

        }

```

... so given the exception (`The CHECK_EXPIRATION option cannot be used when CHECK_POLICY is OFF.`), it looked like `Set-TargetResource` (in the `SqlLogin` resource) is setting the `PasswordExpirationEnabled` value before the `PasswordPolicyEnforced` value.

This did work in the original update (i.e. step/test (1)), but the `LoginPasswordPolicyEnforced` (I suspect) defaults to `$true` anyway so, as a result, this add/set doesn't see the exception raised like it does in step/test (3) where step/test (2) had set it to `$false`). 

I've just pushed another change to swap the order in which these are applied within the `SqlLogin` resource (and updated the changelog with that update).

Not sure if there should be any additional logic/condition within the `Set-TargetResource` resource to cater for invalid combinations (e.g. where `LoginPasswordExpirationEnabled = $true and LoginPasswordPolicyEnforced = $false`) or if this should be raised by the SMO library and caught (as it seems to be) by the `SqlLogin` resource, and/or an additional test to ensure that the logic behaves as expected (whichever way that may be). Either way, I suspect it's a quick change/addition to make, if required. Just let me know what you think?

 I'll see how this current build progresses (or doesn't) and will likely make any further changes (if needed) tomorrow.

Let me know if you've any further questions.

2021-01-11 18:24 UTC, johlju requested changes
> Reviewed 3 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: all files reviewed, 1 unresolved discussion (waiting on @SphenicPaul)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 204 at r6](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQmg7cp5_vdUBljiaM4:-MQmg7cp5_vdUBljiaM5:b-mi8zd9) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2b5434b0fd5893fec2e549c155bcac4ba6df95d6/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L204)):*
> ```
> if ( $login.PasswordPolicyEnforced -ne $LoginPasswordPolicyEnforced )
> ```

Can we add a comment saying this must always be changed prior to `PasswordExpirationEnabled`?
___
*[tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, line 567 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQlkfBW8yjE-wsDtGdA:-MQmdcEv5wBTbDMF0SRO:b-8d9phu) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2c54fa2d254ea692f4150f6151cc8c8bb8c494b8/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L567)):*
<details><summary><i>Previously, SphenicPaul (Paul J. Wilcox) wrote…</i></summary><blockquote>

OK. I've moved this functionality into the 'When preparing database, dependencies cleanup' context and separated this out from the original test/context. 

The new functionality is in it's own 'It' block within a `| Should -Not -Throw` assertion (with the exception of the variable assignments in the 'Context', not the 'It', as I wanted to use the `$defaultDbName` variable value in the 'It` name/description).
</blockquote></details>

Just for information, non-blocking. Code inside Context-blocks should be put in a BeforeAll-block, or BeforeEach-block, so that it is faster converting to Pester 5 (that requires that for correct operation). In this case I will fix it when rebasing the Pester 5 PR. 


<!-- Sent from Reviewable.io -->

2021-01-11 18:31 UTC, johlju commented
>Not sure if there should be any additional logic/condition within the Set-TargetResource resource to cater for invalid combinations (e.g. where LoginPasswordExpirationEnabled = $true and LoginPasswordPolicyEnforced = $false) or if this should be raised by the SMO library and caught (as it seems to be) by the SqlLogin resource, and/or an additional test to ensure that the logic behaves as expected (whichever way that may be). Either way, I suspect it's a quick change/addition to make, if required. Just let me know what you think?

I think we let the SMO handle the error if it is wrongly configured. There could to many variations to handle them in the resource.

Also I think the root cause is having these set to default values

```powershell
        [Parameter()]
        [System.Boolean]
        $LoginMustChangePassword = $true,

        [Parameter()]
        [System.Boolean]
        $LoginPasswordExpirationEnabled = $true,

        [Parameter()]
        [System.Boolean]
        $LoginPasswordPolicyEnforced = $true,
```

The parameters should never be enforced unless the are part of the configuration. Currently the resources enforces values even when the usr did not opt-in to enforce them :/ But changing this is a breaking change.

For example, this evaluation:
```powershell
if ( $login.PasswordPolicyEnforced -ne $LoginPasswordPolicyEnforced )
```

should have been:

```powershell
if ( $PSBoundParameters.ContainsKey('PasswordPolicyEnforced') -and $login.PasswordPolicyEnforced -ne $LoginPasswordPolicyEnforced )
```

2021-01-11 18:33 UTC, SphenicPaul reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 204 at r6](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-MQmg7cp5_vdUBljiaM4:-MQmi-NU-pkC2cezw9_e:b-x7xwyq) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/2b5434b0fd5893fec2e549c155bcac4ba6df95d6/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L204)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ( $login.PasswordPolicyEnforced -ne $LoginPasswordPolicyEnforced )
> ```

Can we add a comment saying this must always be changed prior to `PasswordExpirationEnabled`?
</blockquote></details>

OK. Done. I've added the equivalent comments to both sections of code (in case these ever get split up at any point)


<!-- Sent from Reviewable.io -->

2021-01-11 18:34 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-:-MQmiXbZ79QgJxURsV8W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-11 18:34 UTC, SphenicPaul commented
OK. All that makes sense, and latest revisions made.

We'll see how the build goes this time.

2021-01-11 18:35 UTC, johlju commented
If the tests pass lefts merge this. 🙂  I can create an issue to track the breaking code change.

2021-01-11 18:46 UTC, SphenicPaul commented
Also, while I think about (and for the record) the tests are specifying the input/properly/parameter values anyway so I’d expect the defaults set in the resource parameters would be ignored in these cases.

I guess the point/issue you raise is still a valid one though and could still occur if no parameter values were provided.

2021-01-11 19:02 UTC, johlju commented
It failed the same way, see from line 1916: https://dev.azure.com/dsccommunity/SqlServerDsc/_build/results?buildId=3619&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e&j=8772ad65-1070-5fc2-976b-5360a2c9118a

2021-01-11 19:03 UTC, johlju commented
> I guess the point/issue you raise is still a valid one though and could still occur if no parameter values were provided.

Yes, it only occurs for already present SQL logins if no value is provided.

2021-01-11 19:31 UTC, SphenicPaul commented
It looks like the latest error is now from a different test - it's now the test that does the first update (when it is setting `LoginPasswordPolicyEnforced` from `$true` to `$false`... whilst `LoginPasswordExpirationEnabled` is still `$true`) - It's hitting the error updating the properties in the opposite direction.

I've updated the function once more, now to update both `LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced` within the same update passed to `Update-SQLServerLogin`.

I'll try and check back later.

2021-01-11 19:53 UTC, johlju commented
Looks like SqlLogin passed now, though it seemed to fail on SqlSetup (intermittent error) so I kick off the tests again tomorrow. Can't do it until all tests finishes and unit tests run for 3 hours.

2021-01-12 10:26 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1652#-:-MQq7SuPD_D-uwuyObk-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SphenicPaul)



<!-- Sent from Reviewable.io -->

2021-01-12 10:30 UTC, merged

2021-01-12 10:32 UTC, johlju commented
@SphenicPaul merged this now! Thank you, awesome work on this! 😃

2021-01-12 12:30 UTC, SphenicPaul commented
No worries...Although I do suspect the changlog might still need amending slightly to reflect the final change I made to bring the updates of both the SqlLogin properties into one update.

I suspect the changelog still refers to the ordering change (which is probably less relevant now as both properties now get updated together).

Let me know if you think it needs amending or not. I can raise a quick PR for that later on if needed.

2021-01-12 12:40 UTC, johlju commented
@SphenicPaul Please update the change log appropriately. 🙂

2021-01-12 13:50 UTC, SphenicPaul commented
OK. Raised #1670 to resolve this.