[#1669] SqlLogin: LoginMustChangePassword, LoginPasswordExpirationEna…
dsccommunity/SqlServerDsc pull request #1696
Opened 2021-03-10 18:17 UTC by bozho

`LoginMustChangePassword`, `LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced` parameters no longer enforce default values.

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [x] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2021-03-30 08:38 UTC, johlju commented
This is still on the todo list. Just a lot of work getting DnsServerDsc out the door. I will swing back here soon. I will try to get to the backlog of all reviews during Easter. Same for the new PR.

2021-03-30 11:45 UTC, bozho commented
No rush - I create our own "inter-version" builds for modules I've submitted PRs for and host them on a private PS module repo, so I can keep working on my stuff :-)

2021-05-04 04:20 UTC, johlju reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 1 unresolved discussion (waiting on @bozho)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MZpa_Oi6SSpXpMDjlW7:-MZpa_Oi6SSpXpMDjlW8:bwxvv9n) (no related file):*
It seems with this change we are missing unit tests, would you mind add unit tests to cover the code path that are not tested? :slightly_smiling_face: 

---


<!-- Sent from Reviewable.io -->

2021-05-05 14:52 UTC, bozho commented
@johlju Ok, I think I've added missing code coverage tests. I do have a few questions.

I had to add a new `Connect-SQL` mock (`$mockConnectSQL_SQLLogin_PasswordFlagsFalse`), which also made me realise that mocking a command is not scoped inside each `It` block - I had to "reset" `Connect-SQL` mock on line `752` in `DSC_SqlLogin.Tests.ps1`.

I also think that mock on line 808 is wrong:
```
Mock -CommandName Connect-SQL -MockWith { throw } -Verifiable -ParameterFilter { $SetupCredential }
```

`ParameterFilter` will always return `$false`, since `$SetupCredential` variable is not declared in `DSC_SqlLogin.Tests.ps1`.

Would it be a good idea to add an explicit `Mock` for `Connect-SQL` inside each `It` block for `Test-TargetResource` context, like it's already done for `Set-TargetResource` context?

2021-05-06 07:32 UTC, bozho commented
It seems that SQL2017 integration test failed because there was a problem with the test host, not because tests failed.

2021-06-05 14:57 UTC, johlju commented
/AzurePipelines run

2021-09-18 14:55 UTC, johlju commented
I have this on the todo - it was a crazy week at work, but this is next in the todo.

2021-09-26 10:04 UTC, johlju commented
> I also think that mock on line 808 is wrong ... ParameterFilter will always return $false, since $SetupCredential variable is not declared in DSC_SqlLogin.Tests.ps1.

I variable is using the parameter from the function Connect-Sql - it evaluates if SetupCredential is set. But `$null -ne $SetupCredential` or `$PSBoundParameters.ContainsKey('SetupCredential')` would have been more easy to read.

> Would it be a good idea to add an explicit Mock for Connect-SQL inside each It block for Test-TargetResource context, like it's already done for Set-TargetResource context?

The test need to be refactored anyway for Pester 5, so lets leave it as-is.

2021-09-26 10:30 UTC, johlju requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 3 unresolved discussions (waiting on @bozho)

___
*[CHANGELOG.md, line 12 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MkWdgJUCIA_H_EXe5tb:-MkWdgJUCIA_H_EXe5tc:b-3s14zn) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/86ddb97a0cac3f7c9a2dbbed384c685b1f6654e8/CHANGELOG.md#L12)):*
> ```
> [issue #1669](https://github.com/dsccommunity/SqlServerDsc/issues/1669).
> ```

Lets add parenthesis around this to make it like the others `([issue #1669](https://github.com/dsccommunity/SqlServerDsc/issues/1669)).`
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 209 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MkWaiwIBv3RkVzhbX8F:-MkWaiwIBv3RkVzhbX8G:b-lyth9u) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/86ddb97a0cac3f7c9a2dbbed384c685b1f6654e8/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L209)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>                         Write-Verbose -Message (
>                             $script:localizedData.SetPasswordPolicyEnforced -f $LoginPasswordPolicyEnforced, $Name, $ServerName, $InstanceName
>                         )
>                         Write-Verbose -Message (
>                             $script:localizedData.SetPasswordExpirationEnabled -f $LoginPasswordExpirationEnabled, $Name, $ServerName, $InstanceName
>                         )
> ```
</details>


These verbose statements should be moved into each if-block below.
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 215 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MkWaPuoBJkE1yoNo7ms:-MkWaPuoBJkE1yoNo7mt:b-sywej0) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/86ddb97a0cac3f7c9a2dbbed384c685b1f6654e8/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L215)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>                         if ( $PSBoundParameters.ContainsKey('LoginPasswordPolicyEnforced') )
>                         {
>                             $login.PasswordPolicyEnforced = $LoginPasswordPolicyEnforced
>                         }
> 
>                         if ( $PSBoundParameters.ContainsKey('LoginPasswordExpirationEnabled') )
>                         {
>                             $login.PasswordExpirationEnabled = $LoginPasswordExpirationEnabled
>                         }
> ```
</details>


Looking at comment on line 197, please add an integration tests that verifies this do work
See example integration test config: https://github.com/dsccommunity/SqlServerDsc/blob/8aa0a4c8c9c61881851f756fb92659812187d935/tests/Integration/DSC_SqlLogin.config.ps1#L207


<!-- Sent from Reviewable.io -->

2021-09-28 08:03 UTC, bozho reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 3 unresolved discussions (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MZpa_Oi6SSpXpMDjlW7:-MkfQQujEfhu1v8hNZ6F:b-qx0b4u) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

It seems with this change we are missing unit tests, would you mind add unit tests to cover the code path that are not tested? :slightly_smiling_face: 
</blockquote></details>

I've only seen this comment now. I've added unit tests back in May, hope they're good enough.

---
___
*[CHANGELOG.md, line 12 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MkWdgJUCIA_H_EXe5tb:-MkfM4oI8AphKrbndiG6:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/86ddb97a0cac3f7c9a2dbbed384c685b1f6654e8/CHANGELOG.md#L12)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [issue #1669](https://github.com/dsccommunity/SqlServerDsc/issues/1669).
> ```

Lets add parenthesis around this to make it like the others `([issue #1669](https://github.com/dsccommunity/SqlServerDsc/issues/1669)).`
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 209 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MkWaiwIBv3RkVzhbX8F:-MkfMlF10f0-5TRdMYyj:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/86ddb97a0cac3f7c9a2dbbed384c685b1f6654e8/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L209)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                         Write-Verbose -Message (
>                             $script:localizedData.SetPasswordPolicyEnforced -f $LoginPasswordPolicyEnforced, $Name, $ServerName, $InstanceName
>                         )
>                         Write-Verbose -Message (
>                             $script:localizedData.SetPasswordExpirationEnabled -f $LoginPasswordExpirationEnabled, $Name, $ServerName, $InstanceName
>                         )
> ```

These verbose statements should be moved into each if-block below.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 215 at r4](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MkWaPuoBJkE1yoNo7ms:-MkfQ11nCiYMX38wT62x:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/86ddb97a0cac3f7c9a2dbbed384c685b1f6654e8/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L215)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                         if ( $PSBoundParameters.ContainsKey('LoginPasswordPolicyEnforced') )
>                         {
>                             $login.PasswordPolicyEnforced = $LoginPasswordPolicyEnforced
>                         }
> 
>                         if ( $PSBoundParameters.ContainsKey('LoginPasswordExpirationEnabled') )
>                         {
>                             $login.PasswordExpirationEnabled = $LoginPasswordExpirationEnabled
>                         }
> ```

Looking at comment on line 197, please add an integration tests that verifies this do work
See example integration test config: https://github.com/dsccommunity/SqlServerDsc/blob/8aa0a4c8c9c61881851f756fb92659812187d935/tests/Integration/DSC_SqlLogin.config.ps1#L207
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-02 16:22 UTC, johlju requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 4 unresolved discussions (waiting on @bozho)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 214 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0lYfbD9qEK17SqcKs:-Ml0lYfbD9qEK17SqcKt:bv981u4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L214)):*
> ```
>                             Write-Verbose -Message (
>                                 $script:localizedData.SetPasswordExpirationEnabled -f $LoginPasswordExpirationEnabled, $Name, $ServerName, $InstanceName
>                             )
> ```

Sorry, my English wasn't clear enough. I meant that the corresponding verbose message should go into the respective if-blocks.
We can remove this verbose message here.
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 222 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0m5sIB3yuL42sDILi:-Ml0m5sIB3yuL42sDILj:b-fhs2b4) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L222)):*
> ```
>                             Write-Verbose -Message (
>                                 $script:localizedData.SetPasswordPolicyEnforced -f $LoginPasswordPolicyEnforced, $Name, $ServerName, $InstanceName
>                             )
> ```

We can remove this verbose message here.
___
*[tests/Integration/DSC_SqlLogin.config.ps1, line 317 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0nj04Es6xvOlI0mqV:-Ml0nj04Es6xvOlI0mqW:b70lpsf) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/tests/Integration/DSC_SqlLogin.config.ps1#L317)):*
> ```
> Configuration DSC_SqlLogin_UpdateLoginDscUser4_Config_LoginPasswordExpirationEnabled
> ```

Please add a section in the integration test as well, see this: https://github.com/dsccommunity/SqlServerDsc/blob/8aa0a4c8c9c61881851f756fb92659812187d935/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L430-L483

You can copy the marked code and add a test after the one that is marked (marked in the link above).
___
*[tests/Integration/DSC_SqlLogin.config.ps1, line 343 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0o6375Id3JzfnPJ7B:-Ml0o6375Id3JzfnPJ7C:b-6gwy4g) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/tests/Integration/DSC_SqlLogin.config.ps1#L343)):*
> ```
> Configuration DSC_SqlLogin_UpdateLoginDscUser4_Config_LoginPasswordPolicyEnforced
> ```

Same as the previous comment.


<!-- Sent from Reviewable.io -->

2021-10-04 09:52 UTC, bozho reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 4 unresolved discussions (waiting on @bozho and @johlju)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 214 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0lYfbD9qEK17SqcKs:-Ml9ejX6DYliDc269BIZ:bo0b1o6) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L214)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                             Write-Verbose -Message (
>                                 $script:localizedData.SetPasswordExpirationEnabled -f $LoginPasswordExpirationEnabled, $Name, $ServerName, $InstanceName
>                             )
> ```

Sorry, my English wasn't clear enough. I meant that the corresponding verbose message should go into the respective if-blocks.
We can remove this verbose message here.
</blockquote></details>

Oh, no, your English was clear. I copy/pasted both messages into both blocks and meant to delete the unrelated one in each, got distracted and then committed like this, sorry :-)
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 222 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0m5sIB3yuL42sDILi:-Ml9fBab8PeBceP1b_XK:bz616) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L222)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>                             Write-Verbose -Message (
>                                 $script:localizedData.SetPasswordPolicyEnforced -f $LoginPasswordPolicyEnforced, $Name, $ServerName, $InstanceName
>                             )
> ```

We can remove this verbose message here.
</blockquote></details>

Same here :)


<!-- Sent from Reviewable.io -->

2021-10-04 09:52 UTC, bozho reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[tests/Integration/DSC_SqlLogin.config.ps1, line 317 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0nj04Es6xvOlI0mqV:-Ml9hvk_5EV1W7js84Vr:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/tests/Integration/DSC_SqlLogin.config.ps1#L317)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Configuration DSC_SqlLogin_UpdateLoginDscUser4_Config_LoginPasswordExpirationEnabled
> ```

Please add a section in the integration test as well, see this: https://github.com/dsccommunity/SqlServerDsc/blob/8aa0a4c8c9c61881851f756fb92659812187d935/tests/Integration/DSC_SqlLogin.Integration.Tests.ps1#L430-L483

You can copy the marked code and add a test after the one that is marked (marked in the link above).
</blockquote></details>

Done.
___
*[tests/Integration/DSC_SqlLogin.config.ps1, line 343 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0o6375Id3JzfnPJ7B:-Ml9hw2P6QEudSQq7llH:b-896fix) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/tests/Integration/DSC_SqlLogin.config.ps1#L343)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Configuration DSC_SqlLogin_UpdateLoginDscUser4_Config_LoginPasswordPolicyEnforced
> ```

Same as the previous comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-04 09:52 UTC, bozho reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 214 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0lYfbD9qEK17SqcKs:-Ml9hy0v2TkWk_1Zt8GN:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L214)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

Oh, no, your English was clear. I copy/pasted both messages into both blocks and meant to delete the unrelated one in each, got distracted and then committed like this, sorry :-)
</blockquote></details>

Done
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 222 at r5](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-Ml0m5sIB3yuL42sDILi:-Ml9i-Fi5xhnuyojNdSR:bb6un1j) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/302e3ce31ca7b3eb19bc54a493b8749333b049df/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L222)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

Same here :)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-10-18 16:18 UTC, johlju commented
I need to have time to look over you comment, it sounds like you think we already test for the scenario I was looking for.

2022-03-13 09:42 UTC, johlju requested changes
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 2 unresolved discussions (waiting on @bozho)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 300 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-My1bciP169--VNkSvWY:-My1bciP169--VNkSvWZ:b-e0z7mp) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L300)):*
> ```PowerShell
> 
>                         $login.PasswordPolicyEnforced = $LoginPasswordPolicyEnforced
>                         $login.PasswordExpirationEnabled = $LoginPasswordExpirationEnabled
> ```

Here we still enforce the values (when the login does not exists).



_Code quote:_
```PowerShell
                        $login.PasswordPolicyEnforced = $LoginPasswordPolicyEnforced
                        $login.PasswordExpirationEnabled = $LoginPasswordExpirationEnabled
                        if ( $LoginMustChangePassword )
                        {
                            $LoginCreateOptions = [Microsoft.SqlServer.Management.Smo.LoginCreateOptions]::MustChange
                        }
                        else
                        {
                            $LoginCreateOptions = [Microsoft.SqlServer.Management.Smo.LoginCreateOptions]::None
                        }
```
___
*[tests/Integration/DSC_SqlLogin.config.ps1, line 218 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-My1db6c4t69I7HaZdFN:-My1db6c4t69I7HaZdFO:b-a0fl9u) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/tests/Integration/DSC_SqlLogin.config.ps1#L218)):*
> ```PowerShell
>             Name                           = $Node.DscUser4Name
>             LoginType                      = $Node.DscUser4Type
>             LoginMustChangePassword        = $false
> ```

As per other comment, when we no longer have these values to $true as the default value, then I think we need to add another integration tests that adds another SQL login where these values are not set to verify it works not specifying these values.



_Code quote:_
```PowerShell
            LoginMustChangePassword        = $false
            LoginPasswordExpirationEnabled = $true
            LoginPasswordPolicyEnforced    = $true
```


<!-- Sent from Reviewable.io -->

2022-03-13 09:46 UTC, johlju commented
@bozho sorry to taking so longer to get back to this - but now I'm on it. We just need to fix these to last review comment and then I will merge this one. Let me know if you have time to work on this. Again, sorry for the delay.

2022-03-13 09:57 UTC, johlju commented
@bozho just make sure the unit tests passes (so I can merge) - don't bother with adding tests for any new code paths. I'm currently refactoring the unit tests in another PR for Pester 5 so I have to "rewrite" most tests anyway.

2022-03-15 11:27 UTC, bozho reviewed
No worries, I'll just need to refresh my memory a bit :-) 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-:-MyCJF_D23g2NtgwT_0h:b3u2v0y)* status: all files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 204 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MyCJLuS2lmDzPr6XlFs:-MyCJLuS2lmDzPr6XlFt:b-z02m6v) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L204)):*
> ```PowerShell
>                     }
> 
>                     # `PasswordPolicyEnforced and `PasswordExpirationEnabled` must be updated together (if one or both are not in the desired state)
> ```

@johlju Re-reading this comment, it doesn't match with what `if` below checks.

If `PasswordPolicyEnforced` and `PasswordExpirationEnabled` must always be set/updated together, shouldn't the `if` check that either both or neither of these parameters are specified and then set/update each based on their current settings?
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 300 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-My1bciP169--VNkSvWY:-MyCK3aQ7W9_fQ65HuxG:b646oh7) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L300)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Here we still enforce the values (when the login does not exists).
</blockquote></details>

Whoops, missed that one. Let's sort out my comment for line `204` above, then we copy the solution here.
___
*[tests/Integration/DSC_SqlLogin.config.ps1, line 218 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-My1db6c4t69I7HaZdFN:-MyCKDcUCQHEohFQLhIp:b8f2zgk) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/tests/Integration/DSC_SqlLogin.config.ps1#L218)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

As per other comment, when we no longer have these values to $true as the default value, then I think we need to add another integration tests that adds another SQL login where these values are not set to verify it works not specifying these values.
</blockquote></details>

Ok. Should I do anything here, then?


<!-- Sent from Reviewable.io -->

2022-03-15 15:48 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 3 unresolved discussions (waiting on @bozho and @johlju)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 204 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MyCJLuS2lmDzPr6XlFs:-MyDCtaY5eUf6-N5Gya_:b-ncpv6v) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L204)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

@johlju Re-reading this comment, it doesn't match with what `if` below checks.

If `PasswordPolicyEnforced` and `PasswordExpirationEnabled` must always be set/updated together, shouldn't the `if` check that either both or neither of these parameters are specified and then set/update each based on their current settings?

</blockquote></details>

This PR proposed to change so these two properties can be set individually. You created integration tests to verify that these properties could be set individually, once those new integration tests passes then this comment can be removed as it is wrong.
___
*[tests/Integration/DSC_SqlLogin.config.ps1, line 218 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-My1db6c4t69I7HaZdFN:-MyDEJozEnad42aU3Lmv:b7xgjoy) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/tests/Integration/DSC_SqlLogin.config.ps1#L218)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

Ok. Should I do anything here, then?
</blockquote></details>

We need another test after you resolve one of the other comments. 

As per current code in this PR when a SQL Login is created the two properties `LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced` are always set to `$false` for a new SQL login.

When you resolve the code at line 300 in DSC_SqlLogin.psm1 (see other comment), then we need another integration tests that adds a new SQL login and _do not_ pass the parameters `LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced` to make sure we can create a SQL login without those properties. 


<!-- Sent from Reviewable.io -->

2022-03-17 09:05 UTC, bozho reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 3 unresolved discussions (waiting on @bozho and @johlju)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 204 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MyCJLuS2lmDzPr6XlFs:-MyM0tSg7SVlLXDmvBMP:besxpe) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L204)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This PR proposed to change so these two properties can be set individually. You created integration tests to verify that these properties could be set individually, once those new integration tests passes then this comment can be removed as it is wrong.
</blockquote></details>

Ah, I understand what the comment is trying to say here: if either or both parameters are specified and either is not in desired state, we need to use `Update-SQLServerLogin` to update login data, not that both parameters have to be specified.

The `if` block staring on line `205` allows us to avoid calling `Update-SQLServerLogin` twice if both parameters have changed (i.e. calling it for each change).

I'll rewrite the comment to make it understandable on a first read :-)
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 300 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-My1bciP169--VNkSvWY:-MyM1j662WHfTdxwP51Y:b-85bq9h) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L300)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

Whoops, missed that one. Let's sort out my comment for line `204` above, then we copy the solution here.
</blockquote></details>

@johlju I think this is fine: we are creating a new SQL login here and if `$LoginPasswordPolicyEnforced` or `$LoginPasswordExpirationEnabled` are not specified, they'll be `$false`, which is the new default (changes to lines `166`, `170` and `174`).

I did a quick manual test. Creating a new `Microsoft.SqlServer.Management.Smo.Login` instance, those properties are `$null`. If I set the login type to `SqlLogin` and execute `$login.Create($password)`, the new login is created with `MustChangePassword` set to `$false`, `PasswordExpirationEnabled` set to `$false` and `PasswordPolicyEnforced` set to `$true` - should this combination be the new default?


<!-- Sent from Reviewable.io -->

2022-03-18 13:50 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: all files reviewed, 3 unresolved discussions (waiting on @bozho)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 204 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-MyCJLuS2lmDzPr6XlFs:-MySFneo9nyiNbQHNxob:bt1nsnd) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L204)):*
> if either or both parameters are specified and either is not in desired state, we need to use Update-SQLServerLogin to update login data, not that both parameters have to be specified.

Exactly :slightly_smiling_face: 

> I'll rewrite the comment to make it understandable on a first read :-)

Sounds good.
___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 300 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-My1bciP169--VNkSvWY:-MySGUvo81Iutp9ipdPV:b-9czmdf) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L300)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

@johlju I think this is fine: we are creating a new SQL login here and if `$LoginPasswordPolicyEnforced` or `$LoginPasswordExpirationEnabled` are not specified, they'll be `$false`, which is the new default (changes to lines `166`, `170` and `174`).

I did a quick manual test. Creating a new `Microsoft.SqlServer.Management.Smo.Login` instance, those properties are `$null`. If I set the login type to `SqlLogin` and execute `$login.Create($password)`, the new login is created with `MustChangePassword` set to `$false`, `PasswordExpirationEnabled` set to `$false` and `PasswordPolicyEnforced` set to `$true` - should this combination be the new default?

</blockquote></details>

Either that, or we just revert to `$true` on the parameters, and keep using that as the default. Then there is one less breaking change in this PR. :thinking: It will also keep the login to the most secure (?) and the user must set things to `$false` to be "less" secure.

But I'm also good with what you suggest above to, keeping it the same as SQL Server does. 

I let you decide, I'm good with whatever you decide. :) 


<!-- Sent from Reviewable.io -->

2022-03-25 12:56 UTC, bozho reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, line 300 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-My1bciP169--VNkSvWY:-Mz-l7_t8IvdP2uljIYc:b-ox18hf) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1#L300)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Either that, or we just revert to `$true` on the parameters, and keep using that as the default. Then there is one less breaking change in this PR. :thinking: It will also keep the login to the most secure (?) and the user must set things to `$false` to be "less" secure.

But I'm also good with what you suggest above to, keeping it the same as SQL Server does. 

I let you decide, I'm good with whatever you decide. :) 
</blockquote></details>

I gave this some thought and I think we should leave it like this. 

`Microsoft.SqlServer.Management.Smo.Login` defaults seem sane for automation purposes: it's reasonable to assume the password will be a strong, auto-generated one, so having `PasswordPolicyEnforced` as `true` by default is fine.

Having `LoginMustChangePassword` as `true` by default would complicate automated deployments and `PasswordExpirationEnabled` being `true` by default might also be a bit of a faff, especially if the login is used only "internally" by deployed system. One would expect that a system will have a general password/key rotation policy for all components :-)
___
*[tests/Integration/DSC_SqlLogin.config.ps1, line 218 at r8](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-My1db6c4t69I7HaZdFN:-Mz-n8qW7viW0hiFzEGI:b-78esgh) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/3067b5012afede95a31f9858741ea546300e0262/tests/Integration/DSC_SqlLogin.config.ps1#L218)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We need another test after you resolve one of the other comments. 

As per current code in this PR when a SQL Login is created the two properties `LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced` are always set to `$false` for a new SQL login.

When you resolve the code at line 300 in DSC_SqlLogin.psm1 (see other comment), then we need another integration tests that adds a new SQL login and _do not_ pass the parameters `LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced` to make sure we can create a SQL login without those properties. 
</blockquote></details>

ah, got it.


<!-- Sent from Reviewable.io -->

2022-03-25 14:13 UTC, bozho commented
@johlju Eh, we have a bit of a mess in `...LoginDscUser4...` integration tests...

First, we apply `DSC_SqlLogin_AddLoginDscUser4_Config` configuration. That one has both password flags (`LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced`) set to `$true`.

Then, we apply `DSC_SqlLogin_UpdateLoginDscUser4_Config`, which sets both password flag to `$false` (in addition to changing the password).

Then, we apply `DSC_SqlLogin_AddLoginDscUser4_Config` again, which resets the password, as well as both password flags back to `$true`.

Those three are all pre-existing test code (when all three password params had defaults as `$true`).

The new tests are:
Apply `DSC_SqlLogin_UpdateLoginDscUser4_Config_LoginPasswordExpirationEnabled`, which only explicitly sets `LoginPasswordExpirationEnabled` to `$true`. The `Get-DscConfiguration` test currently fails here because it tests that `LoginPasswordPolicyEnforced` is `$false`, but it's not because it was reset by the second run of `DSC_SqlLogin_AddLoginDscUser4_Config` configuration. I could change the expectation there to `$true`, but that makes the test a bit pointless - we've just reset SQL login with `DSC_SqlLogin_AddLoginDscUser4_Config` and we're setting `LoginPasswordExpirationEnabled` using `DSC_SqlLogin_UpdateLoginDscUser4_Config_LoginPasswordExpirationEnabled` to `$true`, but the flag is already in that state.

Furthermore, I've done some manual testing and setting `LoginPasswordExpirationEnabled` to `$true` and keeping `LoginPasswordPolicyEnforced`=`$false` will cause `[Microsoft.SqlServer.Management.Smo.Login]::Alter()` to fail, and the resource code currently does not check for that.

I think the correct order of `LoginDscUser4` tests should be:
`DSC_SqlLogin_AddLoginDscUser4_Config` - `LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced` set to `$true`
`DSC_SqlLogin_UpdateLoginDscUser4_Config` which will set both password flags to `$false`.
`DSC_SqlLogin_UpdateLoginDscUser4_Config_LoginPasswordPolicyEnforced` which would only set `LoginPasswordPolicyEnforced` to `$true`
`DSC_SqlLogin_UpdateLoginDscUser4_Config_LoginPasswordExpirationEnabled` which would only set `LoginPasswordExpirationEnabled` to `$true`.
`DSC_SqlLogin_AddLoginDscUser4_Config` to reset the password.

We should also add either parameter check for `LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced` to resource code to disallow the invalid `$true`/`$false` combo.

A separate `...LoginDscUser5...` test(s) would then test with new defaults (`$false`).

2022-03-27 10:26 UTC, johlju commented
I agree with all the above. Do as suggested. Though we could skip the extra parameter check for now and that in another PR, just to get this PR through. 🙂

2022-03-28 10:37 UTC, johlju reviewed
Waiting for the tests to pass. 

> Reviewed 2 of 3 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696#-:-MZpZ1RzA_ZaR9sMTSo8:b2xhiln)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bozho)



<!-- Sent from Reviewable.io -->

2022-03-28 12:50 UTC, johlju commented
I will kick off the integration tests that failed once all tests has finished running.

2022-03-28 18:55 UTC, merged

2022-03-28 18:56 UTC, johlju commented
Thank you @bozho!