SqlAgDatabase: Fixes Issue #1743
dsccommunity/SqlServerDsc pull request #1744
Opened 2022-04-19 12:46 UTC by dlenkov

#### Pull Request (PR) description

- Changes to SqlAGDatabase
  - Added StatementTimeout parameter with value 0 (no timeout) to Connect-SQL invocation in Set-TargetResource function to fix Issue#1743
    This prevents timeout during backup operation on secondary.

#### This Pull Request (PR) fixes the following issues

- Fixes #1743

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ ] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2022-04-20 14:04 UTC, johlju requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1744)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dlenkov and @johlju)

___
*[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 207 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1744#-N06HSUU2Z5D8ycb_ezU:-N06HSUVDEhsjxNL2WFM:b-156tf) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/48882d3471b32b7488fae3f1acc9910d91061b2b/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L207)):*
> ```PowerShell
> 
>     # Connect to the defined instance
>     $serverObject = Connect-SQL -ServerName $ServerName -InstanceName $InstanceName -StatementTimeout 0
> ```

See comment https://github.com/dsccommunity/SqlServerDsc/issues/1743#issuecomment-1103970490.


<!-- Sent from Reviewable.io -->

2022-04-26 11:19 UTC, dlenkov commented
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1744)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dlenkov and @johlju)
> 
> _[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 207 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1744#-N06HSUU2Z5D8ycb_ezU:-N06HSUVDEhsjxNL2WFM:b-156tf) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/48882d3471b32b7488fae3f1acc9910d91061b2b/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L207)):_
> 
> > ```powershell
> >     # Connect to the defined instance
> >     $serverObject = Connect-SQL -ServerName $ServerName -InstanceName $InstanceName -StatementTimeout 0
> > ```
> 
> See comment [#1743 (comment)](https://github.com/dsccommunity/SqlServerDsc/issues/1743#issuecomment-1103970490).

Done.

2022-04-26 11:20 UTC, dlenkov commented
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1744)_ status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dlenkov and @johlju)
> 
> _[source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, line 594 at r1](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1744#-N06Jwo_-SVodtOC14kQ:-N06Jwo_-SVodtOC14kR:bvdgl8o) ([raw file](https://github.com/dsccommunity/sqlserverdsc/blob/48882d3471b32b7488fae3f1acc9910d91061b2b/source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1#L594)):_
> 
> > ```powershell
> >                         {
> >                             # Restore the database
> >                             Invoke-Query -ServerName $currentAvailabilityGroupReplicaServerObject.NetName -InstanceName $currentAvailabilityGroupReplicaServerObject.ServiceName -Database master -Query $restoreDatabaseQueryString -StatementTimeout 0
> > ```
> 
> These two lines should also change to using the new parameter instead of hardcoding it to `0`.
> 
> _Code quote:_
> 
> ```powershell
>                             Invoke-Query -ServerName $currentAvailabilityGroupReplicaServerObject.NetName -InstanceName $currentAvailabilityGroupReplicaServerObject.ServiceName -Database master -Query $restoreDatabaseQueryString -StatementTimeout 0
>                             Invoke-Query -ServerName $currentAvailabilityGroupReplicaServerObject.NetName -InstanceName $currentAvailabilityGroupReplicaServerObject.ServiceName -Database master -Query $restoreLogQueryString -StatementTimeout 0
> ```

Done.

2022-04-26 16:55 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1744#-:-N0an4DKBvG0FB5-4MNv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dlenkov)



<!-- Sent from Reviewable.io -->

2022-04-26 16:58 UTC, johlju commented
@dlenkov thank you for this, I kicked off the test that failed and will merge as soon as it passes. 🙂

2022-04-26 17:51 UTC, merged