Connect-SQL: Add Wait for Online SMO Status
dsccommunity/SqlServerDsc pull request #1916
Opened 2023-04-18 04:50 UTC by Kreby

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues
- Fixes #1816 

#### Task list
- [ X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [ ] Comment-based help updated, including parameter descriptions.
- [ X] Localization strings updated.
- [ ] Examples updated.
- [ X] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ X] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2023-04-18 05:04 UTC, Kreby commented
@johlju I had this working, passing all the tests from the pipeline, but then when I ran my actual test deployments I was seeing weird issues.  I don't think they are related to this change however.  I've submitted as a draft right now until I can do some further testing tomorrow.  At least you can take a look at it in the mean time.

Would you be able to provide me the non English localization of the string I added?

I'm not sure if any additional or modified unit/integration tests are needed based on what was added.  Let me know if you think otherwise.

2023-04-20 12:47 UTC, johlju requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916)* status: all files reviewed, 4 unresolved discussions (waiting on @Kreby)

___
*[`source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1` line 584 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTe2tb96_mQqomgjuu:-NTTe2tb96_mQqomgjuv:b8n8jyj) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1#L584)):*
> ```PowerShell
> 
>             Write-Verbose -Message (
>                 $script:localizedData.WaitForDatabaseEngineInstanceStatus -f $instanceStatus, $onlineStatus
> ```

Maybe we should output this once after like 20 seconds? Other wise it could theoretically a lot of them during the $StatementTimeout.



_Code quote:_
```PowerShell
            Write-Verbose -Message (
                $script:localizedData.WaitForDatabaseEngineInstanceStatus -f $instanceStatus, $onlineStatus
            ) -Verbose
```
___
*[`source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1` line 591 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTfrImDahorOhyqYvn:-NTTfrImDahorOhyqYvo:b-6mdvta) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1#L591)):*
> ```PowerShell
>         } while ($connectTimer.Elapsed.TotalSeconds -lt $StatementTimeout)
> 
>         $connectTimer.Stop()
> ```

Think we should stop this down in `finally` so that we don't keep counting if an error occurs.



_Code quote:_
```PowerShell
$connectTimer.Stop()
```
___
*[`source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1` line 47 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTeORw2iRWCYdLk2xq:-NTTeORw2iRWCYdLk2xr:b-bw3h4l) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1#L47)):*
> ```PowerShell
>     FailedToObtainServerInstance = Failed to obtain a SQL Server instance with name '{0}' on server '{1}'. Ensure the SQL Server instance exists on the server and that the 'SQLServer' module references a version of the 'Microsoft.SqlServer.Management.Smo.Wmi' library that supports the version of the SQL Server instance. (SQLCOMMON0070)
>     DatabaseEngineInstanceNotOnline = The SQL instance '{0}' was expected to have the status 'Online', but had status '{1}'. (SQLCOMMON0071)
>     WaitForDatabaseEngineInstanceStatus = The SQL instance status is '{0}' waiting for '{1}'.  (SQLCOMMON0072)"
> ```

Suggest we also mention that we are "...waiting for x number of seconds". See also other comment of just output it once after like 20 seconds. 



_Code quote:_
```PowerShell
WaitForDatabaseEngineInstanceStatus = The SQL instance status is '{0}' waiting for '{1}'.  (SQLCOMMON0072)"
```
___
*[`source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1` line 53 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTejpm7xZeH3wC-dF9:-NTTejpm7xZeH3wC-dFA:b-cq1lz5) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1#L53)):*
> ```PowerShell
>     FailedToObtainServerInstance = Failed to obtain a SQL Server instance with name '{0}' on server '{1}'. Ensure the SQL Server instance exists on the server and that the 'SQLServer' module references a version of the 'Microsoft.SqlServer.Management.Smo.Wmi' library that supports the version of the SQL Server instance. (SQLCOMMON0070)
>     DatabaseEngineInstanceNotOnline = The SQL instance '{0}' was expected to have the status 'Online', but had status '{1}'. (SQLCOMMON0071)
>     WaitForDatabaseEngineInstanceStatus = The SQL instance status is '{0}' waiting for '{1}'.  (SQLCOMMON0072)"
> ```

Same change here as previous comment.



_Code quote:_
```PowerShell
WaitForDatabaseEngineInstanceStatus = The SQL instance status is '{0}' waiting for '{1}'.  (SQLCOMMON0072)"
```


<!-- Sent from Reviewable.io -->

2023-04-20 12:49 UTC, johlju commented
> I'm not sure if any additional or modified unit/integration tests are needed based on what was added. Let me know if you think otherwise.

It is possible but complicated to write unit test to test this change. Not sure it is worth the effort so did not comment on it. 🙂  Just a few other comments.

2023-04-20 14:06 UTC, Kreby reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[`source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1` line 584 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTe2tb96_mQqomgjuu:-NTTvVpx53a6cLTkt2Y1:b-aon4k7) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1#L584)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe we should output this once after like 20 seconds? Other wise it could theoretically a lot of them during the $StatementTimeout.
</blockquote></details>

Theoretically yes, however the loop only executes after the blocking ```Connect()``` was successful.  So this loop could run multiple times but from all of my testing will likely  only run once or twice, if at all.  While the ```Connect()``` is blocking nothing will be output so this is really only ever going to happen once the connection has been established and while waiting for the SMO ```Status``` property to go from ```$null```  to ```Online```.    

I'm not opposed to a change but this is just output for the SMO ```Status``` initialization not the connection to the SQL Server itself.  Does that make sense?
___
*[`source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1` line 591 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTfrImDahorOhyqYvn:-NTTxbz14En6QOvT9twU:b-gybukm) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1#L591)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Think we should stop this down in `finally` so that we don't keep counting if an error occurs.
</blockquote></details>

Sure, I'll make this change.
___
*[`source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1` line 47 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTeORw2iRWCYdLk2xq:-NTTxyr1ELbhAXZ1PCV6:b-bwl7b0) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1#L47)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Suggest we also mention that we are "...waiting for x number of seconds". See also other comment of just output it once after like 20 seconds. 
</blockquote></details>

I'll make an update eventually based on the outcome of the above conversation around the waiting.
___
*[`source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1` line 53 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTejpm7xZeH3wC-dF9:-NTTyFz77R-xTpgk-_43:b-bwl7b0) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1#L53)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same change here as previous comment.
</blockquote></details>

I'll make an update eventually based on the outcome of the above conversation around the waiting.


<!-- Sent from Reviewable.io -->

2023-04-20 16:13 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916)* status: all files reviewed, 4 unresolved discussions (waiting on @Kreby)

___
*[`source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1` line 584 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTe2tb96_mQqomgjuu:-NTUQrnR-Pe3fHBRsExz:bkugi5j) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1#L584)):*
<details><summary><i>Previously, Kreby wrote…</i></summary><blockquote>

Theoretically yes, however the loop only executes after the blocking ```Connect()``` was successful.  So this loop could run multiple times but from all of my testing will likely  only run once or twice, if at all.  While the ```Connect()``` is blocking nothing will be output so this is really only ever going to happen once the connection has been established and while waiting for the SMO ```Status``` property to go from ```$null```  to ```Online```.    

I'm not opposed to a change but this is just output for the SMO ```Status``` initialization not the connection to the SQL Server itself.  Does that make sense?
</blockquote></details>

My thought is that we don't need to output the verbose message at all normally (just unnecessary verbose messages). But if it for some reason takes longer then we output the verbose message, or could be a warning too, that it taking longer than expected. Or, we could change it to a `Write-Debug` instead and keep the logic as-is.


<!-- Sent from Reviewable.io -->

2023-04-20 17:54 UTC, Kreby reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[`source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1` line 584 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-NTTe2tb96_mQqomgjuu:-NTUjX905EV6pLsodOF7:bh3ie43) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/c5d865cd4ece93f75f4ae9e5d259bd0a0ef6b939/source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1#L584)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

My thought is that we don't need to output the verbose message at all normally (just unnecessary verbose messages). But if it for some reason takes longer then we output the verbose message, or could be a warning too, that it taking longer than expected. Or, we could change it to a `Write-Debug` instead and keep the logic as-is.
</blockquote></details>

I'm good with using ```Write-Debug``` instead since it is a bit more of a debug message than a verbose one if you are okay with it.


<!-- Sent from Reviewable.io -->

2023-04-25 12:03 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916#-:-NTsI4NK0MSkgwqqQD96:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Kreby)



<!-- Sent from Reviewable.io -->

2023-04-25 12:06 UTC, johlju commented
>  I don't think they are related to this change however. I've submitted as a draft right now until I can do some further testing tomorrow. 

Guessing the issue you were seeing was unrelated. The change should only make it better, didn't see anything that would make anything fail (unless there is an extreme edge case). 🙂 I merge this and if there is any issues we can do an additional PR.

2023-04-25 12:07 UTC, merged