Get-SqlDscPreferredModule: Optionally specify which version of the SQL module is imported
dsccommunity/SqlServerDsc pull request #1966
Opened 2023-08-25 23:40 UTC by YaroBear

#### Pull Request (PR) description

Optionally set the `SMODefaultModuleVersion` environment variable for your preferred module.

For example:
- SqlServer: 22.0.49-preview 
- SQLPS: 130
- OtherModule: <maj.min.patch>

#### This Pull Request (PR) fixes the following issues

- Fixes #1965

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation updated in the resource's README.md.
- [ ] Resource parameter descriptions updated in schema.mof.
- [x] Comment-based help updated, including parameter descriptions.
- [x] Localization strings updated.
- [ ] Examples updated.
- [x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2023-08-26 08:00 UTC, johlju requested changes
Awesome work on this, and impressive work on the unit tests! Just minor comments.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-:-NckqayDB6sxi2iQ86IG:byh6qew)* status: all files reviewed, 11 unresolved discussions (waiting on @YaroBear)

___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 96 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Ncki_gg62U4VKS-l7f1:-Ncki_gg62U4VKS-l7f2:b-fio7gk) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L96)):*
> ```PowerShell
> 
>     $availableModules = Get-Module -Name $Name -ListAvailable |
>         ForEach-Object {
> ```

We should use named parameters. 



_Suggestion:_
```PowerShell
ForEach-Object -Process {
```
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 126 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckiEoE5AV7JZUWd8yX:-NckiEoE5AV7JZUWd8yY:b-fio7gk) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L126)):*
> ```PowerShell
>     {
>         $preferredModules = $availableModules |
>             Where-Object { $_.PSModuleInfo.Name -eq $preferredModuleName}
> ```

We should use named parameters. 



_Suggestion:_
```PowerShell
Where-Object -FilterScript { $_.PSModuleInfo.Name -eq $preferredModuleName}
```
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 126 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Nckj3to5NHwVvbQhQoo:-Nckj3to5NHwVvbQhQop:b-j7rwmz) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L126)):*
> ```PowerShell
>     {
>         $preferredModules = $availableModules |
>             Where-Object { $_.PSModuleInfo.Name -eq $preferredModuleName}
> ```

Couldn't we filter the preferred module from the result from `Get-Module` above directly, before calculating version? It would remove this foreach-loop. :thinking: What do you think` 
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 134 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckjdajC-UIMSlffGRN:-Nckjdak-U6YLxEdnCwP:btabdd0) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L134)):*
> ```PowerShell
>                 # Get the version specified in $env:SMODefaultModuleVersion if available
>                 $availableModule = $preferredModules |
>                 Where-Object { $_.CalculatedVersion -eq $env:SMODefaultModuleVersion} |
> ```

We should use named parameters.



_Suggestion:_
```PowerShell
Where-Object -FIlterScript { $_.CalculatedVersion -eq $env:SMODefaultModuleVersion} |
```
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 135 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NcklM1NEG2sbI46j7SH:-NcklM1NEG2sbI46j7SI:b-cpsfdb) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L135)):*
> ```PowerShell
>                 $availableModule = $preferredModules |
>                 Where-Object { $_.CalculatedVersion -eq $env:SMODefaultModuleVersion} |
>                 Select-Object -First 1
> ```

We should indent these two lines of the pipeline one indent when they are on separate rows (which is good to not make the line too long).



_Code quote:_
```PowerShell
                Where-Object { $_.CalculatedVersion -eq $env:SMODefaultModuleVersion} |
                Select-Object -First 1
```
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 139 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NcklJ4G-VVtw2IO0Xrv:-NcklJ4G-VVtw2IO0Xrw:bfiziky) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L139)):*
> ```PowerShell
>                 Write-Verbose -Message ($script:localizedData.PreferredModule_ModuleVersionFound -f $availableModule.PSModuleInfo.Name, $availableModule.CalculatedVersion)
>             }
>             else {
> ```

We should have open brace on a separate line.



_Code quote:_
```PowerShell
else {
```
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 143 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NcklGf68LRk06gJ7Lur:-NcklGf68LRk06gJ7Lus:b-cpsfdb) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L143)):*
> ```PowerShell
>                 $availableModule = $preferredModules |
>                 Sort-Object -Property 'CalculatedVersion' -Descending |
>                 Select-Object -First 1
> ```

We should indent these two lines of the pipeline one indent when they are on separate rows (which is good to not make the line too long).



_Code quote:_
```PowerShell
                Sort-Object -Property 'CalculatedVersion' -Descending |
                Select-Object -First 1
```
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 145 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckkyHWCSlEJIOlVs5i:-NckkyHWCSlEJIOlVs5j:b-dxgh4o) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L145)):*
> ```PowerShell
>                 Select-Object -First 1
> 
>                 Write-Verbose -Message ($script:localizedData.PreferredModule_ModuleFound -f $availableModule.PSModuleInfo.Name)
> ```

Maybe we could use the string `PreferredModule_ModuleVersionFound` here too, to output the version even if the user did not specify a specific version. It would simplify the code with just one `Write-Verbose` before the `break` and the output is more detailed. :thinking:  What do you think?



_Code quote:_
```PowerShell
PreferredModule_ModuleFound
```
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 83 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckmVBU4m4XMZuHlWct:-NckmVBU4m4XMZuHlWcu:btabdd0) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Import-SqlDscPreferredModule.ps1#L83)):*
> ```PowerShell
>         if ($PSBoundParameters.ContainsKey('Name'))
>         {
>             $removeModule += Get-Module $Name
> ```

We should use named parameters.



_Suggestion:_
```PowerShell
Get-Module -Name $Name
```
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 97 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NcknXRj9nHeoHFlZMlv:-NcknXRj9nHeoHFlZMlw:btabdd0) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Import-SqlDscPreferredModule.ps1#L97)):*
> ```PowerShell
>         }
> 
>         Remove-Module $removeModule -Force -ErrorAction 'SilentlyContinue'
> ```

We should use named parameters.



_Suggestion:_
```PowerShell
Remove-Module -Name $removeModule -Force -ErrorAction 'SilentlyContinue'
```
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 114 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckoA9GC0O3V3zckayv:-NckoA9GC0O3V3zckayw:b9c6z08) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Import-SqlDscPreferredModule.ps1#L114)):*
> ```PowerShell
> 
>                 return
>             }
> ```

What if the wrong version is already imported, what shall happen then? I think we need to throw an exception because then the wrong SMO assemblies has been loaded into the session and that can mess things up if we would just try to import and newer or older version.



_Code quot [...]

2023-08-26 08:00 UTC, johlju commented
I merged another PR so will need to rebase this one.

2023-08-26 08:02 UTC, johlju commented
Also, check the HQRM tests failing (style errors): https://dev.azure.com/dsccommunity/SqlServerDsc/_build/results?buildId=8129&view=logs&j=9150365c-bae3-55fa-031b-59bba4aba4d9&t=dc12ef69-6f79-52f3-2e04-c23de96e6308&l=565

2023-08-28 19:07 UTC, YaroBear reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966)* status: all files reviewed, 11 unresolved discussions (waiting on @johlju)

___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 126 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Nckj3to5NHwVvbQhQoo:-NcwyKtn-CKVDNS1a4O7:bj6e26p) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L126)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Couldn't we filter the preferred module from the result from `Get-Module` above directly, before calculating version? It would remove this foreach-loop. :thinking: What do you think`
</blockquote></details>

We are already filtering by $name on line 95: `$availableModules = Get-Module -Name $Name`

The foreach-loop serves to find the preferred module in the *order* defined by the `$Name` variable.
For example: if `$Name = @('sqlserver', 'sqlps')`, in the foreach-loop, if a sqlserver module is found, it will set `$availableModule = SqlServer` and break from the loop.
If sqlserver module is not found, then it will look for sqlps.
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 114 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckoA9GC0O3V3zckayv:-NcxWwmi7l4Fe0HlSxrG:b-l8aqb4) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Import-SqlDscPreferredModule.ps1#L114)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

What if the wrong version is already imported, what shall happen then? I think we need to throw an exception because then the wrong SMO assemblies has been loaded into the session and that can mess things up if we would just try to import and newer or older version.
</blockquote></details>

Hm, Get-SqlDscPreferredModule probably needs to return not just the PSModuleInfo object, but also the CalculatedVersion property in order to check this accurately for SQLPS (without duplicating logic)

Do you recommend a statement terminating error, i.e `$PSCmdlet.ThrowTerminatingError`?


<!-- Sent from Reviewable.io -->

2023-08-28 21:37 UTC, YaroBear commented
Reviewable.io seems to be down currently...

> Hm, Get-SqlDscPreferredModule probably needs to return not just the PSModuleInfo object, but also the CalculatedVersion property in order to check this accurately for SQLPS (without duplicating logic)

Actually, I think I'll need to reuse the logic either way. Maybe a  private function would be better? Get-SMOModuleCalculatedVersion can be reused in both Get-SqlDscPreferredModule and Import-SqlDscPreferredModule

2023-08-29 00:01 UTC, YaroBear reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966)* status: 1 of 8 files reviewed, 11 unresolved discussions (waiting on @johlju)

___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 96 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Ncki_gg62U4VKS-l7f1:-Ncy_cFRCdrICL-Q6oCl:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L96)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should use named parameters.
</blockquote></details>

Done.
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 126 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckiEoE5AV7JZUWd8yX:-Ncy_drG4v6M1ASTlv8u:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L126)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should use named parameters.
</blockquote></details>

Done.
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 134 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckjdajC-UIMSlffGRN:-Ncy_fRR4F5aAo3UFjMu:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L134)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should use named parameters.
</blockquote></details>

Done.
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 135 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NcklM1NEG2sbI46j7SH:-Ncy_gVD4yaBODIQ1kxI:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L135)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should indent these two lines of the pipeline one indent when they are on separate rows (which is good to not make the line too long).
</blockquote></details>

Done.
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 139 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NcklJ4G-VVtw2IO0Xrv:-Ncy_hDX9nw7y9WT5Q05:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L139)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should have open brace on a separate line.
</blockquote></details>

Done.
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 143 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NcklGf68LRk06gJ7Lur:-Ncy_i4ABdZg9PSDCB_d:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L143)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should indent these two lines of the pipeline one indent when they are on separate rows (which is good to not make the line too long).
</blockquote></details>

Done.
___
*[`source/Public/Get-SqlDscPreferredModule.ps1` line 145 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckkyHWCSlEJIOlVs5i:-Ncy_j2-4kJ6srlwe1fQ:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Get-SqlDscPreferredModule.ps1#L145)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe we could use the string `PreferredModule_ModuleVersionFound` here too, to output the version even if the user did not specify a specific version. It would simplify the code with just one `Write-Verbose` before the `break` and the output is more detailed. :thinking:  What do you think?
</blockquote></details>

Done.
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 83 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckmVBU4m4XMZuHlWct:-Ncy_kYk1GxP5xnYUwjJ:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Import-SqlDscPreferredModule.ps1#L83)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should use named parameters.
</blockquote></details>

Done.
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 97 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NcknXRj9nHeoHFlZMlv:-Ncy_lEW6O8sDBtryTQQ:b-896fix) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Import-SqlDscPreferredModule.ps1#L97)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should use named parameters.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-29 01:07 UTC, YaroBear commented
@johlju 

I'm running this and don't seem to be getting any ScriptAnalyzer issues locally. VS Code doesn't seem to be picking up on anything either. Any advice?
```
Invoke-ScriptAnalyzer -Path .\source\DSCResources\**\*.psm1 -CustomRulePath .\tests\QA\AnalyzerRules\SqlServerDsc.AnalyzerRules.psm1 -IncludeRule @('Measure-*')
```

Also, getting some test failures in the pipeline for the new private function I added. What am I missing for the function to be picked up?
`Get-SMOModuleCalculatedVersion' is not recognized as a name of a cmdlet`

2023-08-29 17:18 UTC, johlju commented
I will continue review tomorrow I hope. Looks like you answered all questions yourself? 🙂

2023-08-29 19:33 UTC, YaroBear commented
> I will continue review tomorrow I hope. Looks like you answered all questions yourself? 🙂

Yep, I think so! Thanks!

2023-08-30 15:40 UTC, johlju requested changes
Great thought moving the calculation of module version to a private function! Just a few more comments.

> Reviewed 4 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-:-Nd65ZMy6OjkmyON7bgd:bgaoqpq)* status: all files reviewed, 2 unresolved discussions (waiting on @YaroBear)

___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 114 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckoA9GC0O3V3zckayv:-Nd65FGr23Khfm1N14qb:b-xqune0) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Import-SqlDscPreferredModule.ps1#L114)):*
<details><summary><i>Previously, YaroBear (Yaroslav Berejnoi) wrote…</i></summary><blockquote>

Hm, Get-SqlDscPreferredModule probably needs to return not just the PSModuleInfo object, but also the CalculatedVersion property in order to check this accurately for SQLPS (without duplicating logic)

Do you recommend a statement terminating error, i.e `$PSCmdlet.ThrowTerminatingError`?
</blockquote></details>

My bad, it seems there was a bug prior to this change that should have thrown, see previous comment.
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 73 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Nd64JUa3SggJp7j4EV4:-Nd64JUa3SggJp7j4EV5:b-xjpqw3) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/00451e4f8c7d8d1de3795ed8c41c129d000debd1/source/Public/Import-SqlDscPreferredModule.ps1#L73)):*
> ```PowerShell
>     }
> 
>     $availableModule = Get-SqlDscPreferredModule @getSqlDscPreferredModuleParameters
> ```

This should be called with `-ErrorAction 'Stop'` so that it throws if the wrong version is found, or if no module is found at all. This seems like this was a bug prior to this change.
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 123 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Nd64rvOEe_-dmUjxNUk:-Nd64rvOEe_-dmUjxNUl:b-2597v2) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/00451e4f8c7d8d1de3795ed8c41c129d000debd1/source/Public/Import-SqlDscPreferredModule.ps1#L123)):*
> ```PowerShell
>                         )
>                     )
>                 }
> ```

No sure we need this error since Get-SqlDscPreferredModule should throw an exception prior to this (see previous comment). :thinking:  Do you agree?



_Code quote:_
```PowerShell
                $loadedModuleCalculatedVersion = $loadedModule | Get-SMOModuleCalculatedVersion
                $availableModuleCalculatedVersion = $availableModule | Get-SMOModuleCalculatedVersion
                if ($env:SMODefaultModuleVersion -and $loadedModuleCalculatedVersion -ne $availableModuleCalculatedVersion)
                {
                    $PSCmdlet.ThrowTerminatingError(
                        [System.Management.Automation.ErrorRecord]::new(
                            ($script:localizedData.PreferredModule_WrongModuleVersionLoaded -f $loadedModule.Name, $loadedModule.Version, $availableModule.Version),
                            'ISDPM0001', # cspell: disable-line
                            [System.Management.Automation.ErrorCategory]::ObjectNotFound,
                            'PreferredModule'
                        )
                    )
                }
```


<!-- Sent from Reviewable.io -->

2023-08-31 15:55 UTC, YaroBear reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 114 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-NckoA9GC0O3V3zckayv:-NdBITPz9bQqvU4zTABo:b-49fxom) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/e7158ea7cfa3091eccae508cdd198e1be25e3de2/source/Public/Import-SqlDscPreferredModule.ps1#L114)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

My bad, it seems there was a bug prior to this change that should have thrown, see previous comment.
</blockquote></details>

Got it! Thanks. Will make the update
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 73 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Nd64JUa3SggJp7j4EV4:-NdBIJXtAi_FmjDLvyBK:b-lci04z) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/00451e4f8c7d8d1de3795ed8c41c129d000debd1/source/Public/Import-SqlDscPreferredModule.ps1#L73)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This should be called with `-ErrorAction 'Stop'` so that it throws if the wrong version is found, or if no module is found at all. This seems like this was a bug prior to this change.
</blockquote></details>

ah right, that will make Write-Error in Get-SqlDscPreferredModule a terminating error. Got it!
___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 123 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Nd64rvOEe_-dmUjxNUk:-NdBHjQoEQSeqSc8j9Qo:b-pbdqzg) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/00451e4f8c7d8d1de3795ed8c41c129d000debd1/source/Public/Import-SqlDscPreferredModule.ps1#L123)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

No sure we need this error since Get-SqlDscPreferredModule should throw an exception prior to this (see previous comment). :thinking:  Do you agree?
</blockquote></details>

Agreed!


<!-- Sent from Reviewable.io -->

2023-08-31 16:24 UTC, YaroBear reviewed
Thanks!

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-:-NdBP8LUBle0l6Hiyi-2:b-ucfknh)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 73 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Nd64JUa3SggJp7j4EV4:-NdBOgrj3HVV-QnoRmn0:b3pom4) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/00451e4f8c7d8d1de3795ed8c41c129d000debd1/source/Public/Import-SqlDscPreferredModule.ps1#L73)):*
<details><summary><i>Previously, YaroBear (Yaroslav Berejnoi) wrote…</i></summary><blockquote>

ah right, that will make Write-Error in Get-SqlDscPreferredModule a terminating error. Got it!
</blockquote></details>

Just checking, instead of the if/else we should now wrap `Get-SqlDscPreferredModule` in a try/catch with the $PSCmdlet.ThrowTerminating error in the catch body?

![image.png](https://files.reviewableusercontent.io/images/reviewable/5227017/nDmYRJ_QXkyWUqSS1v22BLMK/image.png)


<!-- Sent from Reviewable.io -->

2023-08-31 19:21 UTC, johlju commented
*[`source/Public/Import-SqlDscPreferredModule.ps1` line 73 at r3](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-Nd64JUa3SggJp7j4EV4:-NdC0-wJ-RhFHrmvyee8:bqnxwcx) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/00451e4f8c7d8d1de3795ed8c41c129d000debd1/source/Public/Import-SqlDscPreferredModule.ps1#L73)):*
<details><summary><i>Previously, YaroBear (Yaroslav Berejnoi) wrote…</i></summary><blockquote>

Just checking, instead of the if/else we should now wrap `Get-SqlDscPreferredModule` in a try/catch with the $PSCmdlet.ThrowTerminating error in the catch body?

![image.png](https://files.reviewableusercontent.io/images/reviewable/5227017/nDmYRJ_QXkyWUqSS1v22BLMK/image.png)
</blockquote></details>

There are already and error thrown for us in the Get-command  (the command Write-Error) so by adding ErrorAction to our call here we make sure that when the Write-Error is executed we get a terminating error. 

So no need for a try/catch here and no need for adding any kind of extra throw in the import-command . The logic for checking for the wrong version is in the get function and it is that function that throws an error. 

A user can igonore the error in the Get-command by adding `ErrorAction ‘SilentlyContinue’` but we want a terminating  error so we call it with ‘Stop’. 

Hope that is more clear what I meant. 😊


<!-- Sent from Reviewable.io -->

2023-08-31 22:42 UTC, YaroBear commented
@johlju Were you able to check my last commit?
There was an `if($availableModule) else $PSCmdlet.ThrowTerminatingError` at the bottom of the script *prior* to my changes.

Now that the Get command has an `erroraction 'stop`', I replaced the if/else with try/catch. Otherwise we will get a script terminating error instead of a statement terminating error.

Are we getting rid of $PSCmdlet.ThrowTerminatingError entirely now so that it's a script terminating error?

2023-09-01 05:35 UTC, johlju commented
No worries, glad you discussion and double checking so we get it correct. After testing running the code I do like your change so let's keep it! :slightly_smiling_face: 

But not sure what you mean by script terminating error? Can you explain what you meant by "script terminating error" so I understand what you meant for the future? :slightly_smiling_face: 

If we call `Get-SqlDscPreferredModule` we get this exception:

```powershell
PS> Get-SqlDscPreferredModule -ErrorAction stop
Get-SqlDscPreferredModule : No preferred PowerShell module was found.
At line:1 char:1
+ Get-SqlDscPreferredModule -ErrorAction stop
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (SqlServer, SQLPS:String) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : GSDPM0001,Get-SqlDscPreferredModule
```

Running `Import-SqlDscPreferredModule` we get this exception (with your change):

```powershell
PS> Import-SqlDscPreferredModule
Import-SqlDscPreferredModule : Failed to find a dependent module. Unable to run SQL Server commands or use SQL Server types. Please install one of the preferred SMO modules or the SQLPS module, then try to import SqlServerDsc again.
At line:1 char:1
+ Import-SqlDscPreferredModule
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (PreferredModule:String) [Import-SqlDscPreferredModule], Exception
+ FullyQualifiedErrorId : ISDPM0001,Import-SqlDscPreferredModule
```

The only difference (except for the error message and command name) is the category information were it says `Write-Error` in the first one. 





<!-- Sent from Reviewable.io -->

2023-09-01 05:38 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966#-:-NdEEwTjD55-CmF-wO-2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YaroBear)



<!-- Sent from Reviewable.io -->

2023-09-01 05:46 UTC, johlju commented
Awesome work on this @YaroBear. I kicked off the failed tests again, will merge once they passes.

2023-09-01 15:03 UTC, YaroBear commented
Awesome, thanks for working with me and having the great discussions! I wasn't aware of the difference between `throw` (pipeline terminating error) and `$pscmdlet.ThrowTerminatingError` (statement terminating error) before this PR actually.

I got the information from [this stackoverflow](https://stackoverflow.com/questions/49204918/difference-between-throw-and-pscmdlet-throwterminatingerror). So it might not be accurate as it's not in the official PowerShell docs:

> a script-terminating error terminates the entire runspace by default. i.e., the running script and all its callers, with no further statements getting executed

> whereas a statement-terminating error terminates only the current statement (the function calling $PScmdlet.ThrowTerminatingError() and the statement it is a part of, which is often a pipeline), with execution continuing with the next statement by default.

2023-09-01 16:10 UTC, johlju commented
I learned something new today too. But that article does not mention `Write-Error` which does non-terminating errors, so it too should allow a pipeline to continue running unless `ErrorAction` is set to `Stop`. 🤔  The statment `throw` should not be used, but mostly because it outputs the exception badly visually. It is mentioned here https://github.com/dsccommunity/SqlServerDsc/blob/main/CONTRIBUTING.md#commands but that text might take in account how to throw when a command supports a pipelines. I always assumed one should use `Write-Error` in those cases. 🤔

2023-09-01 16:20 UTC, merged

2023-09-01 17:04 UTC, YaroBear commented
[This portion of CONTRIBUTING.md](https://github.com/dsccommunity/SqlServerDsc/blob/main/CONTRIBUTING.md#terminating-error-1) specifies:
> If a command shall throw an terminating error then the statement throw shall not be used, neither shall the command Write-Error with the parameter -ErrorAction Stop. Always use the method $PSCmdlet.ThrowTerminatingError() to throw a terminating error.

Although we are not setting `Write-Error "" -ErrorAction 'Stop'` *directly* in `Get-SqlDscPreferredModule`, we are setting it *indirectly* by writing `Get-SqlDscPreferredModule -ErrorAction 'Stop'`. See the example code at the bottom of this comment.

So I think we *have* to have the try/catch block on `Get-SqlDscPreferredModule -ErrorAction 'Stop'` otherwise the entire DSC script will terminate.

Example code:

- Calling `Invoke-WriteErrowWithErrorActionStop`, we see that Write-Host within the function is *not* executed after we encounter the Write-Error
- Calling `Invoke-ThrowTerminatingErrorAndLog`, we see that Write-Host within the function *is* executed after we encounter $PScmdlet.ThrowTerminatingError

```powershell
function Invoke-WriteError {
    [CmdletBinding()]
    param (
    )

    Write-Error 'An error occured'
}

function Invoke-ThrowTerminatingError() {
    [CmdletBinding()]
    param (
    )
    $PScmdlet.ThrowTerminatingError(
        [System.Management.Automation.ErrorRecord]::new(
        ('Command terminating error'),
        'ISDPM0001',
        [System.Management.Automation.ErrorCategory]::InvalidOperation,
        'CommandTerminatingError'
    ))
}

function Invoke-WriteErrorWithErrorActionStop() {
    Invoke-WriteError -ErrorAction 'Stop'

    Write-Host "This line should not be reached"
}


function Invoke-ThrowTerminatingErrorAndLog() {
    Invoke-ThrowTerminatingError

    Write-Host "This line should be reached"
}
```

![image](https://github.com/dsccommunity/SqlServerDsc/assets/5227017/97aa15b3-c221-4e3a-a577-72ad4bd9d20c)

2023-09-02 08:42 UTC, johlju commented
I did not know that `$PScmdlet.ThrowTerminatingError` did not actually terminated the script. Agree that the change that was made in the PR was the correct one.

But if the above function 'ThrowTerminatingErrorAndLog` is made like this:

```powershell
function Invoke-ThrowTerminatingErrorAndLog {
    [CmdletBinding()]
    param (
    )
    
    Invoke-ThrowTerminatingError

    Write-Host "This line should be reached"
}
```

Then called with `-ErrorAction 'Stop'` then the `Write-Host´ are not reached.

```
PS > Invoke-ThrowTerminatingErrorAndLog -ErrorAction 'Stop'
Invoke-ThrowTerminatingError: 
Line |
   6 |      Invoke-ThrowTerminatingError
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Command terminating error
```

But that requires that the user actually knows to pass in `ErrorAction 'Stop'` to actually stop the script.

2023-09-02 09:20 UTC, johlju commented
Testing this with a pipeline this is how I would expected it to work

```powershell
function Invoke-PipelineThrow 
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
        [System.String]
        $MyStringValue 
    )

    process
    {
        Write-Host ("Start PROCESS for value '{0}'" -f $MyStringValue)

        if ($MyStringValue -eq 'ThrowWriteError')
        {
            Write-Error -Message ("Non-terminating error for value '{0}'" -f $MyStringValue)
        }

        if ($MyStringValue -eq 'ThrowTerminatingError')
        {
            $PScmdlet.ThrowTerminatingError(
                [System.Management.Automation.ErrorRecord]::new(
                ("Terminating error for value '{0}'" -f $MyStringValue),
                'UniqueID',
                [System.Management.Automation.ErrorCategory]::InvalidOperation,
                $MyStringValue
            ))
        }

        Write-Host ("Ran all of PROCESS for value '{0}'" -f $MyStringValue)
    }

    end
    {
        Write-Host "Reached END"
    }
}
```

Running this we see that `$PScmdlet.ThrowTerminatingError` will terminate the pipeline (as I would ecpect), while `Write-Error` will not stop the pipeline as it is a non-terminating error.

```powershell
PS > 'FirstValue', 'SecondValue', 'ThrowWriteError', 'ThrowTerminatingError', 'LastValue' | Invoke-PipelineThrow
Start PROCESS for value 'FirstValue'
Ran all of PROCESS for value 'FirstValue'
Start PROCESS for value 'SecondValue'
Ran all of PROCESS for value 'SecondValue'
Start PROCESS for value 'ThrowWriteError'
Invoke-PipelineThrow: Non-terminating error for value 'ThrowWriteError'
Ran all of PROCESS for value 'ThrowWriteError'
Start PROCESS for value 'ThrowTerminatingError'
Invoke-PipelineThrow: Terminating error for value 'ThrowTerminatingError'
```
Even if we pass in `'SilentlyContinue'` the `$PScmdlet.ThrowTerminatingError` will still terminate the pipeline.

```powershell
PS > 'FirstValue', 'SecondValue', 'ThrowWriteError', 'ThrowTerminatingError', 'LastValue' | Invoke-PipelineThrow -ErrorAction 'SilentlyContinue'
Start PROCESS for value 'FirstValue'
Ran all of PROCESS for value 'FirstValue'
Start PROCESS for value 'SecondValue'
Ran all of PROCESS for value 'SecondValue'
Start PROCESS for value 'ThrowWriteError'
Ran all of PROCESS for value 'ThrowWriteError'
Start PROCESS for value 'ThrowTerminatingError'
Invoke-PipelineThrow: Terminating error for value 'ThrowTerminatingError'
```

If we pass in `ErrorAction 'Stop'` we will se that `Write-Error` will also become a terminating error.

```powershell
PS > 'FirstValue', 'SecondValue', 'ThrowWriteError', 'ThrowTerminatingError', 'LastValue' | Invoke-PipelineThrow -ErrorAction 'Stop'
Start PROCESS for value 'FirstValue'
Ran all of PROCESS for value 'FirstValue'
Start PROCESS for value 'SecondValue'
Ran all of PROCESS for value 'SecondValue'
Start PROCESS for value 'ThrowWriteError'
Invoke-PipelineThrow: Non-terminating error for value 'ThrowWriteError'
```

So I guess one must use `$PScmdlet.ThrowTerminatingError` and `Write-Error` depending on how the commands should be used. I normally use `Write-Error` in `Get-*`-commands where errors should be able to be ignored and use `$PScmdlet.ThrowTerminatingError` in commands that change state so they terminate the action. But what I did not know was that `$PScmdlet.ThrowTerminatingError` did not terminate the parent function/script that use it. Learned something new, thank you.