https://github.com/RandyInMarin/SqlServerDsc/blob/main/CHANGELOG.md
dsccommunity/SqlServerDsc pull request #2001
Opened 2024-02-17 01:15 UTC by RandyInMarin

#### Pull Request (PR) description

Added the parameter UseDefaultCredentials to the SqlDatabasemailDsc resource to allow setting the value to the non-default value of $true.  This will result in the database engine service account credentials being used to authenticate with the SMTP server.  There is no need to specify a custom login in this case.  If the default $false is used, the SMTP login will be anonymous unless a login was specified for SMTP access.  

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x ] Resource documentation updated in the resource's README.md.
- [ x] Resource parameter descriptions updated in schema.mof.
- [x ] Comment-based help updated, including parameter descriptions.
- [ ] Localization strings updated.
- [ ] Examples updated.
- [ x] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x ] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2024-02-17 10:36 UTC, johlju requested changes
I will continue the review once these comment are fixed.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001#-:-Nqqcgz83j7195FtIYYr:b-bhtnm7)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @RandyInMarin)

___
*[`CHANGELOG.md` line 12 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001#-NqqZNkOEf5rStsXr84U:-NqqZNkOEf5rStsXr84V:b-1rc3a7) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/861cfd0a3970022e2b756c3836e7a5a405decf90/CHANGELOG.md#L12)):*
> ```Markdown
> - SqlServerDsc
>   - Added build tasks to generate Wiki documentation for public commands.
> - SqlDatabaseMailDsc
> ```

Should be just `SqlDatabaseMail`



_Suggestion:_
```Markdown
SqlDatabaseMail
```
___
*[`CHANGELOG.md` line 16 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001#-NqqZZT7ChGb0KmCZivO:-NqqZZT7ChGb0KmCZivP:bz12es5) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/861cfd0a3970022e2b756c3836e7a5a405decf90/CHANGELOG.md#L16)):*
> ```Markdown
>     SMTP server authentication uses the DatabaseEngine service account. The
>     default is $false which uses a login specified for SMTP authorization.
>     If false and no custom login specified, an anonymous login is used.
> ```

How do we specify a custom login?
___
*[`source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1` line 149 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001#-Nqq_3Ny-OUepBzNthFa:-Nqq_3Ny-OUepBzNthFb:b-avbnz3) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/861cfd0a3970022e2b756c3836e7a5a405decf90/source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1#L149)):*
> ```PowerShell
>                     $returnValue['MailServerName'] = $mailServer.Name
>                     $returnValue['TcpPort'] = $mailServer.Port
>                     $returnValue['UseDefaultCredentials'] = $mailServer.UseDefaultCredentials # custom
> ```

Do we need this comment? It is non descriptive. Throughout.
___
*[`source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1` line 241 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001#-Nqq_JuCCFw-Aao1BRpF:-Nqq_JuCCFw-Aao1BRpG:bheeix3) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/861cfd0a3970022e2b756c3836e7a5a405decf90/source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1#L241)):*
> ```PowerShell
>         Controls SMTP server authentication.  The database engine credentials are
>         the default credentials used when $true.  If not specified, the default is
>         $false and an anonymous login is used unless other credentials are provided.
> ```

Same as a previous comment. How do we provide other credentials with this change?
___
*[`source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1` line 241 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001#-NqqbL6w4Je20djH71pP:-NqqbL6w4Je20djH71pQ:be0aa8i) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/861cfd0a3970022e2b756c3836e7a5a405decf90/source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1#L241)):*
> ```PowerShell
>         Controls SMTP server authentication.  The database engine credentials are
>         the default credentials used when $true.  If not specified, the default is
>         $false and an anonymous login is used unless other credentials are provided.
> ```

Suggest changing to this, please change as appropriate if you see it different :slightly_smiling_face: Throughout the changes. 



_Suggestion:_
```PowerShell
        Controls the SMTP server authentication. When set to `$true` the database engine
        credentials are used as the SMTP server authentication. When set to `$false` or
        not specified, anonymous login is used unless other credentials are provided.
```
___
*[`source/DSCResources/DSC_SqlDatabaseMail/en-US/DSC_SqlDatabaseMail.strings.psd1` line 25 at r1](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001#-Nqqa8YE2-U27qg3jpm7:-Nqqa8YE2-U27qg3jpm8:b-qrxo6e) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/861cfd0a3970022e2b756c3836e7a5a405decf90/source/DSCResources/DSC_SqlDatabaseMail/en-US/DSC_SqlDatabaseMail.strings.psd1#L25)):*
> ```PowerShell
>     MailServerPropertyServerName = server name
>     MailServerPropertyTcpPort = TCP port
>     MailServerPropertyUseDefaultCredentials = SMTP server authentication
> ```

We should change this to the property name.



_Suggestion:_
```PowerShell
Use default credentials
```


<!-- Sent from Reviewable.io -->

2024-02-17 10:39 UTC, johlju commented
@RandyInMarin great work on this! 🙂

2024-02-18 03:09 UTC, RandyInMarin commented
@johlju Hi, can you guide me on how I apply the change to the fork.  Do I fix locally and push to the existing fork?  Then do I push or something the change to the existing pull request?

The "custom" comment does not belong.  I copied the code and made edits.  I decided to try fork and a pull request instead.  

Current, the SqlDatabaseMail supports only the $false case, the default.  This is the case that uses the configured account or anonymous SMPT login.  Adding the option for $true (the one I need) does not address the missing parameters to configure the SMPT login account.  (There is another abandoned fork for that, I think.)  For now, as before, the configuring the SMPT account is not done here.  If somebody does set it via SSMS one at a time, they would have good reason to update this resource to add those parameters.)  Is it okay to add support for $true and leave the existing $false support the same... with documentation explaining the lack of support for the login?  

Passing in an account name for the login might not be bad.  I would not know how to pass in a password securely.  

BTW My use case does not include the LCM.  I will be using invoke-dscresource.  This method matches current practice at work but is more elegant.  This should avoid future DSC v3 incompatibilities because existing resources will still work - but not configuration or mof files.  That's my understanding, anyway.

2024-02-19 17:56 UTC, johlju commented
> @johlju Hi, can you guide me on how I apply the change to the fork? Do I fix locally and push to the existing fork? Then do I push or something the change to the existing pull request?

Yes, you push commits to the same working branch in your fork as is in the PR (you used `main` in your case)

> The "custom" comment does not belong. I copied the code and made edits. I decided to try fork and a pull request instead.

We can update the text to reflect what works per the change.

> Currently SqlDatabaseMail supports only the $false case, the default. This is the case that uses the configured account or anonymous SMPT login. Adding the option for $true (the one I need) does not address the missing parameters to configure the SMPT login account. (There is another abandoned fork for that, I think.) For now, as before, the configuring the SMPT account is not done here. If somebody does set it via SSMS one at a time, they would have good reason to update this resource to add those parameters.) Is it okay to add support for $true and leave the existing $false support the same... with documentation explaining the lack of support for the login?

Yes, just chnage the texts explaining what the parameter does. The other can be made in another PR.

> Passing in an account name for the login might not be bad. I would not know how to pass in a password securely.

It is done through a parameter with the `PSCredential` type.

> BTW My use case does not include the LCM. I will be using invoke-dscresource. This method matches current practice at work but is more elegant. This should avoid future DSC v3 incompatibilities because existing resources will still work - but not configuration or mof files. That's my understanding, anyway.

I think MOF resources will not work, only class-based resources, but haven't dug into DSCv3 yet.

2024-02-20 20:13 UTC, RandyInMarin commented
@johlju I made the updates.  I changed the documentation to isolate UseDefaultCredentials from basic or anonymous authentication.  I used the notes section to clarify.  

When designing a dsc resource, should parameters match those use in the SMO? For example, I think "Use default credential" plus an account name and password is confusing.  It seems like a UseDefaultCredential switch would be clearer.  If the switch is specified, then the account name and password are not allowed parameters?  Otherwise, specifying an account name means basic authentication.  If no account name or switch, it's anonymous?  

I suppose the same can be said for a gMSA when trying to specify a password for a service account.  One account name for simplicity, but one of two parameters for the password - password or gMSA switch?

Use a switch only when the corresponding property(s) is not to be specified or must have a specific value?  -gMSA -> no password.  -UseDefaultCredential -> UseDefaultCredential is $true plus no account or password.  -Anonymous -> UseDefaultCredential is $false plus no account or password.  -Basic -> UseDefaultCredential is $false plus account and password required.  

Perhaps this is too much business logic for a dsc resource....

2024-03-02 14:09 UTC, johlju commented
> When designing a dsc resource, should parameters match those use in the SMO? For example, I think "Use default credential" plus an account name and password is confusing. It seems like a UseDefaultCredential switch would be clearer. If the switch is specified, then the account name and password are not allowed parameters? Otherwise, specifying an account name means basic authentication. If no account name or switch, it's anonymous?

Sounds good to me.

> I suppose the same can be said for a gMSA when trying to specify a password for a service account. One account name for simplicity, but one of two parameters for the password - password or gMSA switch?

We have a design pattern for this here: https://github.com/dsccommunity/SqlServerDsc/blob/main/CONTRIBUTING.md#credentials-that-does-not-have-password

2024-03-02 14:14 UTC, johlju commented
> When designing a dsc resource, should parameters match those use in the SMO?

Not necessarily.

2024-03-02 14:15 UTC, johlju requested changes
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001)* status: all files reviewed, 2 unresolved discussions (waiting on @RandyInMarin)

___
*[`source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.schema.mof` line 16 at r2](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001#-NrzVQdx0FnyUE85gSdM:-NrzVQdx0FnyUE85gSdN:bqecmfk) ([raw file](https://github.com/dsccommunity/SqlServerDsc/blob/bfbcc22d0e76ec7a7a98dcb68f20fa4ff2e14b5b/source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.schema.mof#L16)):*
> ```
>     [Write, Description("The logging level that the _Database Mail_ will use. If not specified the default logging level is `'Extended'`."), ValueMap{"Normal","Extended","Verbose"}, Values{"Normal","Extended","Verbose"}] String LoggingLevel;
>     [Write, Description("The TCP port used for communication. Default value is port `25`.")] UInt16 TcpPort;
>     [Write, Description("Specifies if the DatabaseEngine credentials are used for SMTP server authentication. The default is `$false`.")] Boolean UseDefaultCredentials;
> ```

Should no longer say "The default is `$false`." 


<!-- Sent from Reviewable.io -->

2024-03-02 14:16 UTC, johlju commented
Just a tiny comment left, then I think this is ready to merge.

2024-03-02 22:34 UTC, RandyInMarin commented
> Just a tiny comment left, then I think this is ready to merge.

@johlju Made the tiny change.

2024-03-03 08:38 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001#-:-Ns2SdOYAvnLXSBabAsF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RandyInMarin)



<!-- Sent from Reviewable.io -->

2024-03-03 10:55 UTC, merged

2024-03-03 10:56 UTC, johlju commented
@RandyInMarin great work on this! 🙂